export const me = {
  "gender": "male",
  "name": {
    "title": "mr",
    "first": "lance",
    "last": "thomas"
  },
  "location": {
    "street": "6942 first street",
    "city": "elk grove",
    "state": "new hampshire",
    "postcode": 30411
  },
  "email": "lance.thomas@example.com",
  "login": {
    "username": "organicmouse687",
    "password": "frodo1",
    "salt": "0cSpyp70",
    "md5": "bf758d9c79ef3c8a2c3fd900fb0c3148",
    "sha1": "4f28fcd2d5e5ae5e0ff55b7528841e350cabf9fb",
    "sha256": "1d44ef3ad01dafe929c56021498d8a6d89b2c438bd3f6a07de777ed35b98b5e1"
  },
  "dob": "1969-12-14 07:28:16",
  "registered": "2010-08-09 13:37:38",
  "phone": "(589)-070-0928",
  "cell": "(110)-065-6280",
  "id": {
    "name": "SSN",
    "value": "408-64-0336"
  },
  "picture": {
    "large": "https://randomuser.me/api/portraits/men/2.jpg",
    "medium": "https://randomuser.me/api/portraits/med/men/2.jpg",
    "thumbnail": "https://randomuser.me/api/portraits/thumb/men/2.jpg"
  },
  "nat": "US"
};

export const users = [
  {
    "gender": "male",
    "name": {
      "title": "mr",
      "first": "jacob",
      "last": "wilson"
    },
    "location": {
      "street": "3649 dieppe ave",
      "city": "maitland",
      "state": "nunavut",
      "postcode": 58699
    },
    "email": "jacob.wilson@example.com",
    "login": {
      "username": "smallmouse862",
      "password": "christin",
      "salt": "2syKiC3G",
      "md5": "38abd66466233cb15cbe32bc9bfe5159",
      "sha1": "9aa0e9f0cf924bfe649d20eda1defd1dcb6ac20b",
      "sha256": "3ac7bc516b195eab9f6c91ebc093a0ac35ef35cdb292cca0beaef22feb835226"
    },
    "dob": "1979-12-06 16:10:13",
    "registered": "2008-12-25 08:51:40",
    "phone": "132-274-9669",
    "cell": "889-621-4075",
    "id": {
      "name": "",
      "value": null
    },
    "picture": {
      "large": "https://randomuser.me/api/portraits/men/29.jpg",
      "medium": "https://randomuser.me/api/portraits/med/men/29.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/men/29.jpg"
    },
    "nat": "CA"
  },
  {
    "gender": "male",
    "name": {
      "title": "mr",
      "first": "barış",
      "last": "adal"
    },
    "location": {
      "street": "3875 fatih sultan mehmet cd",
      "city": "elazığ",
      "state": "erzincan",
      "postcode": 44000
    },
    "email": "barış.adal@example.com",
    "login": {
      "username": "goldenduck344",
      "password": "dogwood",
      "salt": "s3YLIy3o",
      "md5": "0475fbb9357434458f8b5990b6d8bf38",
      "sha1": "1d1d086f2b255eec0fb905ec171d2552ed5352c6",
      "sha256": "472543aba428f162187dae5cf4d8e851410e7b6a5ee66511c277c3266db87684"
    },
    "dob": "1980-05-31 10:31:12",
    "registered": "2013-06-10 12:48:40",
    "phone": "(483)-824-9134",
    "cell": "(255)-294-7516",
    "id": {
      "name": "",
      "value": null
    },
    "picture": {
      "large": "https://randomuser.me/api/portraits/men/17.jpg",
      "medium": "https://randomuser.me/api/portraits/med/men/17.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/men/17.jpg"
    },
    "nat": "TR"
  },
  {
    "gender": "female",
    "name": {
      "title": "miss",
      "first": "lillie",
      "last": "fox"
    },
    "location": {
      "street": "7057 nowlin rd",
      "city": "salem",
      "state": "south dakota",
      "postcode": 47964
    },
    "email": "lillie.fox@example.com",
    "login": {
      "username": "browngorilla270",
      "password": "carnage",
      "salt": "9wvhzjAh",
      "md5": "34d6d4b7b4622e7f2b62009c7e6a8c2b",
      "sha1": "18399e977056770b332ff7f9e6d3bab02a141e8d",
      "sha256": "96ad392016f86432a04a8f4915cda7b5631e6aefcdfee5624f3af00ca7836375"
    },
    "dob": "1970-11-05 12:45:41",
    "registered": "2012-03-02 19:36:43",
    "phone": "(115)-485-1830",
    "cell": "(611)-766-4831",
    "id": {
      "name": "SSN",
      "value": "527-24-8023"
    },
    "picture": {
      "large": "https://randomuser.me/api/portraits/women/11.jpg",
      "medium": "https://randomuser.me/api/portraits/med/women/11.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/women/11.jpg"
    },
    "nat": "US"
  },
  {
    "gender": "male",
    "name": {
      "title": "mr",
      "first": "andreas",
      "last": "madsen"
    },
    "location": {
      "street": "3556 toften",
      "city": "aarhus n",
      "state": "midtjylland",
      "postcode": 13212
    },
    "email": "andreas.madsen@example.com",
    "login": {
      "username": "goldenswan363",
      "password": "wildfire",
      "salt": "zP8XuLKg",
      "md5": "408ce5aba22c645de30f4d2b1999c77c",
      "sha1": "7ce249e5022c273a4b0ddc92f3aeff702e5d0bf7",
      "sha256": "3d28d4bc78a672bfc3244eeb0a1c443d0f2b90f0508d7de27b5d09048ad81b32"
    },
    "dob": "1994-08-27 13:14:43",
    "registered": "2002-07-20 02:28:10",
    "phone": "10970265",
    "cell": "71929658",
    "id": {
      "name": "CPR",
      "value": "720294-2175"
    },
    "picture": {
      "large": "https://randomuser.me/api/portraits/men/64.jpg",
      "medium": "https://randomuser.me/api/portraits/med/men/64.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/men/64.jpg"
    },
    "nat": "DK"
  },
  {
    "gender": "female",
    "name": {
      "title": "mrs",
      "first": "clara",
      "last": "taylor"
    },
    "location": {
      "street": "5485 tecumseh rd",
      "city": "cumberland",
      "state": "manitoba",
      "postcode": 34574
    },
    "email": "clara.taylor@example.com",
    "login": {
      "username": "yellowdog477",
      "password": "trance",
      "salt": "EYRVQEck",
      "md5": "16661668b93288a0ad3a284eab937739",
      "sha1": "db1b99f99a4ac15ab888212eeed544571913a956",
      "sha256": "4a6b4762fc7cc29fba8c3c0d9cfa8887fdea0bfc8e63c5b9d9abdd25b108b957"
    },
    "dob": "1973-06-23 07:23:41",
    "registered": "2015-09-19 03:38:38",
    "phone": "577-722-0568",
    "cell": "792-577-6875",
    "id": {
      "name": "",
      "value": null
    },
    "picture": {
      "large": "https://randomuser.me/api/portraits/women/50.jpg",
      "medium": "https://randomuser.me/api/portraits/med/women/50.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/women/50.jpg"
    },
    "nat": "CA"
  },
  {
    "gender": "female",
    "name": {
      "title": "mrs",
      "first": "denise",
      "last": "jones"
    },
    "location": {
      "street": "7749 ash dr",
      "city": "tamworth",
      "state": "south australia",
      "postcode": 9010
    },
    "email": "denise.jones@example.com",
    "login": {
      "username": "heavygoose871",
      "password": "sanity72",
      "salt": "vIiJHC1f",
      "md5": "703ae4647b62d49d08ae52fd69f0051b",
      "sha1": "49c026171effbe0db4ac053aae68a64b929e1b35",
      "sha256": "c27095cc6d249817a470cff1404136d4aba21afa7d5897e4317f3609adb67852"
    },
    "dob": "1994-04-25 16:45:38",
    "registered": "2005-04-01 10:27:21",
    "phone": "07-3131-1991",
    "cell": "0450-238-220",
    "id": {
      "name": "TFN",
      "value": "234813411"
    },
    "picture": {
      "large": "https://randomuser.me/api/portraits/women/78.jpg",
      "medium": "https://randomuser.me/api/portraits/med/women/78.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/women/78.jpg"
    },
    "nat": "AU"
  },
  {
    "gender": "female",
    "name": {
      "title": "miss",
      "first": "nicole",
      "last": "bryant"
    },
    "location": {
      "street": "3698 dame street",
      "city": "greystones",
      "state": "louth",
      "postcode": 93976
    },
    "email": "nicole.bryant@example.com",
    "login": {
      "username": "greenrabbit563",
      "password": "stuart",
      "salt": "DCCFIHuw",
      "md5": "866e96225ef7b4cc25977ab2f3298e15",
      "sha1": "a08a302c100c65d79a619a038206d33122cac7c1",
      "sha256": "ef846b0ecec73b2fc88d33e30c74de4c61eb9ce4e283649fce2eff6b8bf61089"
    },
    "dob": "1988-10-17 15:18:57",
    "registered": "2004-02-08 07:10:12",
    "phone": "021-355-3167",
    "cell": "081-951-8915",
    "id": {
      "name": "PPS",
      "value": "4144352T"
    },
    "picture": {
      "large": "https://randomuser.me/api/portraits/women/51.jpg",
      "medium": "https://randomuser.me/api/portraits/med/women/51.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/women/51.jpg"
    },
    "nat": "IE"
  },
  {
    "gender": "female",
    "name": {
      "title": "madame",
      "first": "anaëlle",
      "last": "lemoine"
    },
    "location": {
      "street": "9876 rue des cuirassiers",
      "city": "sullens",
      "state": "fribourg",
      "postcode": 8369
    },
    "email": "anaëlle.lemoine@example.com",
    "login": {
      "username": "silverdog459",
      "password": "spongebo",
      "salt": "OHiOs84u",
      "md5": "c58ae74a1aeda74ad9f3bdb44bdfca4c",
      "sha1": "0555bf0ab623146eacba3bf427b8d82da4901f32",
      "sha256": "847c791231b1c487759f1213dbe417de5951dd2ac58f4d773328d4eb2809eac6"
    },
    "dob": "1968-04-25 17:19:00",
    "registered": "2006-07-02 11:15:57",
    "phone": "(474)-829-1093",
    "cell": "(165)-417-7297",
    "id": {
      "name": "AVS",
      "value": "756.BWCB.YGRF.66"
    },
    "picture": {
      "large": "https://randomuser.me/api/portraits/women/64.jpg",
      "medium": "https://randomuser.me/api/portraits/med/women/64.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/women/64.jpg"
    },
    "nat": "CH"
  },
  {
    "gender": "male",
    "name": {
      "title": "monsieur",
      "first": "luis",
      "last": "robin"
    },
    "location": {
      "street": "4715 rue abel-hovelacque",
      "city": "cully",
      "state": "vaud",
      "postcode": 5884
    },
    "email": "luis.robin@example.com",
    "login": {
      "username": "redlion383",
      "password": "cynthia",
      "salt": "OK3vnC81",
      "md5": "a0e3b99ade90dbc6180f0b38bc47fc8e",
      "sha1": "25c63f344e61a2022f1eda0bd52ad85f1b3e3411",
      "sha256": "7e27f7eaaefe3d6c17da8a5f0596eef8b5062450e3b42dbb53de9a4e6f7c1a03"
    },
    "dob": "1971-03-06 13:18:58",
    "registered": "2011-12-24 06:24:00",
    "phone": "(764)-855-6625",
    "cell": "(642)-376-3246",
    "id": {
      "name": "AVS",
      "value": "756.BRRB.ZFRS.79"
    },
    "picture": {
      "large": "https://randomuser.me/api/portraits/men/70.jpg",
      "medium": "https://randomuser.me/api/portraits/med/men/70.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/men/70.jpg"
    },
    "nat": "CH"
  },
  {
    "gender": "female",
    "name": {
      "title": "miss",
      "first": "emilia",
      "last": "iglesias"
    },
    "location": {
      "street": "3041 calle de segovia",
      "city": "pamplona",
      "state": "comunidad valenciana",
      "postcode": 93299
    },
    "email": "emilia.iglesias@example.com",
    "login": {
      "username": "smalltiger997",
      "password": "waters",
      "salt": "UEg9QrCc",
      "md5": "bbb5ddbdf06eb5daeae591fffdb99649",
      "sha1": "4eba76c89de20e446b5cb2ce2604698e1f9503da",
      "sha256": "b2fc3b0a317e76b07db129a43536e8344601d43581e94a2b54654cdc98fd9c3d"
    },
    "dob": "1958-08-30 03:08:37",
    "registered": "2006-06-08 09:46:23",
    "phone": "986-896-902",
    "cell": "626-829-371",
    "id": {
      "name": "DNI",
      "value": "92664499-E"
    },
    "picture": {
      "large": "https://randomuser.me/api/portraits/women/19.jpg",
      "medium": "https://randomuser.me/api/portraits/med/women/19.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/women/19.jpg"
    },
    "nat": "ES"
  },
  {
    "gender": "female",
    "name": {
      "title": "ms",
      "first": "danielle",
      "last": "oliver"
    },
    "location": {
      "street": "8009 poplar dr",
      "city": "hobart",
      "state": "australian capital territory",
      "postcode": 3169
    },
    "email": "danielle.oliver@example.com",
    "login": {
      "username": "greenostrich475",
      "password": "screwyou",
      "salt": "9Ffpa2So",
      "md5": "198b5f56ee13576e3d707f632122d2ac",
      "sha1": "8f002ab67dfb4d8a5479f88bef403f554e73d537",
      "sha256": "224ded287fffe096a47bd8ef6080ab6730106bf31e6ccf8fa87f34b4e063c66e"
    },
    "dob": "1950-06-25 06:56:02",
    "registered": "2011-06-19 07:37:58",
    "phone": "04-1245-0812",
    "cell": "0472-574-194",
    "id": {
      "name": "TFN",
      "value": "089149818"
    },
    "picture": {
      "large": "https://randomuser.me/api/portraits/women/43.jpg",
      "medium": "https://randomuser.me/api/portraits/med/women/43.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/women/43.jpg"
    },
    "nat": "AU"
  },
  {
    "gender": "female",
    "name": {
      "title": "mrs",
      "first": "esther",
      "last": "nuñez"
    },
    "location": {
      "street": "7144 calle de ferraz",
      "city": "valladolid",
      "state": "navarra",
      "postcode": 50284
    },
    "email": "esther.nuñez@example.com",
    "login": {
      "username": "smallwolf596",
      "password": "horace",
      "salt": "sywGKiXd",
      "md5": "9a7743c0c7816b71d91441adfc158b37",
      "sha1": "975652a60c6b4c31634a1f9dc4ab3a7a00611882",
      "sha256": "881f27e72e0abef51a2de5f023557284da0354fe5b7c8ad6055f5cd8cf5c6a86"
    },
    "dob": "1985-08-01 07:59:20",
    "registered": "2014-08-27 12:27:32",
    "phone": "961-351-729",
    "cell": "692-589-794",
    "id": {
      "name": "DNI",
      "value": "98137631-Y"
    },
    "picture": {
      "large": "https://randomuser.me/api/portraits/women/21.jpg",
      "medium": "https://randomuser.me/api/portraits/med/women/21.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/women/21.jpg"
    },
    "nat": "ES"
  },
  {
    "gender": "male",
    "name": {
      "title": "mr",
      "first": "نيما",
      "last": "گلشن"
    },
    "location": {
      "street": "6052 استاد نجاتاللهی",
      "city": "خمینیشهر",
      "state": "قزوین",
      "postcode": 74670
    },
    "email": "نيما.گلشن@example.com",
    "login": {
      "username": "goldencat105",
      "password": "lkjhgfds",
      "salt": "8OgTnr1J",
      "md5": "9244d64fb4aa366208753d8a76aeeb0c",
      "sha1": "6dd19e41ad92906ea3dcc0172ddbe7759efb820b",
      "sha256": "f2b966dedce7dfab73fc8d24013120b3cf02ea0573078ae15f8abd23d20da31f"
    },
    "dob": "1962-09-14 14:30:53",
    "registered": "2012-11-09 09:22:22",
    "phone": "091-29453546",
    "cell": "0973-422-9066",
    "id": {
      "name": "",
      "value": null
    },
    "picture": {
      "large": "https://randomuser.me/api/portraits/men/52.jpg",
      "medium": "https://randomuser.me/api/portraits/med/men/52.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/men/52.jpg"
    },
    "nat": "IR"
  },
  {
    "gender": "male",
    "name": {
      "title": "mr",
      "first": "cesar",
      "last": "santiago"
    },
    "location": {
      "street": "1924 calle de la almudena",
      "city": "arrecife",
      "state": "aragón",
      "postcode": 35751
    },
    "email": "cesar.santiago@example.com",
    "login": {
      "username": "silverleopard341",
      "password": "cook",
      "salt": "i7APrgUB",
      "md5": "8da9edde0b35eba9d3971f785ee23eaa",
      "sha1": "b08628a19c737583b26a6612a9a11392be72bd75",
      "sha256": "92e53d48bb65cd8575f9e2b999fe94333caab5190889c44c160c0f20e39a85fd"
    },
    "dob": "1957-10-19 12:26:32",
    "registered": "2006-11-22 19:44:32",
    "phone": "965-577-628",
    "cell": "601-495-706",
    "id": {
      "name": "DNI",
      "value": "43570400-E"
    },
    "picture": {
      "large": "https://randomuser.me/api/portraits/men/68.jpg",
      "medium": "https://randomuser.me/api/portraits/med/men/68.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/men/68.jpg"
    },
    "nat": "ES"
  },
  {
    "gender": "female",
    "name": {
      "title": "miss",
      "first": "gonca",
      "last": "limoncuoğlu"
    },
    "location": {
      "street": "4234 abanoz sk",
      "city": "muğla",
      "state": "bolu",
      "postcode": 71731
    },
    "email": "gonca.limoncuoğlu@example.com",
    "login": {
      "username": "tinydog233",
      "password": "nomore",
      "salt": "6xaXxPyo",
      "md5": "55ce16a15ed4f50d88eb23cba4f99658",
      "sha1": "bd092a0c15f1e8b663aefd5afa1dd78b3b0532ba",
      "sha256": "9ef75c6437b77100d03028a73db5f6fc01141ea259a0b0eb8ec1a077ebaf57f7"
    },
    "dob": "1993-02-14 05:31:35",
    "registered": "2003-07-04 15:54:21",
    "phone": "(967)-600-9921",
    "cell": "(670)-204-9079",
    "id": {
      "name": "",
      "value": null
    },
    "picture": {
      "large": "https://randomuser.me/api/portraits/women/13.jpg",
      "medium": "https://randomuser.me/api/portraits/med/women/13.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/women/13.jpg"
    },
    "nat": "TR"
  },
  {
    "gender": "female",
    "name": {
      "title": "miss",
      "first": "deniz",
      "last": "karadaş"
    },
    "location": {
      "street": "5006 necatibey cd",
      "city": "balıkesir",
      "state": "ağrı",
      "postcode": 65732
    },
    "email": "deniz.karadaş@example.com",
    "login": {
      "username": "whiteelephant657",
      "password": "asd123",
      "salt": "2PCid7JK",
      "md5": "6b709cbe943002f66f69610ca28d20d6",
      "sha1": "30c23a79bf4f07debbe2932e9b308f0d197ba0f7",
      "sha256": "1f290a174163f21a355d679a3d448ae5d715831f17a4d0409c307c05b6dab9f3"
    },
    "dob": "1957-12-09 01:26:18",
    "registered": "2016-07-04 08:22:02",
    "phone": "(857)-818-7210",
    "cell": "(279)-028-1972",
    "id": {
      "name": "",
      "value": null
    },
    "picture": {
      "large": "https://randomuser.me/api/portraits/women/32.jpg",
      "medium": "https://randomuser.me/api/portraits/med/women/32.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/women/32.jpg"
    },
    "nat": "TR"
  },
  {
    "gender": "male",
    "name": {
      "title": "mr",
      "first": "joshua",
      "last": "wilhelm"
    },
    "location": {
      "street": "4084 wiesenstraße",
      "city": "neuwied",
      "state": "baden-württemberg",
      "postcode": 37981
    },
    "email": "joshua.wilhelm@example.com",
    "login": {
      "username": "tinymouse317",
      "password": "xiang",
      "salt": "6WmcdPEN",
      "md5": "3c789ccfd81a3e75f1d5362f3eaafee6",
      "sha1": "1892e95ce2026bf56f0343e02dcd4cdd35a1bfd0",
      "sha256": "73f436ffecce3a6d886c92c6500670363ee20cd9307282ee78d1b12104c23bf9"
    },
    "dob": "1974-12-20 08:36:37",
    "registered": "2009-07-19 05:02:43",
    "phone": "0497-8767678",
    "cell": "0173-9317550",
    "id": {
      "name": "",
      "value": null
    },
    "picture": {
      "large": "https://randomuser.me/api/portraits/men/3.jpg",
      "medium": "https://randomuser.me/api/portraits/med/men/3.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/men/3.jpg"
    },
    "nat": "DE"
  },
  {
    "gender": "female",
    "name": {
      "title": "ms",
      "first": "alicia",
      "last": "morgan"
    },
    "location": {
      "street": "2967 thornridge cir",
      "city": "wagga wagga",
      "state": "australian capital territory",
      "postcode": 3694
    },
    "email": "alicia.morgan@example.com",
    "login": {
      "username": "greenostrich135",
      "password": "because",
      "salt": "qavOImkP",
      "md5": "e17ccb4db8cf508780f6fd7945bea8d7",
      "sha1": "149a51207d0d8b08dda0d1f8a2ac27b83d5be1e5",
      "sha256": "413fb82621aedc65589fe3612b674a99e69283023ba6676eccaed1c108962c08"
    },
    "dob": "1984-02-07 00:06:53",
    "registered": "2015-05-02 06:42:22",
    "phone": "05-5519-7789",
    "cell": "0415-299-139",
    "id": {
      "name": "TFN",
      "value": "794281170"
    },
    "picture": {
      "large": "https://randomuser.me/api/portraits/women/37.jpg",
      "medium": "https://randomuser.me/api/portraits/med/women/37.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/women/37.jpg"
    },
    "nat": "AU"
  },
  {
    "gender": "female",
    "name": {
      "title": "miss",
      "first": "ayşe",
      "last": "tahincioğlu"
    },
    "location": {
      "street": "3080 şehitler cd",
      "city": "ardahan",
      "state": "adana",
      "postcode": 68916
    },
    "email": "ayşe.tahincioğlu@example.com",
    "login": {
      "username": "whiteelephant745",
      "password": "pizza",
      "salt": "jWlQLLkT",
      "md5": "dffb33eedf2983858324b24f2e28e020",
      "sha1": "7088be27685a37cde08fba6997bc857b0229ad50",
      "sha256": "280dd99e1533875ec81c4766ff5628f34bf7ec60a514002369e5a00cc125e758"
    },
    "dob": "1961-01-23 23:07:04",
    "registered": "2003-08-24 04:11:19",
    "phone": "(155)-493-7347",
    "cell": "(442)-165-7006",
    "id": {
      "name": "",
      "value": null
    },
    "picture": {
      "large": "https://randomuser.me/api/portraits/women/91.jpg",
      "medium": "https://randomuser.me/api/portraits/med/women/91.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/women/91.jpg"
    },
    "nat": "TR"
  },
  {
    "gender": "female",
    "name": {
      "title": "miss",
      "first": "lily",
      "last": "roux"
    },
    "location": {
      "street": "9378 montée saint-barthélémy",
      "city": "courbevoie",
      "state": "cantal",
      "postcode": 60945
    },
    "email": "lily.roux@example.com",
    "login": {
      "username": "tinygorilla360",
      "password": "pinkfloy",
      "salt": "4r5t9LaJ",
      "md5": "d27903a8e56d514a6b3f5aed69f65560",
      "sha1": "35f59b35ebb9492fbd6a09ebb6ebbbd42439b4c3",
      "sha256": "e7ce99e8e3b319677cc41d583b32108dcf9624c8db196b634d6d5e8f5ff0315d"
    },
    "dob": "1960-10-22 17:42:38",
    "registered": "2010-06-18 08:10:15",
    "phone": "02-27-22-19-10",
    "cell": "06-26-09-34-63",
    "id": {
      "name": "INSEE",
      "value": "260906295603 23"
    },
    "picture": {
      "large": "https://randomuser.me/api/portraits/women/64.jpg",
      "medium": "https://randomuser.me/api/portraits/med/women/64.jpg",
      "thumbnail": "https://randomuser.me/api/portraits/thumb/women/64.jpg"
    },
    "nat": "FR"
  }
];

export const studyReasonOption = [
{
  "id" : 0,
  "text" : "Choose your Reason"
},
{
  "id" : 1,
  "text" : "I want to go to Japan"
},
{
  "id" : 2,
  "text" : "I want to go to Africa"
},
{
  "id" : 3,
  "text" : "I want to go to Indog"
},
]


export const hiraganaList = [
  //SeiOn
  {
    "id":"h_a",
    "type":"hiragana",      
    "romaji":"a",
    "moji":"あ",
    "audio":"a.mp3",
    "title":"a",
  },
  {
    "id":"h_i",
    "type":"hiragana",      
    "romaji":"i",
    "moji":"い",
    "audio":"i.mp3",
    "title":"i",
  },
  {
    "id":"h_u",
    "type":"hiragana",      
    "romaji":"u",
    "moji":"う",
    "audio":"u.mp3",
    "title":"u",
  },
  {
    "id":"h_e",
    "type":"hiragana",      
    "romaji":"e",
    "moji":"え",
    "audio":"e.mp3",
    "title":"e",
  },
  {
    "id":"h_o",
    "type":"hiragana",      
    "romaji":"o",
    "moji":"お",
    "audio":"o.mp3",
    "title":"o",
  },
  {
    "id":"h_ka",
    "type":"hiragana",      
    "romaji":"ka",
    "moji":"か",
    "audio":"ka.mp3",
    "title":"ka",
  },
  {
    "id":"h_ki",
    "type":"hiragana",      
    "romaji":"ki",
    "moji":"き",
    "audio":"ki.mp3",
    "title":"ki",
  },
  {
    "id":"h_ku",
    "type":"hiragana",      
    "romaji":"ku",
    "moji":"く",
    "audio":"ku.mp3",
    "title":"ku",
  },
  {
    "id":"h_ke",
    "type":"hiragana",      
    "romaji":"ke",
    "moji":"け",
    "audio":"ke.mp3",
    "title":"ke",
  },
  {
    "id":"h_ko",
    "type":"hiragana",      
    "romaji":"ko",
    "moji":"こ",
    "audio":"ko.mp3",
    "title":"ko",
  },
  {
    "id":"h_sa",
    "type":"hiragana",      
    "romaji":"sa",
    "moji":"さ",
    "audio":"sa.mp3",
    "title":"sa",
  },
  {
    "id":"h_shi",
    "type":"hiragana",      
    "romaji":"shi",
    "moji":"し",
    "audio":"shi.mp3",
    "title":"shi",
  },
  {
    "id":"h_su",
    "type":"hiragana",      
    "romaji":"su",
    "moji":"す",
    "audio":"su.mp3",
    "title":"su",
  },
  {
    "id":"h_se",
    "type":"hiragana",      
    "romaji":"se",
    "moji":"せ",
    "audio":"se.mp3",
    "title":"se",
  },
  {
    "id":"h_so",
    "type":"hiragana",      
    "romaji":"so",
    "moji":"そ",
    "audio":"so.mp3",
    "title":"so",
  },
  {
    "id":"h_ta",
    "type":"hiragana",      
    "romaji":"ta",
    "moji":"た",
    "audio":"ta.mp3",
    "title":"ta",
  },
  {
    "id":"h_chi",
    "type":"hiragana",      
    "romaji":"chi",
    "moji":"ち",
    "audio":"chi.mp3",
    "title":"chi",
  },
  {
    "id":"h_tsu",
    "type":"hiragana",      
    "romaji":"tsu",
    "moji":"つ",
    "audio":"tsu.mp3",
    "title":"tsu",
  },
  {
    "id":"h_te",
    "type":"hiragana",      
    "romaji":"te",
    "moji":"て",
    "audio":"te.mp3",
    "title":"te",
  },
  {
    "id":"h_to",
    "type":"hiragana",      
    "romaji":"to",
    "moji":"と",
    "audio":"to.mp3",
    "title":"to",
  },
  {
    "id":"h_na",
    "type":"hiragana",      
    "romaji":"na",
    "moji":"な",
    "audio":"na.mp3",
    "title":"na",
  },
  {
    "id":"h_ni",
    "type":"hiragana",      
    "romaji":"ni",
    "moji":"に",
    "audio":"ni.mp3",
    "title":"ni",
  },
  {
    "id":"h_nu",
    "type":"hiragana",      
    "romaji":"nu",
    "moji":"ぬ",
    "audio":"nu.mp3",
    "title":"nu",
  },
  {
    "id":"h_ne",
    "type":"hiragana",      
    "romaji":"ne",
    "moji":"ね",
    "audio":"ne.mp3",
    "title":"ne",
  },
  {
    "id":"h_no",
    "type":"hiragana",      
    "romaji":"no",
    "moji":"の",
    "audio":"no.mp3",
    "title":"no",
  },
  {
    "id":"h_ha",
    "type":"hiragana",      
    "romaji":"ha",
    "moji":"は",
    "audio":"ha.mp3",
    "title":"ha",
  },
  {
    "id":"h_hi",
    "type":"hiragana",      
    "romaji":"hi",
    "moji":"ひ",
    "audio":"hi.mp3",
    "title":"hi",
  },
  {
    "id":"h_fu",
    "type":"hiragana",      
    "romaji":"fu",
    "moji":"ふ",
    "audio":"fu.mp3",
    "title":"fu",
  },
  {
    "id":"h_he",
    "type":"hiragana",      
    "romaji":"he",
    "moji":"へ",
    "audio":"he.mp3",
    "title":"he",
  },
  {
    "id":"h_ho",
    "type":"hiragana",      
    "romaji":"ho",
    "moji":"ほ",
    "audio":"ho.mp3",
    "title":"ho",
  },
  {
    "id":"h_ma",
    "type":"hiragana",      
    "romaji":"ma",
    "moji":"ま",
    "audio":"ma.mp3",
    "title":"ma",
  },
  {
    "id":"h_mi",
    "type":"hiragana",      
    "romaji":"mi",
    "moji":"み",
    "audio":"mi.mp3",
    "title":"mi",
  },
  {
    "id":"h_mu",
    "type":"hiragana",      
    "romaji":"mu",
    "moji":"む",
    "audio":"mu.mp3",
    "title":"mu",
  },
  {
    "id":"h_me",
    "type":"hiragana",      
    "romaji":"me",
    "moji":"め",
    "audio":"me.mp3",
    "title":"me",
  },
  {
    "id":"h_mo",
    "type":"hiragana",      
    "romaji":"mo",
    "moji":"も",
    "audio":"mo.mp3",
    "title":"mo",
  },
  {
    "id":"h_ya",
    "type":"hiragana",      
    "romaji":"ya",
    "moji":"や",
    "audio":"ya.mp3",
    "title":"ya",
  },
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_yu",
    "type":"hiragana",      
    "romaji":"yu",
    "moji":"ゆ",
    "audio":"yu.mp3",
    "title":"yu",
  },
   {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_yo",
    "type":"hiragana",      
    "romaji":"yo",
    "moji":"よ",
    "audio":"yo.mp3",
    "title":"yo",
  },
  {
    "id":"h_ra",
    "type":"hiragana",      
    "romaji":"ra",
    "moji":"ら",
    "audio":"ra.mp3",
    "title":"ra",
  },
  {
    "id":"h_ri",
    "type":"hiragana",      
    "romaji":"ri",
    "moji":"り",
    "audio":"ri.mp3",
    "title":"ri",
  },
  {
    "id":"h_ru",
    "type":"hiragana",      
    "romaji":"ru",
    "moji":"る",
    "audio":"ru.mp3",
    "title":"ru",
  },
  {
    "id":"h_re",
    "type":"hiragana",      
    "romaji":"re",
    "moji":"れ",
    "audio":"re.mp3",
    "title":"re",
  },
  {
    "id":"h_ro",
    "type":"hiragana",      
    "romaji":"ro",
    "moji":"ろ",
    "audio":"ro.mp3",
    "title":"ro",
  },
  {
    "id":"h_wa",
    "type":"hiragana",      
    "romaji":"wa",
    "moji":"わ",
    "audio":"wa.mp3",
    "title":"wa",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_wo",
    "type":"hiragana",      
    "romaji":"o(wo)",
    "moji":"を",
    "audio":"wo.mp3",
    "title":"wo",
  },
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_n",
    "type":"hiragana",      
    "romaji":"n",
    "moji":"ん",
    "audio":"n.mp3",
    "title":"n",
  },
  //DakuOn
  {
    "id":"h_ga",
    "type":"hiragana",      
    "romaji":"ga",
    "moji":"が",
    "audio":"ga.mp3",
    "title":"ga",
  },
  {
    "id":"h_gi",
    "type":"hiragana",      
    "romaji":"gi",
    "moji":"ぎ",
    "audio":"gi.mp3",
    "title":"gi",
  },
  {
    "id":"h_gu",
    "type":"hiragana",      
    "romaji":"gu",
    "moji":"ぐ",
    "audio":"gu.mp3",
    "title":"gu",
  },
  {
    "id":"h_ge",
    "type":"hiragana",      
    "romaji":"ge",
    "moji":"げ",
    "audio":"ge.mp3",
    "title":"ge",
  },
  {
    "id":"h_go",
    "type":"hiragana",      
    "romaji":"go",
    "moji":"ご",
    "audio":"go.mp3",
    "title":"go",
  },
  {
    "id":"h_za",
    "type":"hiragana",      
    "romaji":"za",
    "moji":"ざ",
    "audio":"za.mp3",
    "title":"za",
  },
  {
    "id":"h_ji",
    "type":"hiragana",      
    "romaji":"ji(zi)",
    "moji":"じ",
    "audio":"ji.mp3",
    "title":"ji(zi)",
  },
  {
    "id":"h_zu",
    "type":"hiragana",      
    "romaji":"zu",
    "moji":"ず",
    "audio":"zu.mp3",
    "title":"zu",
  },
  {
    "id":"h_ze",
    "type":"hiragana",      
    "romaji":"ze",
    "moji":"ぜ",
    "audio":"ze.mp3",
    "title":"ze",
  },
  {
    "id":"h_zo",
    "type":"hiragana",      
    "romaji":"zo",
    "moji":"ぞ",
    "audio":"zo.mp3",
    "title":"zo",
  },
  {
    "id":"h_da",
    "type":"hiragana",      
    "romaji":"da",
    "moji":"だ",
    "audio":"da.mp3",
    "title":"da",
  },
  {
    "id":"h_di",
    "type":"hiragana",      
    "romaji":"ji(di)",
    "moji":"ぢ",
    "audio":"di.mp3",
    "title":"ji(di)",
  },
  {
    "id":"h_du",
    "type":"hiragana",      
    "romaji":"zu(du)",
    "moji":"づ",
    "audio":"du.mp3",
    "title":"zu(du)",
  },
  {
    "id":"h_de",
    "type":"hiragana",      
    "romaji":"de",
    "moji":"で",
    "audio":"de.mp3",
    "title":"de",
  },
  {
    "id":"h_do",
    "type":"hiragana",      
    "romaji":"do",
    "moji":"ど",
    "audio":"do.mp3",
    "title":"do",
  },
  {
    "id":"h_ba",
    "type":"hiragana",      
    "romaji":"ba",
    "moji":"ば",
    "audio":"ba.mp3",
    "title":"ba",
  },
  {
    "id":"h_bi",
    "type":"hiragana",      
    "romaji":"bi",
    "moji":"び",
    "audio":"bi.mp3",
    "title":"bi",
  },
  {
    "id":"h_bu",
    "type":"hiragana",      
    "romaji":"bu",
    "moji":"ぶ",
    "audio":"bu.mp3",
    "title":"bu",
  },
  {
    "id":"h_be",
    "type":"hiragana",      
    "romaji":"be",
    "moji":"べ",
    "audio":"be.mp3",
    "title":"be",
  },
  {
    "id":"h_bo",
    "type":"hiragana",      
    "romaji":"bo",
    "moji":"ぼ",
    "audio":"bo.mp3",
    "title":"bo",
  },
  {
    "id":"h_pa",
    "type":"hiragana",      
    "romaji":"pa",
    "moji":"ぱ",
    "audio":"pa.mp3",
    "title":"pa",
  },
  {
    "id":"h_pi",
    "type":"hiragana",      
    "romaji":"pi",
    "moji":"ぴ",
    "audio":"pi.mp3",
    "title":"pi",
  },
  {
    "id":"h_pu",
    "type":"hiragana",      
    "romaji":"pu",
    "moji":"ぷ",
    "audio":"pu.mp3",
    "title":"pu",
  },
  {
    "id":"h_pe",
    "type":"hiragana",      
    "romaji":"pe",
    "moji":"ぺ",
    "audio":"pe.mp3",
    "title":"pe",
  },
  {
    "id":"h_po",
    "type":"hiragana",      
    "romaji":"po",
    "moji":"ぽ",
    "audio":"po.mp3",
    "title":"po",
  },
  //YoOn
  {
    "id":"h_kya",
    "type":"hiragana",      
    "romaji":"kya",
    "moji":"きゃ",
    "audio":"kya.mp3",
    "title":"kya",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_kyu",
    "type":"hiragana",      
    "romaji":"kyu",
    "moji":"きゅ",
    "audio":"kyu.mp3",
    "title":"kyu",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_kyo",
    "type":"hiragana",      
    "romaji":"kyo",
    "moji":"きょ",
    "audio":"kyo.mp3",
    "title":"kyo",
  },
  {
    "id":"h_sha",
    "type":"hiragana",      
    "romaji":"sha",
    "moji":"しゃ",
    "audio":"sha.mp3",
    "title":"sha",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_shu",
    "type":"hiragana",      
    "romaji":"shu",
    "moji":"しゅ",
    "audio":"shu.mp3",
    "title":"shu",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_sho",
    "type":"hiragana",      
    "romaji":"sho",
    "moji":"しょ",
    "audio":"sho.mp3",
    "title":"sho",
  },
  {
    "id":"h_cha",
    "type":"hiragana",      
    "romaji":"cha",
    "moji":"ちゃ",
    "audio":"cha.mp3",
    "title":"cha",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_chu",
    "type":"hiragana",      
    "romaji":"chu",
    "moji":"ちゅ",
    "audio":"chu.mp3",
    "title":"chu",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_cho",
    "type":"hiragana",      
    "romaji":"cho",
    "moji":"ちょ",
    "audio":"cho.mp3",
    "title":"cho",
  },
  {
    "id":"h_nya",
    "type":"hiragana",      
    "romaji":"nya",
    "moji":"にゃ",
    "audio":"nya.mp3",
    "title":"nya",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_nyu",
    "type":"hiragana",      
    "romaji":"nyu",
    "moji":"にゅ",
    "audio":"nyu.mp3",
    "title":"nyu",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_nyo",
    "type":"hiragana",      
    "romaji":"nyo",
    "moji":"にょ",
    "audio":"nyo.mp3",
    "title":"nyo",
  },
  {
    "id":"h_hya",
    "type":"hiragana",      
    "romaji":"hya",
    "moji":"ひゃ",
    "audio":"hya.mp3",
    "title":"hya",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_hyu",
    "type":"hiragana",      
    "romaji":"hyu",
    "moji":"ひゅ",
    "audio":"hyu.mp3",
    "title":"hyu",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_hyo",
    "type":"hiragana",      
    "romaji":"hyo",
    "moji":"ひょ",
    "audio":"hyo.mp3",
    "title":"hyo",
  },
  {
    "id":"h_mya",
    "type":"hiragana",      
    "romaji":"mya",
    "moji":"みゃ",
    "audio":"mya.mp3",
    "title":"mya",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_myu",
    "type":"hiragana",      
    "romaji":"myu",
    "moji":"みゅ",
    "audio":"myu.mp3",
    "title":"myu",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_myo",
    "type":"hiragana",      
    "romaji":"myo",
    "moji":"みょ",
    "audio":"myo.mp3",
    "title":"myo",
  },
  {
    "id":"h_rya",
    "type":"hiragana",      
    "romaji":"rya",
    "moji":"りゃ",
    "audio":"rya.mp3",
    "title":"rya",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_ryu",
    "type":"hiragana",      
    "romaji":"ryu",
    "moji":"りゅ",
    "audio":"ryu.mp3",
    "title":"ryu",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_ryo",
    "type":"hiragana",      
    "romaji":"ryo",
    "moji":"りょ",
    "audio":"ryo.mp3",
    "title":"ryo",
  },
  {
    "id":"h_gya",
    "type":"hiragana",      
    "romaji":"gya",
    "moji":"ぎゃ",
    "audio":"gya.mp3",
    "title":"gya",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_gyu",
    "type":"hiragana",      
    "romaji":"gyu",
    "moji":"ぎゅ",
    "audio":"gyu.mp3",
    "title":"gyu",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_gyo",
    "type":"hiragana",      
    "romaji":"gyo",
    "moji":"ぎょ",
    "audio":"gyo.mp3",
    "title":"gyo",
  },
  {
    "id":"h_ja",
    "type":"hiragana",      
    "romaji":"ja",
    "moji":"じゃ",
    "audio":"ja.mp3",
    "title":"ja",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_ju",
    "type":"hiragana",      
    "romaji":"ju",
    "moji":"じゅ",
    "audio":"ju.mp3",
    "title":"ju",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_jo",
    "type":"hiragana",      
    "romaji":"jo",
    "moji":"じょ",
    "audio":"jo.mp3",
    "title":"jo",
  },
  {
    "id":"h_bya",
    "type":"hiragana",      
    "romaji":"bya",
    "moji":"びゃ",
    "audio":"bya.mp3",
    "title":"bya",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_byu",
    "type":"hiragana",      
    "romaji":"byu",
    "moji":"びゅ",
    "audio":"byu.mp3",
    "title":"byu",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_byo",
    "type":"hiragana",      
    "romaji":"byo",
    "moji":"びょ",
    "audio":"byo.mp3",
    "title":"byo",
  },
  {
    "id":"h_pya",
    "type":"hiragana",      
    "romaji":"pya",
    "moji":"ぴゃ",
    "audio":"pya.mp3",
    "title":"pya",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_pyu",
    "type":"hiragana",      
    "romaji":"pyu",
    "moji":"ぴゅ",
    "audio":"pyu.mp3",
    "title":"pyu",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"h_pyo",
    "type":"hiragana",      
    "romaji":"pyo",
    "moji":"ぴょ",
    "audio":"pyo.mp3",
    "title":"pyo",
  }
]


export const katakanaList = [
  //SeiOn
  {
    "id":"k_a",
    "type":"katakana",      
    "romaji":"a",
    "moji":"ア",
    "audio":"a.mp3",
    "title":"a",
  },
  {
    "id":"k_i",
    "type":"katakana",      
    "romaji":"i",
    "moji":"イ",
    "audio":"i.mp3",
    "title":"i",
  },
  {
    "id":"k_u",
    "type":"katakana",      
    "romaji":"u",
    "moji":"ウ",
    "audio":"u.mp3",
    "title":"u",
  },
  {
    "id":"k_e",
    "type":"katakana",      
    "romaji":"e",
    "moji":"エ",
    "audio":"e.mp3",
    "title":"e",
  },
  {
    "id":"k_o",
    "type":"katakana",      
    "romaji":"o",
    "moji":"オ",
    "audio":"o.mp3",
    "title":"o",
  },
  {
    "id":"k_ka",
    "type":"katakana",      
    "romaji":"ka",
    "moji":"カ",
    "audio":"ka.mp3",
    "title":"ka",
  },
  {
    "id":"k_ki",
    "type":"katakana",      
    "romaji":"ki",
    "moji":"キ",
    "audio":"ki.mp3",
    "title":"ki",
  },
  {
    "id":"k_ku",
    "type":"katakana",      
    "romaji":"ku",
    "moji":"ク",
    "audio":"ku.mp3",
    "title":"ku",
  },
  {
    "id":"k_ke",
    "type":"katakana",      
    "romaji":"ke",
    "moji":"ケ",
    "audio":"ke.mp3",
    "title":"ke",
  },
  {
    "id":"k_ko",
    "type":"katakana",      
    "romaji":"ko",
    "moji":"コ",
    "audio":"ko.mp3",
    "title":"ko",
  },
  {
    "id":"k_sa",
    "type":"katakana",      
    "romaji":"sa",
    "moji":"サ",
    "audio":"sa.mp3",
    "title":"sa",
  },
  {
    "id":"k_shi",
    "type":"katakana",      
    "romaji":"shi",
    "moji":"シ",
    "audio":"shi.mp3",
    "title":"shi",
  },
  {
    "id":"k_su",
    "type":"katakana",      
    "romaji":"su",
    "moji":"ス",
    "audio":"su.mp3",
    "title":"su",
  },
  {
    "id":"k_se",
    "type":"katakana",      
    "romaji":"se",
    "moji":"セ",
    "audio":"se.mp3",
    "title":"se",
  },
  {
    "id":"k_so",
    "type":"katakana",      
    "romaji":"so",
    "moji":"ソ",
    "audio":"so.mp3",
    "title":"so",
  },
  {
    "id":"k_ta",
    "type":"katakana",      
    "romaji":"ta",
    "moji":"タ",
    "audio":"ta.mp3",
    "title":"ta",
  },
  {
    "id":"k_chi",
    "type":"katakana",      
    "romaji":"chi",
    "moji":"チ",
    "audio":"chi.mp3",
    "title":"chi",
  },
  {
    "id":"k_tsu",
    "type":"katakana",      
    "romaji":"tsu",
    "moji":"ツ",
    "audio":"tsu.mp3",
    "title":"tsu",
  },
  {
    "id":"k_te",
    "type":"katakana",      
    "romaji":"te",
    "moji":"テ",
    "audio":"te.mp3",
    "title":"te",
  },
  {
    "id":"k_to",
    "type":"katakana",      
    "romaji":"to",
    "moji":"ト",
    "audio":"to.mp3",
    "title":"to",
  },
  {
    "id":"k_na",
    "type":"katakana",      
    "romaji":"na",
    "moji":"ナ",
    "audio":"na.mp3",
    "title":"na",
  },
  {
    "id":"k_ni",
    "type":"katakana",      
    "romaji":"ni",
    "moji":"ニ",
    "audio":"ni.mp3",
    "title":"ni",
  },
  {
    "id":"k_nu",
    "type":"katakana",      
    "romaji":"nu",
    "moji":"ヌ",
    "audio":"nu.mp3",
    "title":"nu",
  },
  {
    "id":"k_ne",
    "type":"katakana",      
    "romaji":"ne",
    "moji":"ネ",
    "audio":"ne.mp3",
    "title":"ne",
  },
  {
    "id":"k_no",
    "type":"katakana",      
    "romaji":"no",
    "moji":"ノ",
    "audio":"no.mp3",
    "title":"no",
  },
  {
    "id":"k_ha",
    "type":"katakana",      
    "romaji":"ha",
    "moji":"ハ",
    "audio":"ha.mp3",
    "title":"ha",
  },
  {
    "id":"k_hi",
    "type":"katakana",      
    "romaji":"hi",
    "moji":"ヒ",
    "audio":"hi.mp3",
    "title":"hi",
  },
  {
    "id":"k_fu",
    "type":"katakana",      
    "romaji":"fu",
    "moji":"フ",
    "audio":"fu.mp3",
    "title":"fu",
  },
  {
    "id":"k_he",
    "type":"katakana",      
    "romaji":"he",
    "moji":"ヘ",
    "audio":"he.mp3",
    "title":"he",
  },
  {
    "id":"k_ho",
    "type":"katakana",      
    "romaji":"ho",
    "moji":"ホ",
    "audio":"ho.mp3",
    "title":"ho",
  },
  {
    "id":"k_ma",
    "type":"katakana",      
    "romaji":"ma",
    "moji":"マ",
    "audio":"ma.mp3",
    "title":"ma",
  },
  {
    "id":"k_mi",
    "type":"katakana",      
    "romaji":"mi",
    "moji":"ミ",
    "audio":"mi.mp3",
    "title":"mi",
  },
  {
    "id":"k_mu",
    "type":"katakana",      
    "romaji":"mu",
    "moji":"ム",
    "audio":"mu.mp3",
    "title":"mu",
  },
  {
    "id":"k_me",
    "type":"katakana",      
    "romaji":"me",
    "moji":"メ",
    "audio":"me.mp3",
    "title":"me",
  },
  {
    "id":"k_mo",
    "type":"katakana",      
    "romaji":"mo",
    "moji":"モ",
    "audio":"mo.mp3",
    "title":"mo",
  },
  {
    "id":"k_ya",
    "type":"katakana",      
    "romaji":"ya",
    "moji":"ヤ",
    "audio":"ya.mp3",
    "title":"ya",
  },
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_yu",
    "type":"katakana",      
    "romaji":"yu",
    "moji":"ユ",
    "audio":"yu.mp3",
    "title":"yu",
  },
   {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_yo",
    "type":"katakana",      
    "romaji":"yo",
    "moji":"ヨ",
    "audio":"yo.mp3",
    "title":"yo",
  },
  {
    "id":"k_ra",
    "type":"katakana",      
    "romaji":"ra",
    "moji":"ラ",
    "audio":"ra.mp3",
    "title":"ra",
  },
  {
    "id":"k_ri",
    "type":"katakana",      
    "romaji":"ri",
    "moji":"リ",
    "audio":"ri.mp3",
    "title":"ri",
  },
  {
    "id":"k_ru",
    "type":"katakana",      
    "romaji":"ru",
    "moji":"ル",
    "audio":"ru.mp3",
    "title":"ru",
  },
  {
    "id":"k_re",
    "type":"katakana",      
    "romaji":"re",
    "moji":"レ",
    "audio":"re.mp3",
    "title":"re",
  },
  {
    "id":"k_ro",
    "type":"katakana",      
    "romaji":"ro",
    "moji":"ロ",
    "audio":"ro.mp3",
    "title":"ro",
  },
  {
    "id":"k_wa",
    "type":"katakana",      
    "romaji":"wa",
    "moji":"ワ",
    "audio":"wa.mp3",
    "title":"wa",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_wo",
    "type":"katakana",      
    "romaji":"o(wo)",
    "moji":"ヲ",
    "audio":"wo.mp3",
    "title":"wo",
  },
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_n",
    "type":"katakana",      
    "romaji":"n",
    "moji":"ン",
    "audio":"n.mp3",
    "title":"n",
  },
  //DakuOn
  {
    "id":"k_ga",
    "type":"katakana",      
    "romaji":"ga",
    "moji":"ガ",
    "audio":"ga.mp3",
    "title":"ga",
  },
  {
    "id":"k_gi",
    "type":"katakana",      
    "romaji":"gi",
    "moji":"ギ",
    "audio":"gi.mp3",
    "title":"gi",
  },
  {
    "id":"k_gu",
    "type":"katakana",      
    "romaji":"gu",
    "moji":"グ",
    "audio":"gu.mp3",
    "title":"gu",
  },
  {
    "id":"k_ge",
    "type":"katakana",      
    "romaji":"ge",
    "moji":"ゲ",
    "audio":"ge.mp3",
    "title":"ge",
  },
  {
    "id":"k_go",
    "type":"katakana",      
    "romaji":"go",
    "moji":"ゴ",
    "audio":"go.mp3",
    "title":"go",
  },
  {
    "id":"k_za",
    "type":"katakana",      
    "romaji":"za",
    "moji":"ザ",
    "audio":"za.mp3",
    "title":"za",
  },
  {
    "id":"k_ji",
    "type":"katakana",      
    "romaji":"ji(zi)",
    "moji":"ジ",
    "audio":"ji.mp3",
    "title":"ji(zi)",
  },
  {
    "id":"k_zu",
    "type":"katakana",      
    "romaji":"zu",
    "moji":"ズ",
    "audio":"zu.mp3",
    "title":"zu",
  },
  {
    "id":"k_ze",
    "type":"katakana",      
    "romaji":"ze",
    "moji":"ゼ",
    "audio":"ze.mp3",
    "title":"ze",
  },
  {
    "id":"k_zo",
    "type":"katakana",      
    "romaji":"zo",
    "moji":"ゾ",
    "audio":"zo.mp3",
    "title":"zo",
  },
  {
    "id":"k_da",
    "type":"katakana",      
    "romaji":"da",
    "moji":"ダ",
    "audio":"da.mp3",
    "title":"da",
  },
  {
    "id":"k_di",
    "type":"katakana",      
    "romaji":"ji(di)",
    "moji":"ヂ",
    "audio":"di.mp3",
    "title":"ji(di)",
  },
  {
    "id":"k_du",
    "type":"katakana",      
    "romaji":"zu(du)",
    "moji":"ヅ",
    "audio":"du.mp3",
    "title":"zu(du)",
  },
  {
    "id":"k_de",
    "type":"katakana",      
    "romaji":"de",
    "moji":"デ",
    "audio":"de.mp3",
    "title":"de",
  },
  {
    "id":"k_do",
    "type":"katakana",      
    "romaji":"do",
    "moji":"ド",
    "audio":"do.mp3",
    "title":"do",
  },
  {
    "id":"k_ba",
    "type":"katakana",      
    "romaji":"ba",
    "moji":"バ",
    "audio":"ba.mp3",
    "title":"ba",
  },
  {
    "id":"k_bi",
    "type":"katakana",      
    "romaji":"bi",
    "moji":"ビ",
    "audio":"bi.mp3",
    "title":"bi",
  },
  {
    "id":"k_bu",
    "type":"katakana",      
    "romaji":"bu",
    "moji":"ブ",
    "audio":"bu.mp3",
    "title":"bu",
  },
  {
    "id":"k_be",
    "type":"katakana",      
    "romaji":"be",
    "moji":"ベ",
    "audio":"be.mp3",
    "title":"be",
  },
  {
    "id":"k_bo",
    "type":"katakana",      
    "romaji":"bo",
    "moji":"ボ",
    "audio":"bo.mp3",
    "title":"bo",
  },
  {
    "id":"k_pa",
    "type":"katakana",      
    "romaji":"pa",
    "moji":"パ",
    "audio":"pa.mp3",
    "title":"pa",
  },
  {
    "id":"k_pi",
    "type":"katakana",      
    "romaji":"pi",
    "moji":"ピ",
    "audio":"pi.mp3",
    "title":"pi",
  },
  {
    "id":"k_pu",
    "type":"katakana",      
    "romaji":"pu",
    "moji":"プ",
    "audio":"pu.mp3",
    "title":"pu",
  },
  {
    "id":"k_pe",
    "type":"katakana",      
    "romaji":"pe",
    "moji":"ペ",
    "audio":"pe.mp3",
    "title":"pe",
  },
  {
    "id":"k_po",
    "type":"katakana",      
    "romaji":"po",
    "moji":"ポ",
    "audio":"po.mp3",
    "title":"po",
  },
  //YoOn
  {
    "id":"k_kya",
    "type":"katakana",      
    "romaji":"kya",
    "moji":"キャ",
    "audio":"kya.mp3",
    "title":"kya",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_kyu",
    "type":"katakana",      
    "romaji":"kyu",
    "moji":"キュ",
    "audio":"kyu.mp3",
    "title":"kyu",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_kyo",
    "type":"katakana",      
    "romaji":"kyo",
    "moji":"キョ",
    "audio":"kyo.mp3",
    "title":"kyo",
  },
  {
    "id":"k_sha",
    "type":"katakana",      
    "romaji":"sha",
    "moji":"シャ",
    "audio":"sha.mp3",
    "title":"sha",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_shu",
    "type":"katakana",      
    "romaji":"shu",
    "moji":"シュ",
    "audio":"shu.mp3",
    "title":"shu",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_sho",
    "type":"katakana",      
    "romaji":"sho",
    "moji":"ショ",
    "audio":"sho.mp3",
    "title":"sho",
  },
  {
    "id":"k_cha",
    "type":"katakana",      
    "romaji":"cha",
    "moji":"チャ",
    "audio":"cha.mp3",
    "title":"cha",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_chu",
    "type":"katakana",      
    "romaji":"chu",
    "moji":"チュ",
    "audio":"chu.mp3",
    "title":"chu",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_cho",
    "type":"katakana",      
    "romaji":"cho",
    "moji":"チョ",
    "audio":"cho.mp3",
    "title":"cho",
  },
  {
    "id":"k_nya",
    "type":"katakana",      
    "romaji":"nya",
    "moji":"ニャ",
    "audio":"nya.mp3",
    "title":"nya",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_nyu",
    "type":"katakana",      
    "romaji":"nyu",
    "moji":"ニュ",
    "audio":"nyu.mp3",
    "title":"nyu",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_nyo",
    "type":"katakana",      
    "romaji":"nyo",
    "moji":"ニョ",
    "audio":"nyo.mp3",
    "title":"nyo",
  },
  {
    "id":"k_hya",
    "type":"katakana",      
    "romaji":"hya",
    "moji":"ヒャ",
    "audio":"hya.mp3",
    "title":"hya",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_hyu",
    "type":"katakana",      
    "romaji":"hyu",
    "moji":"ヒュ",
    "audio":"hyu.mp3",
    "title":"hyu",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_hyo",
    "type":"katakana",      
    "romaji":"hyo",
    "moji":"ヒョ",
    "audio":"hyo.mp3",
    "title":"hyo",
  },
  {
    "id":"k_mya",
    "type":"katakana",      
    "romaji":"mya",
    "moji":"ミャ",
    "audio":"mya.mp3",
    "title":"mya",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_myu",
    "type":"katakana",      
    "romaji":"myu",
    "moji":"ミュ",
    "audio":"myu.mp3",
    "title":"myu",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_myo",
    "type":"katakana",      
    "romaji":"myo",
    "moji":"ミョ",
    "audio":"myo.mp3",
    "title":"myo",
  },
  {
    "id":"k_rya",
    "type":"katakana",      
    "romaji":"rya",
    "moji":"リャ",
    "audio":"rya.mp3",
    "title":"rya",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_ryu",
    "type":"katakana",      
    "romaji":"ryu",
    "moji":"リュ",
    "audio":"ryu.mp3",
    "title":"ryu",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_ryo",
    "type":"katakana",      
    "romaji":"ryo",
    "moji":"リョ",
    "audio":"ryo.mp3",
    "title":"ryo",
  },
  {
    "id":"k_gya",
    "type":"katakana",      
    "romaji":"gya",
    "moji":"ギャ",
    "audio":"gya.mp3",
    "title":"gya",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_gyu",
    "type":"katakana",      
    "romaji":"gyu",
    "moji":"ギュ",
    "audio":"gyu.mp3",
    "title":"gyu",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_gyo",
    "type":"katakana",      
    "romaji":"gyo",
    "moji":"ギョ",
    "audio":"gyo.mp3",
    "title":"gyo",
  },
  {
    "id":"k_ja",
    "type":"katakana",      
    "romaji":"ja",
    "moji":"ジャ",
    "audio":"ja.mp3",
    "title":"ja",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_ju",
    "type":"katakana",      
    "romaji":"ju",
    "moji":"ジュ",
    "audio":"ju.mp3",
    "title":"ju",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_jo",
    "type":"katakana",      
    "romaji":"jo",
    "moji":"ジョ",
    "audio":"jo.mp3",
    "title":"jo",
  },
  {
    "id":"k_bya",
    "type":"katakana",      
    "romaji":"bya",
    "moji":"ビャ",
    "audio":"bya.mp3",
    "title":"bya",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_byu",
    "type":"katakana",      
    "romaji":"byu",
    "moji":"ビュ",
    "audio":"byu.mp3",
    "title":"byu",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_byo",
    "type":"katakana",      
    "romaji":"byo",
    "moji":"ビョ",
    "audio":"byo.mp3",
    "title":"byo",
  },
  {
    "id":"k_pya",
    "type":"katakana",      
    "romaji":"pya",
    "moji":"ピャ",
    "audio":"pya.mp3",
    "title":"pya",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_pyu",
    "type":"katakana",      
    "romaji":"pyu",
    "moji":"ピュ",
    "audio":"pyu.mp3",
    "title":"pyu",
  }, 
  {//blank
    "id":"",
    "type":"",      
    "romaji":"",
    "moji":"",
    "audio":"",
    "title":"",
  },
  {
    "id":"k_pyo",
    "type":"katakana",      
    "romaji":"pyo",
    "moji":"ピョ",
    "audio":"pyo.mp3",
    "title":"pyo",
  }
]

export const numberList = [
  //SeiOn
  {   
    "id":"num_1",
    "type":"vocabulary",  
    "romaji":"ichi",
    "moji":"いち",
    "kanji":"一",
    "english":"one",
    "audio":"ka.mp3"
  },
  {   
    "id":"num_2",
    "type":"vocabulary",      
    "romaji":"ni",
    "moji":"に",
    "kanji":"二",
    "english":"two",
    "audio":"ka.mp3"
  },
  {   
    "id":"num_3",
    "type":"vocabulary",      
    "romaji":"san",
    "moji":"さん",
    "kanji":"三",
    "english":"three",
    "audio":"ka.mp3"
  }, 
  { 
    "id":"num_4",
    "type":"vocabulary",      
    "romaji":"yon",
    "moji":"よん",
    "kanji":"四",
    "english":"four",
    "audio":"ka.mp3"
  },
  {   
    "id":"num_5",
    "type":"vocabulary",      
    "romaji":"yon",
    "moji":"よん",
    "kanji":"四",
    "english":"four",
    "audio":"ka.mp3"
  },
  {   
    "id":"num_6",
    "type":"vocabulary",      
    "romaji":"yon",
    "moji":"よん",
    "kanji":"四",
    "english":"four",
    "audio":"ka.mp3"
  },
  {   
    "id":"num_7",
    "type":"vocabulary",      
    "romaji":"yon",
    "moji":"よん",
    "kanji":"四",
    "english":"four",
    "audio":"ka.mp3"
  },
  {   
    "id":"num_8",
    "type":"vocabulary",      
    "romaji":"yon",
    "moji":"よん",
    "kanji":"四",
    "english":"four",
    "audio":"ka.mp3"
  },
  {   
    "id":"num_9",
    "type":"vocabulary",      
    "romaji":"yon",
    "moji":"よん",
    "kanji":"四",
    "english":"four",
    "audio":"ka.mp3"
  },
  {   
    "id":"num_10",
    "type":"vocabulary",      
    "romaji":"yon",
    "moji":"よん",
    "kanji":"四",
    "english":"four",
    "audio":"ka.mp3"
  },
  {   
    "id":"num_20",
    "type":"vocabulary",      
    "romaji":"yon",
    "moji":"よん",
    "kanji":"四",
    "english":"four",
    "audio":"ka.mp3"
  },
  {   
    "id":"num_100",
    "type":"vocabulary",      
    "romaji":"yon",
    "moji":"よん",
    "kanji":"四",
    "english":"four",
    "audio":"ka.mp3"
  },
  {   
    "id":"num_200",
    "type":"vocabulary",      
    "romaji":"yon",
    "moji":"よん",
    "kanji":"四",
    "english":"four",
    "audio":"ka.mp3"
  },
  {   
    "id":"num_1000",
    "type":"vocabulary",      
    "romaji":"yon",
    "moji":"よん",
    "kanji":"四",
    "english":"four",
    "audio":"ka.mp3"
  },
  {   
    "id":"num_10000",
    "type":"vocabulary",      
    "romaji":"yon",
    "moji":"よん",
    "kanji":"四",
    "english":"four",
    "audio":"ka.mp3"
  },
  {   
    "id":"num_1000000",
    "type":"vocabulary",      
    "romaji":"yon",
    "moji":"よん",
    "kanji":"四",
    "english":"four",
    "audio":"ka.mp3"
  },

]