export const hiraganalearn = [
    {hiragana: 'あ', romaji: 'a', url: 'a.mp3'},
    {hiragana: 'い', romaji: 'i', url: 'i.mp3'},
    {hiragana: 'う', romaji: 'u',  url: 'u.mp3'},
    {hiragana: 'え', romaji: 'e', url: 'e.mp3'},
    {hiragana: 'お', romaji: 'o',  url: 'o.mp3'},
    {hiragana: 'か', romaji: 'ka', url: 'ka.mp3'},
    {hiragana: 'き', romaji: 'ki',  url: 'ki.mp3'},
    {hiragana: 'く', romaji: 'ku', url: 'ku.mp3'},
    {hiragana: 'け', romaji: 'ke',  url: 'ke.mp3a'},
    {hiragana: 'こ', romaji: 'ko',  url: 'ko.mp3'},
    {hiragana: 'さ', romaji: 'sa',  url: 'sa.mp3'},
    {hiragana: 'し', romaji: 'shi',  url: 'shi.mp3'},
    {hiragana: 'す', romaji: 'su',  url: 'su.mp3'},
    {hiragana: 'せ', romaji: 'se',  url: 'se.mp3'},
    {hiragana: 'そ', romaji: 'so',  url: 'so.mp3'},
    {hiragana: 'た', romaji: 'ta',  url: 'ta.mp3'},
    {hiragana: 'ち', romaji: 'chi',  url: 'chi.mp3'},
    {hiragana: 'つ', romaji: 'tsu',  url: 'tsu.mp3'},
    {hiragana: 'て', romaji: 'te',  url: 'te.mp3'},
    {hiragana: 'と', romaji: 'to',  url: 'to.mp3',},
    {hiragana: 'な', romaji: 'na',  url: 'na.mp3'},
    {hiragana: 'に', romaji: 'ni',  url: 'ni.mp3'},
    {hiragana: 'ぬ', romaji: 'nu',  url: 'nu.mp3'},
    {hiragana: 'ね',  romaji: 'ne', url: 'ne.mp3'},
    {hiragana: 'の', romaji: 'no',  url: 'no.mp3',},
    {hiragana: 'は', romaji: 'ha',  url: 'ha.mp3',},
    {hiragana: 'ひ', romaji: 'hi',  url: 'hi.mp3',},
    {hiragana: 'ふ', romaji: 'hu',  url: 'hu.mp3',},
    {hiragana: 'へ', romaji: 'he',  url: 'he.mp3',},
    {hiragana: 'ほ', romaji: 'ho',  url: 'ho.mp3',},
    {hiragana: 'ま', romaji: 'ma',  url: 'ma.mp3'},
    {hiragana: 'み', romaji: 'mi',  url: 'mi.mp3'},
    {hiragana: 'む', romaji: 'mu',  url: 'mu.mp3'},
    {hiragana: 'め', romaji: 'me',  url: 'me.mp3'},
    {hiragana: 'も', romaji: 'mo',  url: 'mo.mp3',},
    {hiragana: 'や', romaji: 'ya',  url: 'ya.mp3'},
    {},
    {hiragana: 'ゆ', romaji: 'yu',  url: 'yu.mp3'},
    {},
    {hiragana: 'よ', romaji: 'yo',  url: 'yo.mp3'},
    {hiragana: 'ら', romaji: 'ra',  url: 'ra.mp3'},
    {hiragana: 'り', romaji: 'ri',  url: 'ri.mp3'},
    {hiragana: 'る', romaji: 'ru',  url: 'ru.mp3'},
    {hiragana: 'れ', romaji: 're',  url: 're.mp3'},
    {hiragana: 'ろ', romaji: 'ro',  url: 'ro.mp3',},
    {hiragana: 'わ', romaji: 'wa',  url: 'wa.mp3'},
    {},
    {},
    {},
    {hiragana: 'を', romaji: 'wo',  url: 'wo.mp3',},
    {hiragana: 'ん', romaji: 'n',  url: 'n.mp3',},
    {},
    {},
    {},
    {},
];
    export const katakanalearn = [
    {hiragana: 'ア', romaji: 'a', url: 'a.mp3'},
    {hiragana: 'イ', romaji: 'i', url: 'i.mp3'},
    {hiragana: 'ウ', romaji: 'u',  url: 'u.mp3'},
    {hiragana: 'エ', romaji: 'e', url: 'e.mp3'},
    {hiragana: 'オ', romaji: 'o',  url: 'o.mp3'},
    {hiragana: 'カ', romaji: 'ka', url: 'ka.mp3'},
    {hiragana: 'キ', romaji: 'ki',  url: 'ki.mp3'},
    {hiragana: 'ク', romaji: 'ku', url: 'ku.mp3'},
    {hiragana: 'ケ', romaji: 'ke',  url: 'ke.mp3a'},
    {hiragana: 'コ', romaji: 'ko',  url: 'ko.mp3'},
    {hiragana: 'サ', romaji: 'sa',  url: 'sa.mp3'},
    {hiragana: 'シ', romaji: 'shi',  url: 'shi.mp3'},
    {hiragana: 'ス', romaji: 'su',  url: 'su.mp3'},
    {hiragana: 'セ', romaji: 'se',  url: 'se.mp3'},
    {hiragana: 'ソ', romaji: 'so',  url: 'so.mp3'},
    {hiragana: 'タ', romaji: 'ta',  url: 'ta.mp3'},
    {hiragana: 'チ', romaji: 'chi',  url: 'chi.mp3'},
    {hiragana: 'ツ', romaji: 'tsu',  url: 'tsu.mp3'},
    {hiragana: 'テ', romaji: 'te',  url: 'te.mp3'},
    {hiragana: 'ト', romaji: 'to',  url: 'to.mp3',},
    {hiragana: 'ナ', romaji: 'na',  url: 'na.mp3'},
    {hiragana: 'ニ', romaji: 'ni',  url: 'ni.mp3'},
    {hiragana: 'ヌ', romaji: 'nu',  url: 'nu.mp3'},
    {hiragana: 'ネ',  romaji: 'ne', url: 'ne.mp3'},
    {hiragana: 'ノ', romaji: 'no',  url: 'no.mp3',},
    {hiragana: 'ハ', romaji: 'ha',  url: 'ha.mp3',},
    {hiragana: 'ヒ', romaji: 'hi',  url: 'hi.mp3',},
    {hiragana: 'フ', romaji: 'hu',  url: 'hu.mp3',},
    {hiragana: 'ヘ', romaji: 'he',  url: 'he.mp3',},
    {hiragana: 'ホ', romaji: 'ho',  url: 'ho.mp3',},
    {hiragana: 'マ', romaji: 'ma',  url: 'ma.mp3'},
    {hiragana: 'ミ', romaji: 'mi',  url: 'mi.mp3'},
    {hiragana: 'ム', romaji: 'mu',  url: 'mu.mp3'},
    {hiragana: 'メ', romaji: 'me',  url: 'me.mp3'},
    {hiragana: 'モ', romaji: 'mo',  url: 'mo.mp3',},
    {hiragana: 'ヤ', romaji: 'ya',  url: 'ya.mp3'},
    {},
    {hiragana: 'ユ', romaji: 'yu',  url: 'yu.mp3'},
    {},
    {hiragana: 'ヨ', romaji: 'yo',  url: 'yo.mp3'},
    {hiragana: 'ラ', romaji: 'ra',  url: 'ra.mp3'},
    {hiragana: 'リ', romaji: 'ri',  url: 'ri.mp3'},
    {hiragana: 'ル', romaji: 'ru',  url: 'ru.mp3'},
    {hiragana: 'レ', romaji: 're',  url: 're.mp3'},
    {hiragana: 'ロ', romaji: 'ro',  url: 'ro.mp3',},
    {hiragana: 'ワ', romaji: 'wa',  url: 'wa.mp3'},
    {},
    {},
    {},
    {hiragana: 'ヲ', romaji: 'wo',  url: 'wo.mp3',},
    {hiragana: 'ン', romaji: 'n',  url: 'n.mp3',},
    {},
    {},
    {},
    {},
];