export const ImageData = {
    loading : require('../assets/img/topic/image_loading.jpg'),
    default_bg : require('../assets/img/topic/class.jpg'),
    class : require('../assets/img/topic/class.jpg'),
    health : require('../assets/img/topic/health.jpg'),
    kotatsu_room : require('../assets/img/topic/kotatsu_room.jpg'),
    market : require('../assets/img/topic/market.png'),
    me_family : require('../assets/img/topic/me_family.jpg'),
    number_chara : require('../assets/img/topic/number_chara.jpg'),
    office : require('../assets/img/topic/office.jpg'),
    ramen_shop : require('../assets/img/topic/ramen_shop.jpg'),
    society : require('../assets/img/topic/society.jpg'),
    travel : require('../assets/img/topic/travel.jpg'),
    // Character
    happy : require('../assets/img/char/char-happy.png'),
    sad : require('../assets/img/char/char-sad.png'),
    default : require('../assets/img/char/char-default.png'),   
    HL2 : require('../assets/img/HL2.png'),   
    HomeImg : require('../assets/img/imgHome.png'), 
    //topic Img
    T001 : require('../assets/img/1ひらカタ.jpg'), 
    T002 : require('../assets/img/2数字.jpg'), 
    T003 : require('../assets/img/3あいさつ.jpg'), 
    T004 : require('../assets/img/4 自分.jpg'), 
    T005 : require('../assets/img/5家族.jpg'), 
    T006 : require('../assets/img/6住まい.jpg'), 
    T007 : require('../assets/img/7住環境.jpg'), 
    T008 : require('../assets/img/8自由時間.jpg'), 
    T009 : require('../assets/img/9 娯楽.jpg'), 
    T010 : require('../assets/img/10生活.jpg'), 
    T011 : require('../assets/img/11人生.jpg'), 
    T012 : require('../assets/img/12旅行.jpg'), 
    T013 : require('../assets/img/'), 
    T014 : require('../assets/img/14健康.jpg'), 
    T015 : require('../assets/img/15買い物.jpg'), 
    
      
}