// ES6 module syntax
import LocalizedStrings from 'react-native-localization';

// CommonJS syntax
// let LocalizedStrings  = require ('react-native-localization');

export let strings = new LocalizedStrings({
 en:{
   loginGuest: "Login",
   vocabulary : "Vocabulary",
   grammar : "Grammar",
   kanji : "Kanji",
   topic_test : "Topic test",
   next_topic : "Next Topic",
   TOPIC_LIST : "Topic List",
   HIRAGANA_TITLE: "Hiragana & Katakana",
   NUMBER_TITLE : "Number",
   GREETING_TITLE : "Greeting",
   TOPIC1_TITLE : "Myself",
   TOPIC2_TITLE : "Family",
   TOPIC3_TITLE : "House",
   TOPIC4_TITLE : "Living environments",
   TOPIC5_TITLE : "Free time",
   TOPIC6_TITLE : "Entertainment",
   TOPIC7_TITLE : "Living",
   TOPIC8_TITLE : "Human Life",
   TOPIC9_TITLE : "Travel",
   TOPIC10_TITLE : "Traffic",
   TOPIC11_TITLE : "health",
   TOPIC12_TITLE : "Shopping",
   TOPIC13_TITLE : "Eating habits",
   TOPIC14_TITLE : "Nature",
   TOPIC15_TITLE : "Trouble · Manner",
   TOPIC16_TITLE : "Language and Culture",
   // Question Panel
   QUESTION_SELECT : "Select",
   // Quiz
   TIMES_UP: "Time's up",
   WORD_LIST: "WORD LIST",
   EXPLANATION: "EXPLANATION",
   FLASH_CARD: "FLASH CARD",
   DRAW: "DRAW",
   GOI_LIST : "VOCABULARY LIST",
   BUNPO_LIST : "GRAMMAR LIST",
   KANJI_LIST : "KANJI LIST",
   FLASH_CARD_HIRAGANA: "FLASH CARD HIRAGANA",
   FLASH_CARD_KATAKANA: "FLASH CARD KATAKANA",
   HIKA_ROMA: "Hiragana/Katakana to Romaji",
   ROMA_HIKA: "Romaji to Hiragana/Katakana",
   LISTEN: "Listening",
   TRANSLATE_SENTENCE: "Translate the sentence",
   FLASH_CARD: "Listening\n(Translate)",
   FILL_THE_BLANKS: "Fill in the blanks",
   REARRANGE: "Rearrange the sentence",
   ENGLISH: "English",
   NEXT:'Next'
 },
 ja: {
   loginGuest: "japan",
   vocabulary : "語彙",
   grammar : "文法",
   kanji : "漢字",
   topic_test : "トピックテスト",
   next_topic : "次のトピック",
   TOPIC_LIST : "トピック一覧",   
   HIRAGANA_TITLE: "ひらがなとカタカナ",
   NUMBER_TITLE : "数字",
   GREETING_TITLE : "あいさつ",
   TOPIC1_TITLE : "自分",
   TOPIC2_TITLE : "家族",
   TOPIC3_TITLE : "住まい",
   TOPIC4_TITLE : "住環境",
   TOPIC5_TITLE : "自由時間",
   TOPIC6_TITLE : "娯楽",
   TOPIC7_TITLE : "生活",
   TOPIC8_TITLE : "人生",
   TOPIC9_TITLE : "旅行",
   TOPIC10_TITLE : "交通",
   TOPIC11_TITLE : "健康",
   TOPIC12_TITLE : "買い物",
   TOPIC13_TITLE : "食生活 ",
   TOPIC14_TITLE : "自然",
   TOPIC15_TITLE : "トラブル・マナー",
   TOPIC16_TITLE : "言語と文化",
   // Question Panel
   QUESTION_SELECT : "選ぶ",
   // Quiz
   TIMES_UP: "時間です",
   WORD_LIST: "WORD LIST",
   EXPLANATION: "EXPLANATION",
   FLASH_CARD: "FLASH CARD",
   DRAW: "DRAW",
   GOI_LIST : "VOCABULARY LIST",
   BUNPO_LIST : "GRAMMAR LIST",
   KANJI_LIST : "KANJI LIST",   
   FLASH_CARD_HIRAGANA: "FLASH CARD HIRAGANA",
   FLASH_CARD_KATAKANA: "FLASH CARD KATAKANA",
   HIKA_ROMA: "Hiragana/Katakana to Romaji",
   ROMA_HIKA: "Romaji to Hiragana/Katakana",
   LISTEN: "Listening",
   TRANSLATE_SENTENCE: "Translate the sentence",
   FLASH_CARD: "Listening\n(Translate)",
   FILL_THE_BLANKS: "Fill in the blanks",
   REARRANGE: "Rearrange the sentence",
   ENGLISH: "英語",
   NEXT:'次'
  }
});