// ES6 module syntax
import LocalizedStrings from 'react-native-localization';

// CommonJS syntax
// let LocalizedStrings  = require ('react-native-localization');

export let strings = new LocalizedStrings({
 en:{
   loginGuest: "Create Guest Account",
   vocabulary : "Vocabulary",
   grammar : "Grammar",
   kanji : "Kanji",
   topic_test : "Topic test",
   next_topic : "Next Topic",
   TOPIC_LIST : "Topic List",
   HIRAGANA_TITLE: "Hiragana & Katakana",
   NUMBER_TITLE : "Number",
   GREETING_TITLE : "Greeting",
   TOPIC1_TITLE : "Myself and family",
   TOPIC2_TITLE : "Housing and living environments",
   TOPIC3_TITLE : "Free time and entertainment",
   TOPIC4_TITLE : "Daily activity and life",
   TOPIC5_TITLE : "Work and occupation",
   TOPIC6_TITLE : "Travel and transportation",
   TOPIC7_TITLE : "Health",
   TOPIC8_TITLE : "Shopping",
   TOPIC9_TITLE : "Eating habits",
   TOPIC10_TITLE : "Nature and environment",
   TOPIC11_TITLE : "Relationship with people",
   TOPIC12_TITLE : "School and education",
   TOPIC13_TITLE : "Language and Culture",
   TOPIC14_TITLE : "Society",
   TOPIC15_TITLE : "Science and technology",
   TOPIC16_TITLE : "Language and Culture",
   // Question Panel
   QUESTION_SELECT : "Select",
   // Quiz
   TIMES_UP: "Time's up",
   WORD_LIST: "WORD LIST",
   EXPLANATION: "EXPLANATION",
   FLASH_CARD: "FLASH CARD",
   DRAW: "DRAW",
   GOI_LIST : "VOCABULARY LIST",
   BUNPO_LIST : "GRAMMAR LIST",
   KANJI_LIST : "KANJI LIST",
   FLASH_CARD_HIRAGANA: "FLASH CARD HIRAGANA",
   FLASH_CARD_KATAKANA: "FLASH CARD KATAKANA",
   
 },
 ja: {
   loginGuest: "japan",
   vocabulary : "語彙",
   grammar : "文法",
   kanji : "漢字",
   topic_test : "トピックテスト",
   next_topic : "次のトピック",
   TOPIC_LIST : "トピック一覧",   
   HIRAGANA_TITLE: "ひらがなとカタカナ",
   NUMBER_TITLE : "数字",
   GREETING_TITLE : "あいさつ",
   TOPIC1_TITLE : "自分と家族",
   TOPIC2_TITLE : "住まいと住環境",
   TOPIC3_TITLE : "自由時間と娯楽",
   TOPIC4_TITLE : "生活と人生",
   TOPIC5_TITLE : "仕事と職業",
   TOPIC6_TITLE : "旅行と交通",
   TOPIC7_TITLE : "健康",
   TOPIC8_TITLE : "買い物",
   TOPIC9_TITLE : "食生活",
   TOPIC10_TITLE : "自然と環境",
   TOPIC11_TITLE : "人との関係",
   TOPIC12_TITLE : "学校と教育",
   TOPIC13_TITLE : "言語と文化",
   TOPIC14_TITLE : "社会",
   TOPIC15_TITLE : "科学技術",
   TOPIC16_TITLE : "科学技術",
   // Question Panel
   QUESTION_SELECT : "選ぶ",
   // Quiz
   TIMES_UP: "時間です",
   WORD_LIST: "WORD LIST",
   EXPLANATION: "EXPLANATION",
   FLASH_CARD: "FLASH CARD",
   DRAW: "DRAW",
   GOI_LIST : "VOCABULARY LIST",
   BUNPO_LIST : "GRAMMAR LIST",
   KANJI_LIST : "KANJI LIST",   
   FLASH_CARD_HIRAGANA: "FLASH CARD HIRAGANA",
   FLASH_CARD_KATAKANA: "FLASH CARD KATAKANA",

  }
});