export const quizItems = [
    {   
        "id":"h_ka",
        "type":"hiragana",      
        "romaji":"ka",
        "moji":"か",
        "audio":"ka.mp3"
    },
    {   
        "id":"h_ki",
        "type":"hiragana",      
        "romaji":"ki",
        "moji":"き",
        "audio":"ki.mp3"
    },
    {   
        "id":"h_ku",
        "type":"hiragana",      
        "romaji":"ku",
        "moji":"く",
        "audio":"ku.mp3"
    },
    {   
        "id":"h_ke",
        "type":"hiragana",      
        "romaji":"ke",
        "moji":"け",
        "audio":"ke.mp3"
    },
    {   
        "id":"h_ko",
        "type":"hiragana",      
        "romaji":"ko",
        "moji":"こ",
        "audio":"ko.mp3"
    },
    {   
        "id":"h_sa",
        "type":"hiragana",      
        "romaji":"sa",
        "moji":"さ",
        "audio":"sa.mp3"
    },
    {   
        "id":"h_shi",
        "type":"hiragana",      
        "romaji":"shi",
        "moji":"し",
        "audio":"shi.mp3"
    },
    {   
        "id":"h_su",
        "type":"hiragana",      
        "romaji":"su",
        "moji":"す",
        "audio":"su.mp3"
    },
    {   
        "id":"h_se",
        "type":"hiragana",      
        "romaji":"se",
        "moji":"せ",
        "audio":"se.mp3"
    },
    {   
        "id":"h_so",
        "type":"hiragana",      
        "romaji":"so",
        "moji":"そ",
        "audio":"so.mp3"
    }
];

export const quizItemsShort = [
    {   
        "id":"h_ka",
        "type":"hiragana",      
        "romaji":"ka",
        "moji":"か",
        "audio":"ka.mp3"
    },
    {   
        "id":"h_ki",
        "type":"hiragana",      
        "romaji":"ki",
        "moji":"き",
        "audio":"ki.mp3"
    },
    {   
        "id":"h_ku",
        "type":"hiragana",      
        "romaji":"ku",
        "moji":"く",
        "audio":"ku.mp3"
    },
    {   
        "id":"h_ke",
        "type":"hiragana",      
        "romaji":"ke",
        "moji":"け",
        "audio":"ke.mp3"
    },
    {   
        "id":"h_ko",
        "type":"hiragana",      
        "romaji":"ko",
        "moji":"こ",
        "audio":"ko.mp3"
    }
];

export const numberQuiz = [
    {   
        "id":"num_1",
        "type":"vocabulary",  
        "romaji":"ichi",
        "moji":"いち",
        "kanji":"一",
        "english":"one",
        "audio":"ka.mp3"
    },
    {   
        "id":"num_1",
        "type":"vocabulary",      
        "romaji":"ni",
        "moji":"に",
        "kanji":"二",
        "english":"two",
        "audio":"ki.mp3"
    },
    {   
        "id":"num_1",
        "type":"vocabulary",      
        "romaji":"san",
        "moji":"さん",
        "kanji":"三",
        "english":"three",
        "audio":"ku.mp3"
    },
    {   
        "id":"num_1",
        "type":"vocabulary",      
        "romaji":"yon",
        "moji":"よん",
        "kanji":"四",
        "english":"four",
        "audio":"ke.mp3"
    },
    {   
        "id":"num_1",
        "type":"vocabulary",      
        "romaji":"go",
        "moji":"ご",
        "kanji":"五",
        "english":"five",
        "audio":"ko.mp3"
    }
];