export const summaryStyle = [{
    id: '',
    title: 'あ',
    totalLearn: '20',
    totalCorrect: '15',
    totalMistake: '5',
},
{
    id: '',
    title: 'い',
    totalLearn: '20',
    totalCorrect: '15',
    totalMistake: '5',
},
{
    id: '',
    title: 'う',
    totalLearn: '20',
    totalCorrect: '15',
    totalMistake: '5',
},
{
    id: '',
    title: 'え',
    totalLearn: '20',
    totalCorrect: '15',
    totalMistake: '5',
},
{
    id: '',
    title: 'お',
    totalLearn: '20',
    totalCorrect: '15',
    totalMistake: '5',
},
{
    id: '',
    title: 'か',
    totalLearn: '20',
    totalCorrect: '15',
    totalMistake: '5',
},
{
    id: '',
    title: 'き',
    totalLearn: '20',
    totalCorrect: '15',
    totalMistake: '5',
},
{
    id: '',
    title: 'く',
    totalLearn: '20',
    totalCorrect: '15',
    totalMistake: '5',
},
{
    id: '',
    title: 'け',
    totalLearn: '20',
    totalCorrect: '15',
    totalMistake: '5',
},
{
    id: '',
    title: 'こ',
    totalLearn: '20',
    totalCorrect: '15',
    totalMistake: '5',
},
{
    id: '',
    title: 'さ',
    totalLearn: '20',
    totalCorrect: '15',
    totalMistake: '5',
},
{
    id: '',
    title: 'し',
    totalLearn: '20',
    totalCorrect: '15',
    totalMistake: '5',
},

];