export const numbers = [
    {   
        "id":"num_1",
        "type":"vocabulary",  
        "romaji":"ichi",
        "moji":"いち",
        "kanji":"一",
        "english":"one",
        "audio":"ka.mp3"
    },
    {   
        "id":"num_2",
        "type":"vocabulary",      
        "romaji":"ni",
        "moji":"に",
        "kanji":"二",
        "english":"two",
        "audio":"ki.mp3"
    },
    {   
        "id":"num_3",
        "type":"vocabulary",      
        "romaji":"san",
        "moji":"さん",
        "kanji":"三",
        "english":"three",
        "audio":"ku.mp3"
    },
    {   
        "id":"num_4",
        "type":"vocabulary",      
        "romaji":"yon",
        "moji":"よん",
        "kanji":"四",
        "english":"four",
        "audio":"ke.mp3"
    },
    {   
        "id":"num_5",
        "type":"vocabulary",      
        "romaji":"go",
        "moji":"ご",
        "kanji":"五",
        "english":"five",
        "audio":"ko.mp3"
    },
    {   
        "id":"num_6",
        "type":"vocabulary",      
        "romaji":"roku",
        "moji":"ろく",
        "kanji":"六",
        "english":"six",
        "audio":"ko.mp3"
    },
    {   
      "id":"num_7",
      "type":"vocabulary",      
      "romaji":"nana",
      "moji":"なな",
      "kanji":"七",
      "english":"seven",
      "audio":"ko.mp3"
    },
    {   
      "id":"num_8",
      "type":"vocabulary",      
      "romaji":"hachi",
      "moji":"はち",
      "kanji":"八",
      "english":"eight",
      "audio":"ko.mp3"
    },
    {   
      "id":"num_9",
      "type":"vocabulary",      
      "romaji":"kyuu",
      "moji":"きゅう",
      "kanji":"九",
      "english":"nine",
      "audio":"ko.mp3"
    },
    {   
      "id":"num_10",
      "type":"vocabulary",      
      "romaji":"juu",
      "moji":"十",
      "kanji":"10",
      "english":"ten",
      "audio":"ko.mp3"
    },
    {   
      "id":"num_11",
      "type":"vocabulary",      
      "romaji":"hyaku",
      "moji":"ひゃく",
      "kanji":"百",
      "english":"hundred",
      "audio":"ko.mp3"
    },
    {   
      "id":"num_12",
      "type":"vocabulary",      
      "romaji":"sen",
      "moji":"せん",
      "kanji":"千",
      "english":"thousand",
      "audio":"ko.mp3"
    },
    {   
      "id":"num_13",
      "type":"vocabulary",      
      "romaji":"man",
      "moji":"まん",
      "kanji":"万",
      "english":"ten thousand",
      "audio":"ko.mp3"
    },
    {   
      "id":"num_14",
      "type":"vocabulary",      
      "romaji":"en",
      "moji":"えん",
      "kanji":"円",
      "english":"yen",
      "audio":"ko.mp3"
    }
]

export const greetings = [
    {   
        "id":"greet_1",
        "type":"vocabulary",  
        "romaji":"ohayougozaimasu",
        "moji":"おはようございます",
        "kanji":"お早うございます",
        "english":"Good morning",
        "audio":"ka.mp3"
    },
    {   
        "id":"greet_2",
        "type":"vocabulary",      
        "romaji":"konnichiha",
        "moji":"こんにちは",
        "kanji":"こんにちは",
        "english":"Good afternoon",
        "audio":"ki.mp3"
    },
    {   
        "id":"greet_3",
        "type":"vocabulary",      
        "romaji":"konbanha",
        "moji":"こんばんは",
        "kanji":"こんばんは",
        "english":"Good evening",
        "audio":"ku.mp3"
    },
    {   
        "id":"greet_4",
        "type":"vocabulary",      
        "romaji":"sayounara",
        "moji":"さようなら",
        "kanji":"さようなら",
        "english":"Good-bye",
        "audio":"ke.mp3"
    },
    {   
        "id":"greet_5",
        "type":"vocabulary",      
        "romaji":"arigatougozaimasu",
        "moji":"ありがとうございます",
        "kanji":"ありがとうございます",
        "english":"Thank you very much",
        "audio":"ko.mp3"
    },
    {   
        "id":"greet_6",
        "type":"vocabulary",      
        "romaji":"hajimemashite",
        "moji":"はじめまして",
        "kanji":"はじめまして",
        "english":"It's a pleasure to meet you",
        "audio":"ko.mp3"
    },
    {   
        "id":"greet_7",
        "type":"vocabulary",      
        "romaji":"yoroshikuonegaishimasu",
        "moji":"よろしくおねがいします",
        "kanji":"よろしくおねがいします",
        "english":"I'm looking forward to knowing you",
        "audio":"ko.mp3"
    },
    {   
        "id":"greet_8",
        "type":"vocabulary",      
        "romaji":"sumimasen",
        "moji":"すみません",
        "kanji":"すみません",
        "english":"Excuse me / I'm sorry",
        "audio":"ko.mp3"
    },
    {   
        "id":"greet_9",
        "type":"vocabulary",      
        "romaji":"oyasuminasai",
        "moji":"おやすみなさい",
        "kanji":"おやすみなさい",
        "english":"Good night",
        "audio":"ko.mp3"
    }
]