export const numbers = [
    {
        "id":"num_1",
        "type":"vocabulary",
        "english":"0",
        "moji":"ぜろ",
        "romaji":"zero",
        "audio":"n_zero.mp3"
    },    
    {
        "id":"num_2",
        "type":"vocabulary",
        "english":"1",
        "moji":"いち",
        "romaji":"ichi",
        "audio":"n_ichi.mp3"
    },    
    {
        "id":"num_3",
        "type":"vocabulary",
        "english":"2",
        "moji":"に",
        "romaji":"ni",
        "audio":"n_ni.mp3"
    },    
    {
        "id":"num_4",
        "type":"vocabulary",
        "english":"3",
        "moji":"さん",
        "romaji":"san",
        "audio":"n_san.mp3"
    },    
    {
        "id":"num_5",
        "type":"vocabulary",
        "english":"4",
        "moji":"よん/し",
        "romaji":"yon/shi",
        "audio":"n_yon.mp3"
    },    
    {
        "id":"num_6",
        "type":"vocabulary",
        "english":"5",
        "moji":"ご",
        "romaji":"go",
        "audio":"n_go.mp3"
    },    
    {
        "id":"num_7",
        "type":"vocabulary",
        "english":"6",
        "moji":"ろく",
        "romaji":"roku",
        "audio":"n_roku.mp3"
    },    
    {
        "id":"num_8",
        "type":"vocabulary",
        "english":"7",
        "moji":"なな/しち",
        "romaji":"nana/shichi",
        "audio":"n_nana.mp3"
    },    
    {
        "id":"num_9",
        "type":"vocabulary",
        "english":"8",
        "moji":"はち",
        "romaji":"hachi",
        "audio":"n_hachi.mp3"
    },    
    {
        "id":"num_10",
        "type":"vocabulary",
        "english":"9",
        "moji":"きゅう/く",
        "romaji":"kyuu/ku",
        "audio":"n_kyuu.mp3"
    },    
    {
        "id":"num_11",
        "type":"vocabulary",
        "english":"10",
        "moji":"じゅう",
        "romaji":"juu",
        "audio":"n_juu.mp3"
    },    
    {
        "id":"num_12",
        "type":"vocabulary",
        "english":"11",
        "moji":"じゅういち",
        "romaji":"juuichi",
        "audio":"n_juuichi.mp3"
    },    
    {
        "id":"num_13",
        "type":"vocabulary",
        "english":"12",
        "moji":"じゅうに",
        "romaji":"juuni",
        "audio":"n_juuni.mp3"
    },    
    {
        "id":"num_14",
        "type":"vocabulary",
        "english":"13",
        "moji":"じゅうさん",
        "romaji":"juusan",
        "audio":"n_juusan.mp3"
    },    
    {
        "id":"num_15",
        "type":"vocabulary",
        "english":"14",
        "moji":"じゅうよん/じゅうし",
        "romaji":"juuyon/juushi",
        "audio":"n_juuyon.mp3"
    },    
    {
        "id":"num_16",
        "type":"vocabulary",
        "english":"15",
        "moji":"じゅうご",
        "romaji":"juugo",
        "audio":"n_juugo.mp3"
    },    
    {
        "id":"num_17",
        "type":"vocabulary",
        "english":"16",
        "moji":"じゅうろく",
        "romaji":"juuroku",
        "audio":"n_juuroku.mp3"
    },    
    {
        "id":"num_18",
        "type":"vocabulary",
        "english":"17",
        "moji":"じゅうなな/じゅうしち",
        "romaji":"juunana/juushichi",
        "audio":"n_juunana.mp3"
    },    
    {
        "id":"num_19",
        "type":"vocabulary",
        "english":"18",
        "moji":"じゅうはち",
        "romaji":"juuhachi",
        "audio":"n_juuhachi.mp3"
    },    
    {
        "id":"num_20",
        "type":"vocabulary",
        "english":"19",
        "moji":"じゅうきゅう/じゅうく",
        "romaji":"juukyuu/juuku",
        "audio":"n_juukyuu.mp3"
    },    
    {
        "id":"num_21",
        "type":"vocabulary",
        "english":"20",
        "moji":"にじゅう",
        "romaji":"nijuu",
        "audio":"n_nijuu.mp3"
    },    
    {
        "id":"num_22",
        "type":"vocabulary",
        "english":"30",
        "moji":"さんじゅう",
        "romaji":"sanjuu",
        "audio":"n_sanjuu.mp3"
    },    
    {
        "id":"num_23",
        "type":"vocabulary",
        "english":"40",
        "moji":"よんじゅう",
        "romaji":"yonjuu",
        "audio":"n_yonjuu.mp3"
    },    
    {
        "id":"num_24",
        "type":"vocabulary",
        "english":"50",
        "moji":"ごじゅう",
        "romaji":"gojuu",
        "audio":"n_gojuu.mp3"
    },    
    {
        "id":"num_25",
        "type":"vocabulary",
        "english":"60",
        "moji":"ろくじゅう",
        "romaji":"rokujuu",
        "audio":"n_rokujuu.mp3"
    },    
    {
        "id":"num_26",
        "type":"vocabulary",
        "english":"70",
        "moji":"ななじゅう",
        "romaji":"nanajuu",
        "audio":"n_nanajuu.mp3"
    },    
    {
        "id":"num_27",
        "type":"vocabulary",
        "english":"80",
        "moji":"はちじゅう",
        "romaji":"hachijuu",
        "audio":"n_hachijuu.mp3"
    },    
    {
        "id":"num_28",
        "type":"vocabulary",
        "english":"90",
        "moji":"きゅうじゅう",
        "romaji":"kyuujuu",
        "audio":"n_kyuujuu.mp3"
    },    
    {
        "id":"num_29",
        "type":"vocabulary",
        "english":"100",
        "moji":"ひゃく",
        "romaji":"hyaku",
        "audio":"n_hyaku.mp3"
    },    
    {
        "id":"num_30",
        "type":"vocabulary",
        "english":"200",
        "moji":"にひゃく",
        "romaji":"nihyaku",
        "audio":"n_nihyaku.mp3"
    },    
    {
        "id":"num_31",
        "type":"vocabulary",
        "english":"300",
        "moji":"さんびゃく",
        "romaji":"sanbyaku",
        "audio":"n_sanbyaku.mp3"
    },    
    {
        "id":"num_32",
        "type":"vocabulary",
        "english":"400",
        "moji":"よんひゃく",
        "romaji":"yonhyaku",
        "audio":"n_yonhyaku.mp3"
    },    
    {
        "id":"num_33",
        "type":"vocabulary",
        "english":"500",
        "moji":"ごひゃく",
        "romaji":"gohyaku",
        "audio":"n_gohyaku.mp3"
    },    
    {
        "id":"num_34",
        "type":"vocabulary",
        "english":"600",
        "moji":"ろっぴゃく",
        "romaji":"roppyaku",
        "audio":"n_roppyaku.mp3"
    },    
    {
        "id":"num_35",
        "type":"vocabulary",
        "english":"700",
        "moji":"ななひゃく",
        "romaji":"nanahyaku",
        "audio":"n_nanahyaku.mp3"
    },    
    {
        "id":"num_36",
        "type":"vocabulary",
        "english":"800",
        "moji":"はっぴゃく",
        "romaji":"happyaku",
        "audio":"n_happyaku.mp3"
    },    
    {
        "id":"num_37",
        "type":"vocabulary",
        "english":"900",
        "moji":"きゅうひゃく",
        "romaji":"kyuuhyaku",
        "audio":"n_kyuuhyaku.mp3"
    },    
    {
        "id":"num_38",
        "type":"vocabulary",
        "english":"1000",
        "moji":"せん",
        "romaji":"sen",
        "audio":"n_sen.mp3"
    },    
    {
        "id":"num_39",
        "type":"vocabulary",
        "english":"2000",
        "moji":"にせん",
        "romaji":"nisen",
        "audio":"n_nisen.mp3"
    },    
    {
        "id":"num_40",
        "type":"vocabulary",
        "english":"3000",
        "moji":"さんぜん",
        "romaji":"sanzen",
        "audio":"n_sanzen.mp3"
    },    
    {
        "id":"num_41",
        "type":"vocabulary",
        "english":"4000",
        "moji":"よんせん",
        "romaji":"yonsen",
        "audio":"n_yonsen.mp3"
    },    
    {
        "id":"num_42",
        "type":"vocabulary",
        "english":"5000",
        "moji":"ごせん",
        "romaji":"gosen",
        "audio":"n_gosen.mp3"
    },    
    {
        "id":"num_43",
        "type":"vocabulary",
        "english":"6000",
        "moji":"ろくせん",
        "romaji":"rokusen",
        "audio":"n_rokusen.mp3"
    },    
    {
        "id":"num_44",
        "type":"vocabulary",
        "english":"7000",
        "moji":"ななせん",
        "romaji":"nanasen",
        "audio":"n_nanasen.mp3"
    },    
    {
        "id":"num_45",
        "type":"vocabulary",
        "english":"8000",
        "moji":"はっせん",
        "romaji":"hassen",
        "audio":"n_hassen.mp3"
    },    
    {
        "id":"num_46",
        "type":"vocabulary",
        "english":"9000",
        "moji":"きゅうせん",
        "romaji":"kyuusen",
        "audio":"n_kyuusen.mp3"
    },    
    {
        "id":"num_47",
        "type":"vocabulary",
        "english":"10,000",
        "moji":"いちまん",
        "romaji":"ichiman",
        "audio":"n_ichiman.mp3"
    },    
    {
        "id":"num_48",
        "type":"vocabulary",
        "english":"100,000",
        "moji":"じゅうまん",
        "romaji":"juuman",
        "audio":"n_juuman.mp3"
    },    
    {
        "id":"num_49",
        "type":"vocabulary",
        "english":"1,000,000",
        "moji":"ひゃくまん",
        "romaji":"hyakuman",
        "audio":"n_hyakuman.mp3"
    },    
    {
        "id":"num_50",
        "type":"vocabulary",
        "english":"1 thing",
        "moji":"ひとつ",
        "romaji":"hitotsu",
        "audio":"n_hitotsu.mp3"
    },    
    {
        "id":"num_51",
        "type":"vocabulary",
        "english":"2 things",
        "moji":"ふたつ",
        "romaji":"futatsu",
        "audio":"n_futatsu.mp3"
    },    
    {
        "id":"num_52",
        "type":"vocabulary",
        "english":"3 things",
        "moji":"みっつ",
        "romaji":"mittsu",
        "audio":"n_mittsu.mp3"
    },    
    {
        "id":"num_53",
        "type":"vocabulary",
        "english":"4 things",
        "moji":"よっつ",
        "romaji":"yottsu",
        "audio":"n_yottsu.mp3"
    },    
    {
        "id":"num_54",
        "type":"vocabulary",
        "english":"5 things",
        "moji":"いつつ",
        "romaji":"itsutsu",
        "audio":"n_itsutsu.mp3"
    },    
    {
        "id":"num_55",
        "type":"vocabulary",
        "english":"6 things",
        "moji":"むっつ",
        "romaji":"muttsu",
        "audio":"n_muttsu.mp3"
    },    
    {
        "id":"num_56",
        "type":"vocabulary",
        "english":"7 things",
        "moji":"ななつ",
        "romaji":"nanatsu",
        "audio":"n_nanatsu.mp3"
    },    
    {
        "id":"num_57",
        "type":"vocabulary",
        "english":"8 things",
        "moji":"やっつ",
        "romaji":"yattsu",
        "audio":"n_yattsu.mp3"
    },    
    {
        "id":"num_58",
        "type":"vocabulary",
        "english":"9 things",
        "moji":"ここのつ",
        "romaji":"kokonotsu",
        "audio":"n_kokonotsu.mp3"
    },    
    {
        "id":"num_59",
        "type":"vocabulary",
        "english":"10 things",
        "moji":"とお",
        "romaji":"too",
        "audio":"n_too.mp3"
    },    
    {
        "id":"num_60",
        "type":"vocabulary",
        "english":"1 piece",
        "moji":"いっこ",
        "romaji":"ikko",
        "audio":"n_ikko.mp3"
    },    
    {
        "id":"num_61",
        "type":"vocabulary",
        "english":"2 pieces",
        "moji":"にこ",
        "romaji":"niko",
        "audio":"n_niko.mp3"
    },    
    {
        "id":"num_62",
        "type":"vocabulary",
        "english":"3 pieces",
        "moji":"さんこ",
        "romaji":"sanko",
        "audio":"n_sanko.mp3"
    },    
    {
        "id":"num_63",
        "type":"vocabulary",
        "english":"4 pieces",
        "moji":"よんこ",
        "romaji":"yonko",
        "audio":"n_yonko.mp3"
    },    
    {
        "id":"num_64",
        "type":"vocabulary",
        "english":"5 pieces",
        "moji":"ごこ",
        "romaji":"goko",
        "audio":"n_goko.mp3"
    },    
    {
        "id":"num_65",
        "type":"vocabulary",
        "english":"6 pieces",
        "moji":"ろっこ",
        "romaji":"rokko",
        "audio":"n_rokko.mp3"
    },    
    {
        "id":"num_66",
        "type":"vocabulary",
        "english":"7 pieces",
        "moji":"ななこ",
        "romaji":"nanako",
        "audio":"n_nanako.mp3"
    },    
    {
        "id":"num_67",
        "type":"vocabulary",
        "english":"8 pieces",
        "moji":"はっこ",
        "romaji":"hakko",
        "audio":"n_hakko.mp3"
    },    
    {
        "id":"num_68",
        "type":"vocabulary",
        "english":"9 pieces",
        "moji":"きゅうこ",
        "romaji":"kyuuko",
        "audio":"n_kyuuko.mp3"
    },    
    {
        "id":"num_69",
        "type":"vocabulary",
        "english":"10 pieces",
        "moji":"じゅっこ",
        "romaji":"jukko",
        "audio":"n_jukko.mp3"
    },    
    {
        "id":"num_70",
        "type":"vocabulary",
        "english":"1 person",
        "moji":"ひとり",
        "romaji":"hitori",
        "audio":"n_hitori.mp3"
    },    
    {
        "id":"num_71",
        "type":"vocabulary",
        "english":"2 persons",
        "moji":"ふたり",
        "romaji":"futari",
        "audio":"n_futari.mp3"
    },    
    {
        "id":"num_72",
        "type":"vocabulary",
        "english":"3 persons",
        "moji":"さんにん",
        "romaji":"sannin",
        "audio":"n_sannin.mp3"
    },    
    {
        "id":"num_73",
        "type":"vocabulary",
        "english":"4 persons",
        "moji":"よにん",
        "romaji":"yonin",
        "audio":"n_yonin.mp3"
    },    
    {
        "id":"num_74",
        "type":"vocabulary",
        "english":"5 persons",
        "moji":"ごにん",
        "romaji":"gonin",
        "audio":"n_gonin.mp3"
    },    
    {
        "id":"num_75",
        "type":"vocabulary",
        "english":"6 persons",
        "moji":"ろくにん",
        "romaji":"rokunin",
        "audio":"n_rokunin.mp3"
    },    
    {
        "id":"num_76",
        "type":"vocabulary",
        "english":"7 persons",
        "moji":"ななにん",
        "romaji":"nananin",
        "audio":"n_nananin.mp3"
    },    
    {
        "id":"num_77",
        "type":"vocabulary",
        "english":"8 persons",
        "moji":"はちにん",
        "romaji":"hachinin",
        "audio":"n_hachinin.mp3"
    },    
    {
        "id":"num_78",
        "type":"vocabulary",
        "english":"9 persons",
        "moji":"きゅうにん",
        "romaji":"kyuunin",
        "audio":"n_kyuunin.mp3"
    },    
    {
        "id":"num_79",
        "type":"vocabulary",
        "english":"10 persons",
        "moji":"じゅうにん",
        "romaji":"juunin",
        "audio":"n_juunin.mp3"
    },    
    {
        "id":"num_80",
        "type":"vocabulary",
        "english":"1 thin and long thing",
        "moji":"いっぽん",
        "romaji":"ippon",
        "audio":"n_ippon.mp3"
    },    
    {
        "id":"num_81",
        "type":"vocabulary",
        "english":"2 thin and long things",
        "moji":"にほん",
        "romaji":"nihon",
        "audio":"n_nihon.mp3"
    },    
    {
        "id":"num_82",
        "type":"vocabulary",
        "english":"3 thin and long things",
        "moji":"さんぼん",
        "romaji":"sanbon",
        "audio":"n_sanbon.mp3"
    },    
    {
        "id":"num_83",
        "type":"vocabulary",
        "english":"4 thin and long things",
        "moji":"よんほん",
        "romaji":"yonhon",
        "audio":"n_yonhon.mp3"
    },    
    {
        "id":"num_84",
        "type":"vocabulary",
        "english":"5 thin and long things",
        "moji":"ごほん",
        "romaji":"gohon",
        "audio":"n_gohon.mp3"
    },    
    {
        "id":"num_85",
        "type":"vocabulary",
        "english":"6 thin and long things",
        "moji":"ろっぽん",
        "romaji":"roppon",
        "audio":"n_roppon.mp3"
    },    
    {
        "id":"num_86",
        "type":"vocabulary",
        "english":"7 thin and long things",
        "moji":"ななほん",
        "romaji":"nanahon",
        "audio":"n_nanahon.mp3"
    },    
    {
        "id":"num_87",
        "type":"vocabulary",
        "english":"8 thin and long things",
        "moji":"はっぽん",
        "romaji":"happon",
        "audio":"n_happon.mp3"
    },    
    {
        "id":"num_88",
        "type":"vocabulary",
        "english":"9 thin and long things",
        "moji":"きゅうほん",
        "romaji":"kyuuhon",
        "audio":"n_kyuuhon.mp3"
    },    
    {
        "id":"num_89",
        "type":"vocabulary",
        "english":"10 thin and long things",
        "moji":"じゅっぽん",
        "romaji":"juppon",
        "audio":"n_juppon.mp3"
    },    
    {
        "id":"num_90",
        "type":"vocabulary",
        "english":"1 sheet",
        "moji":"いちまい",
        "romaji":"ichimai",
        "audio":"n_ichimai.mp3"
    },    
    {
        "id":"num_91",
        "type":"vocabulary",
        "english":"2 sheets",
        "moji":"にまい",
        "romaji":"nimai",
        "audio":"n_nimai.mp3"
    },    
    {
        "id":"num_92",
        "type":"vocabulary",
        "english":"3 sheets",
        "moji":"さんまい",
        "romaji":"sanmai",
        "audio":"n_sanmai.mp3"
    },    
    {
        "id":"num_93",
        "type":"vocabulary",
        "english":"4 sheets",
        "moji":"よんまい",
        "romaji":"yonmai",
        "audio":"n_yonmai.mp3"
    },    
    {
        "id":"num_94",
        "type":"vocabulary",
        "english":"5 sheets",
        "moji":"ごまい",
        "romaji":"gomai",
        "audio":"n_gomai.mp3"
    },    
    {
        "id":"num_95",
        "type":"vocabulary",
        "english":"6 sheets",
        "moji":"ろくまい",
        "romaji":"rokumai",
        "audio":"n_rokumai.mp3"
    },    
    {
        "id":"num_96",
        "type":"vocabulary",
        "english":"7 sheets",
        "moji":"ななまい",
        "romaji":"nanamai",
        "audio":"n_nanamai.mp3"
    },    
    {
        "id":"num_97",
        "type":"vocabulary",
        "english":"8 sheets",
        "moji":"はちまい",
        "romaji":"hachimai",
        "audio":"n_hachimai.mp3"
    },    
    {
        "id":"num_98",
        "type":"vocabulary",
        "english":"9 sheets",
        "moji":"きゅうまい",
        "romaji":"kyuumai",
        "audio":"n_kyuumai.mp3"
    },    
    {
        "id":"num_99",
        "type":"vocabulary",
        "english":"10 sheets",
        "moji":"じゅうまい",
        "romaji":"juumai",
        "audio":"n_juumai.mp3"
    },        
]

export const greetings = [
    {   
        "id":"greet_1",
        "type":"vocabulary",  
        "romaji":"ohayougozaimasu",
        "moji":"おはようございます",
        "kanji":"お早うございます",
        "english":"Good morning",
        "audio":"g_ohayougozaimasu.mp3"
    },
    {   
        "id":"greet_2",
        "type":"vocabulary",      
        "romaji":"konnichiha",
        "moji":"こんにちは",
        "kanji":"こんにちは",
        "english":"Good afternoon",
        "audio":"g_konnichiha.mp3"
    },
    {   
        "id":"greet_3",
        "type":"vocabulary",      
        "romaji":"konbanha",
        "moji":"こんばんは",
        "kanji":"こんばんは",
        "english":"Good evening",
        "audio":"g_konbanha.mp3"
    },
    {   
        "id":"greet_4",
        "type":"vocabulary",      
        "romaji":"sayounara",
        "moji":"さようなら",
        "kanji":"さようなら",
        "english":"Good-bye",
        "audio":"g_sayounara.mp3"
    },
    {   
        "id":"greet_5",
        "type":"vocabulary",      
        "romaji":"arigatougozaimasu",
        "moji":"ありがとうございます",
        "kanji":"ありがとうございます",
        "english":"Thank you very much",
        "audio":"g_arigatougozaimasu.mp3"
    },
    {   
        "id":"greet_6",
        "type":"vocabulary",      
        "romaji":"hajimemashite",
        "moji":"はじめまして",
        "kanji":"はじめまして",
        "english":"It's a pleasure to meet you",
        "audio":"g_hajimemashite.mp3"
    },
    {   
        "id":"greet_7",
        "type":"vocabulary",      
        "romaji":"yoroshikuonegaishimasu",
        "moji":"よろしくおねがいします",
        "kanji":"よろしくおねがいします",
        "english":"I'm looking forward to knowing you",
        "audio":"g_yoroshikuonegaishimasu.mp3"
    },
    {   
        "id":"greet_8",
        "type":"vocabulary",      
        "romaji":"sumimasen",
        "moji":"すみません",
        "kanji":"すみません",
        "english":"Excuse me / I'm sorry",
        "audio":"g_sumimasen.mp3"
    },
    {   
        "id":"greet_9",
        "type":"vocabulary",      
        "romaji":"oyasuminasai",
        "moji":"おやすみなさい",
        "kanji":"おやすみなさい",
        "english":"Good night",
        "audio":"g_oyasuminasai.mp3"
    }
]