export const vocabulary = [
    {
        "id":"tp6_v_1",
        "type":"vocabulary",
        "moji":"あおい",
        "romaji":"aoi",
        "english":"blue",
        "audio":"t6_aoi.mp3"
    },
    {
        "id":"tp6_v_2",
        "type":"vocabulary",
        "moji":"あかい",
        "romaji":"akai",
        "english":"red",
        "audio":"t6_akai.mp3"
    },
    {
        "id":"tp6_v_3",
        "type":"vocabulary",
        "moji":"あかるい",
        "romaji":"akarui",
        "english":"bright",
        "audio":"t6_akarui.mp3"
    },
    {
        "id":"tp6_v_4",
        "type":"vocabulary",
        "moji":"あけます",
        "romaji":"akemasu",
        "english":"to open",
        "audio":"t6_akemasu.mp3"
    },
    {
        "id":"tp6_v_5",
        "type":"vocabulary",
        "moji":"あし",
        "romaji":"ashi",
        "english":"foot, leg",
        "audio":"t6_ashi.mp3"
    },
    {
        "id":"tp6_v_6",
        "type":"vocabulary",
        "moji":"あたま",
        "romaji":"atama",
        "english":"head",
        "audio":"t6_atama.mp3"
    },
    {
        "id":"tp6_v_7",
        "type":"vocabulary",
        "moji":"あに",
        "romaji":"ani",
        "english":"(humble) older brother",
        "audio":"t6_ani.mp3"
    },
    {
        "id":"tp6_v_8",
        "type":"vocabulary",
        "moji":"あね",
        "romaji":"ane",
        "english":"(humble) older sister",
        "audio":"t6_ane.mp3"
    },
    {
        "id":"tp6_v_9",
        "type":"vocabulary",
        "moji":"あぶない",
        "romaji":"abunai",
        "english":"dangerous",
        "audio":"t6_abunai.mp3"
    },
    {
        "id":"tp6_v_10",
        "type":"vocabulary",
        "moji":"あまい",
        "romaji":"amai",
        "english":"sweet",
        "audio":"t6_amai.mp3"
    },
    {
        "id":"tp6_v_11",
        "type":"vocabulary",
        "moji":"いもうと",
        "romaji":"imōto",
        "english":"(humble) younger sister",
        "audio":"t6_imouto.mp3"
    },
    {
        "id":"tp6_v_12",
        "type":"vocabulary",
        "moji":"いろ",
        "romaji":"iro",
        "english":"color",
        "audio":"t6_iro.mp3"
    },
    {
        "id":"tp6_v_13",
        "type":"vocabulary",
        "moji":"うるさい",
        "romaji":"urusai",
        "english":"noisy, annoying",
        "audio":"t6_urusai.mp3"
    },
    {
        "id":"tp6_v_14",
        "type":"vocabulary",
        "moji":"おおい",
        "romaji":"ōi",
        "english":"many",
        "audio":"t6_oui.mp3"
    },
    {
        "id":"tp6_v_15",
        "type":"vocabulary",
        "moji":"おかあさん",
        "romaji":"o kā-san",
        "english":"(honorable) mother",
        "audio":"t6_oka-san.mp3"
    },
    {
        "id":"tp6_v_16",
        "type":"vocabulary",
        "moji":"おくさん",
        "romaji":"oku-san",
        "english":"(honorable) wife",
        "audio":"t6_oku-san.mp3"
    },
    {
        "id":"tp6_v_17",
        "type":"vocabulary",
        "moji":"おじいさん",
        "romaji":"o jī-san",
        "english":"grandfather, male senior citizen",
        "audio":"t6_ojii-san.mp3"
    },
    {
        "id":"tp6_v_18",
        "type":"vocabulary",
        "moji":"おじさん",
        "romaji":"o jisan",
        "english":"uncle, middle aged gentleman",
        "audio":"t6_oji-san.mp3"
    },
    {
        "id":"tp6_v_19",
        "type":"vocabulary",
        "moji":"おとうさん",
        "romaji":"o tō-san",
        "english":"(honorable) father",
        "audio":"t6_otou-san.mp3"
    },
    {
        "id":"tp6_v_20",
        "type":"vocabulary",
        "moji":"おとうと",
        "romaji":"otōto",
        "english":"younger brother",
        "audio":"t6_otouto.mp3"
    },
    {
        "id":"tp6_v_21",
        "type":"vocabulary",
        "moji":"おとな",
        "romaji":"otona",
        "english":"Adult",
        "audio":"t6_otona.mp3"
    },
    {
        "id":"tp6_v_22",
        "type":"vocabulary",
        "moji":"おにいさん",
        "romaji":"o nī-san",
        "english":"(honorable) older brother",
        "audio":"t6_onii-san.mp3"
    },
    {
        "id":"tp6_v_23",
        "type":"vocabulary",
        "moji":"おねえさん",
        "romaji":"o nei-san",
        "english":"(honorable) older sister",
        "audio":"t6_onei-san.mp3"
    },
    {
        "id":"tp6_v_24",
        "type":"vocabulary",
        "moji":"おば",
        "romaji":"oba",
        "english":"Aunt",
        "audio":"t6_oba.mp3"
    },
    {
        "id":"tp6_v_25",
        "type":"vocabulary",
        "moji":"おばあさん",
        "romaji":"o bā-san",
        "english":"grandmother, female senior-citizen",
        "audio":"t6_oba-san.mp3"
    },
    {
        "id":"tp6_v_26",
        "type":"vocabulary",
        "moji":"おもい",
        "romaji":"omoi",
        "english":"Heavy",
        "audio":"t6_omoi.mp3"
    },
    {
        "id":"tp6_v_27",
        "type":"vocabulary",
        "moji":"おもしろい",
        "romaji":"omoshiroi",
        "english":"Interesting",
        "audio":"t6_omoshiroi.mp3"
    },
    {
        "id":"tp6_v_28",
        "type":"vocabulary",
        "moji":"かお",
        "romaji":"kao",
        "english":"face",
        "audio":"t6_kao.mp3"
    },
    {
        "id":"tp6_v_29",
        "type":"vocabulary",
        "moji":"かぶります",
        "romaji":"kaburimasu",
        "english":"to put on/ wear (hats, caps, hoods)",
        "audio":"t6_kaburimasu.mp3"
    },
    {
        "id":"tp6_v_30",
        "type":"vocabulary",
        "moji":"からい",
        "romaji":"karai",
        "english":"Spicy",
        "audio":"t6_karai.mp3"
    },
    {
        "id":"tp6_v_31",
        "type":"vocabulary",
        "moji":"からだ",
        "romaji":"karada",
        "english":"Body",
        "audio":"t6_karada.mp3"
    },
    {
        "id":"tp6_v_32",
        "type":"vocabulary",
        "moji":"かるい",
        "romaji":"karui",
        "english":"Light",
        "audio":"t6_karui.mp3"
    },
    {
        "id":"tp6_v_33",
        "type":"vocabulary",
        "moji":"かわいい",
        "romaji":"kawaī",
        "english":"Cute",
        "audio":"t6_kawaii.mp3"
    },
    {
        "id":"tp6_v_34",
        "type":"vocabulary",
        "moji":"きえます",
        "romaji":"kiemasu",
        "english":"to disappear",
        "audio":"t6_kiemasu.mp3"
    },
    {
        "id":"tp6_v_35",
        "type":"vocabulary",
        "moji":"きって",
        "romaji":"kitte",
        "english":"postage stamp",
        "audio":"t6_kitte.mp3"
    },
    {
        "id":"tp6_v_36",
        "type":"vocabulary",
        "moji":"きょうだい",
        "romaji":"kyōdai",
        "english":"(humble) siblings",
        "audio":"t6_kyoudai.mp3"
    },
    {
        "id":"tp6_v_37",
        "type":"vocabulary",
        "moji":"くち",
        "romaji":"kuchi",
        "english":"mouth, opening",
        "audio":"t6_kuchi.mp3"
    },
    {
        "id":"tp6_v_38",
        "type":"vocabulary",
        "moji":"くらい",
        "romaji":"kurai",
        "english":"Gloomy",
        "audio":"t6_kurai.mp3"
    },
    {
        "id":"tp6_v_39",
        "type":"vocabulary",
        "moji":"くろい",
        "romaji":"kuroi",
        "english":"black",
        "audio":"t6_kuroi.mp3"
    },
    {
        "id":"tp6_v_40",
        "type":"vocabulary",
        "moji":"けします",
        "romaji":"keshimasu",
        "english":"to erase, to turn off power",
        "audio":"t6_keshimasu.mp3"
    },
    {
        "id":"tp6_v_41",
        "type":"vocabulary",
        "moji":"けっこんします",
        "romaji":"kekkon shimasu",
        "english":"to marry",
        "audio":"t6_kekkonshimasu.mp3"
    },
    {
        "id":"tp6_v_42",
        "type":"vocabulary",
        "moji":"こども",
        "romaji":"kodomo",
        "english":"Child",
        "audio":"t6_kodomo.mp3"
    },
    {
        "id":"tp6_v_43",
        "type":"vocabulary",
        "moji":"しにます",
        "romaji":"shinimasu",
        "english":"to die",
        "audio":"t6_shinimasu.mp3"
    },
    {
        "id":"tp6_v_44",
        "type":"vocabulary",
        "moji":"しゅみ",
        "romaji":"shuumi",
        "english":"hobby",
        "audio":"t6_shumi.mp3"
    },
    {
        "id":"tp6_v_45",
        "type":"vocabulary",
        "moji":"じょうず",
        "romaji":"jōzu",
        "english":"Skillful",
        "audio":"t6_jouzu.mp3"
    },
    {
        "id":"tp6_v_46",
        "type":"vocabulary",
        "moji":"じょうぶ",
        "romaji":"jōbu",
        "english":"strong, durable",
        "audio":"t6_joubu.mp3"
    },
    {
        "id":"tp6_v_47",
        "type":"vocabulary",
        "moji":"しります",
        "romaji":"shirimasu",
        "english":"to know",
        "audio":"t6_shirimasu.mp3"
    },
    {
        "id":"tp6_v_48",
        "type":"vocabulary",
        "moji":"しろい",
        "romaji":"shiroi",
        "english":"White",
        "audio":"t6_shiroi.mp3"
    },
    {
        "id":"tp6_v_49",
        "type":"vocabulary",
        "moji":"すくない",
        "romaji":"sukunai",
        "english":"a few",
        "audio":"t6_sukunai.mp3"
    },
    {
        "id":"tp6_v_50",
        "type":"vocabulary",
        "moji":"すみます",
        "romaji":"sumimasu",
        "english":"to live in",
        "audio":"t6_sumimasu.mp3"
    },
    {
        "id":"tp6_v_51",
        "type":"vocabulary",
        "moji":"せ",
        "romaji":"se",
        "english":"height, stature",
        "audio":"t6_se.mp3"
    },
    {
        "id":"tp6_v_52",
        "type":"vocabulary",
        "moji":"たいせつ",
        "romaji":"taisetsu",
        "english":"important",
        "audio":"t6_taisetsu.mp3"
    },
    {
        "id":"tp6_v_53",
        "type":"vocabulary",
        "moji":"ちかい",
        "romaji":"chikai",
        "english":"near",
        "audio":"t6_chikai.mp3"
    },
    {
        "id":"tp6_v_54",
        "type":"vocabulary",
        "moji":"つよい",
        "romaji":"tsuyoi",
        "english":"powerful",
        "audio":"t6_tsuyoi.mp3"
    },
    {
        "id":"tp6_v_55",
        "type":"vocabulary",
        "moji":"て",
        "romaji":"te",
        "english":"hand",
        "audio":"t6_te.mp3"
    },
    {
        "id":"tp6_v_56",
        "type":"vocabulary",
        "moji":"とおい",
        "romaji":"tōi",
        "english":"far",
        "audio":"t6_toui.mp3"
    },
    {
        "id":"tp6_v_57",
        "type":"vocabulary",
        "moji":"ながい",
        "romaji":"nagai",
        "english":"long",
        "audio":"t6_nagai.mp3"
    },
    {
        "id":"tp6_v_58",
        "type":"vocabulary",
        "moji":"ならびます",
        "romaji":"narabimasu",
        "english":"to line up, to stand in a line",
        "audio":"t6_narabimasu.mp3"
    },
    {
        "id":"tp6_v_59",
        "type":"vocabulary",
        "moji":"なります",
        "romaji":"narimasu",
        "english":"to become",
        "audio":"t6_narimasu.mp3"
    },
    {
        "id":"tp6_v_60",
        "type":"vocabulary",
        "moji":"はな",
        "romaji":"hana",
        "english":"nose",
        "audio":"t6_hana.mp3"
    },
    {
        "id":"tp6_v_61",
        "type":"vocabulary",
        "moji":"ひと",
        "romaji":"hito",
        "english":"person",
        "audio":"t6_hito.mp3"
    },
    {
        "id":"tp6_v_62",
        "type":"vocabulary",
        "moji":"ひろい",
        "romaji":"hiroi",
        "english":"spacious, wide",
        "audio":"t6_hiroi.mp3"
    },
    {
        "id":"tp6_v_63",
        "type":"vocabulary",
        "moji":"へた",
        "romaji":"heta",
        "english":"unskillful",
        "audio":"t6_heta.mp3"
    },
    {
        "id":"tp6_v_64",
        "type":"vocabulary",
        "moji":"まるい",
        "romaji":"marui",
        "english":"round, circular",
        "audio":"t6_marui.mp3"
    },
    {
        "id":"tp6_v_65",
        "type":"vocabulary",
        "moji":"みじかい",
        "romaji":"mijikai",
        "english":"short",
        "audio":"t6_mijikai.mp3"
    },
    {
        "id":"tp6_v_66",
        "type":"vocabulary",
        "moji":"みどり",
        "romaji":"midori",
        "english":"green",
        "audio":"t6_midori.mp3"
    },
    {
        "id":"tp6_v_67",
        "type":"vocabulary",
        "moji":"みみ",
        "romaji":"mimi",
        "english":"ear",
        "audio":"t6_mimi.mp3"
    },
    {
        "id":"tp6_v_68",
        "type":"vocabulary",
        "moji":"め",
        "romaji":"me",
        "english":"eye",
        "audio":"t6_me.mp3"
    },
    {
        "id":"tp6_v_69",
        "type":"vocabulary",
        "moji":"もちます",
        "romaji":"mochimasu",
        "english":"to hold",
        "audio":"t6_mochimasu.mp3"
    },
    {
        "id":"tp6_v_70",
        "type":"vocabulary",
        "moji":"よわい",
        "romaji":"yowai",
        "english":"weak",
        "audio":"t6_yowai.mp3"
    },
    {
        "id":"tp6_v_71",
        "type":"vocabulary",
        "moji":"りょうしん",
        "romaji":"Ryō shin",
        "english":"both parents",
        "audio":"t6_ryoushin.mp3"
    },
    {
        "id":"tp6_v_72",
        "type":"vocabulary",
        "moji":"わかい",
        "romaji":"wakai",
        "english":"young",
        "audio":"t6_wakai.mp3"
    }
]

export const kanji = [
    {
        "id":"tp6_k_1",
        "type":"kanji",
        "romaji":"tō/ chichi",
        "moji":"とう/ちち",
        "kanji":"父",
        "english":"father",
        "audio":"t6_tou_chichi.mp3"
    },
    {
        "id":"tp6_k_2",
        "type":"kanji",
        "romaji":"kā/ haha",
        "moji":"かあ/はは",
        "kanji":"母",
        "english":"mother",
        "audio":"t6_kaa_haha.mp3"
    },
    {
        "id":"tp6_k_3",
        "type":"kanji",
        "romaji":"ta",
        "moji":"た",
        "kanji":"食",
        "english":"to eat",
        "audio":"t6_ta.mp3"
    },
    {
        "id":"tp6_k_4",
        "type":"kanji",
        "romaji":"no",
        "moji":"の",
        "kanji":"飲",
        "english":"to drink",
        "audio":"t6_no.mp3"
    },
    {
        "id":"tp6_k_5",
        "type":"kanji",
        "romaji":"ka",
        "moji":"か",
        "kanji":"書",
        "english":"to write",
        "audio":"t6_ka.mp3"
    },
    {
        "id":"tp6_k_6",
        "type":"kanji",
        "romaji":"mi",
        "moji":"み",
        "kanji":"見",
        "english":"to watch / look",
        "audio":"t6_mi.mp3"
    },
    {
        "id":"tp6_k_7",
        "type":"kanji",
        "romaji":"i",
        "moji":"い",
        "kanji":"言",
        "english":"to say",
        "audio":"t6_i.mp3"
    },
    {
        "id":"tp6_k_8",
        "type":"kanji",
        "romaji":"wa/ Hana",
        "moji":"わ/はな",
        "kanji":"話",
        "english":"to talk",
        "audio":"t6_wa_hana.mp3"
    },
    {
        "id":"tp6_k_9",
        "type":"kanji",
        "romaji":"yo",
        "moji":"よ",
        "kanji":"読",
        "english":"to read",
        "audio":"t6_yo.mp3"
    },
    {
        "id":"tp6_k_10",
        "type":"kanji",
        "romaji":"ka",
        "moji":"か",
        "kanji":"買",
        "english":"to buy",
        "audio":"t6_kau.mp3"
    },
    {
        "id":"tp6_k_11",
        "type":"kanji",
        "romaji":"bun/ kiku",
        "moji":"ぶん/きく",
        "kanji":"聞",
        "english":"to listen",
        "audio":"t6_bun_kiku.mp3"
    },
    {
        "id":"tp6_k_12",
        "type":"kanji",
        "romaji":"yasumu",
        "moji":"やすむ",
        "kanji":"休",
        "english":"to rest",
        "audio":"t6_yasumu.mp3"
    },
    {
        "id":"tp6_k_13",
        "type":"kanji",
        "romaji":"deru",
        "moji":"でる",
        "kanji":"出",
        "english":"to go out",
        "audio":""
    },
    {
        "id":"tp6_k_14",
        "type":"kanji",
        "romaji":"hairu",
        "moji":"はいる",
        "kanji":"入",
        "english":"to enter",
        "audio":"t6_hairu.mp3"
    },
    {
        "id":"tp6_k_15",
        "type":"kanji",
        "romaji":"tatsu",
        "moji":"たつ",
        "kanji":"立",
        "english":"to stand",
        "audio":"t6_tatsu.mp3"
    },
]

export const grammar = [
]

export const listening = [
    {
        "id":"tp6_l_1",
        "type":"listening",
        "romaji":"友達",
        "moji":"友達",
        "kanji":"友達",
        "english":"友達",
        "answerOption":[
            {
                "id":"tp6_l_1",
                "type":"listening",
                "moji":"友達"
            },
            {
                "id":"tp6_l_2",
                "type":"listening",
                "moji":"弟さん"
            },
            {
                "id":"tp6_l_3",
                "type":"listening",
                "moji":"お兄さん"
            },
            {
                "id":"tp6_l_4",
                "type":"listening",
                "moji":"山田さん"
            }
        ],
        "audio":"t6_listening_1.mp3"
    },
    {
        "id":"tp6_l_2",
        "type":"listening",
        "romaji":"背が高いです",
        "moji":"背が高いです",
        "kanji":"背が高いです",
        "english":"背が高いです",
        "answerOption":[
            {
                "id":"tp6_l_2",
                "type":"listening",
                "moji":"背が高いです"
            },
            {
                "id":"tp6_l_1",
                "type":"listening",
                "moji":"背が低いです"
            },
            {
                "id":"tp6_l_3",
                "type":"listening",
                "moji":"髪が長いです"
            },
            {
                "id":"tp6_l_4",
                "type":"listening",
                "moji":"目が小さいです"
            }
        ],
        "audio":"t6_listening_2.mp3"
    },
    {
        "id":"tp6_l_1",
        "type":"listening",
        "romaji":"",
        "moji":"",
        "kanji":"",
        "english":"",
        "answerOption":[
            {
                "id":"tp6_l_1",
                "type":"listening",
                "moji":"本を読むことです"
            },
            {
                "id":"tp6_l_1",
                "type":"listening",
                "moji":"旅行に行くことです"
            },
            {
                "id":"tp6_l_1",
                "type":"listening",
                "moji":"サッカーを見ることです"
            },
            {
                "id":"tp6_l_1",
                "type":"listening",
                "moji":"サッカーをすることです"
            }
        ],
        "audio":"t6_listening_3.mp3"
    }
]

export const reading = [
    {
        "id":"tp6_r_1",
        "type":"reading",
        "moji":"姉のしゅみは料理を作ることです。料理の中で、ケーキが一番上手です。いろいろなケーキをよく作ります。今は、本を買って、仕事が終わってから、毎日家でフランス語の勉強をしています。姉は、フランス語が上手になってから、フランスへ料理の勉強をしに行きたいです。",
        "questionOption":{
            "moji":"Q：どうしてフランス語の勉強をしていますか。",
            "kanji":"Q：どうしてフランス語の勉強をしていますか。"
        },
        "answerOption":[
            {
                "id":"ans_r_5",
                "type":"reading",
                "moji":"ケーキを食べたいですから"
            },
            {
                "id":"ans_r_1",
                "type":"reading",
                "moji":"料理の勉強をしたいですから"
            },
            {
                "id":"ans_r_7",
                "type":"reading",
                "moji":"仕事を休みたいですから"
            },
            {
                "id":"ans_r_8",
                "type":"reading",
                "moji":"フランス語の本が好きですから"
            },
        ],
        "audio":""	
    },
    {
        "id":"tp6_r_2",
        "type":"reading",
        "moji":"私の父はＩＴの会社で働いています。父は背が高くて、やさしい人です。昔は私と姉をいろいろなところへ遊びに連れて行ってくれました。母は高校で英語を教えています。母は料理が上手できれいな人です。いまは日本に住んでいますから、母の料理が食べることができません。",
        "questionOption":{
            "moji":"Q：この人のお母さんの仕事は何ですか。",
            "kanji":"Q：この人のお母さんの仕事は何ですか。"
        },
        "answerOption":[
            {
                "id":"ans_r_5",
                "type":"reading",
                "moji":"会社員	"
            },
            {
                "id":"ans_r_6",
                "type":"reading",
                "moji":"エンジニア		"
            },
            {
                "id":"ans_r_2",
                "type":"reading",
                "moji":"教師	"
            },
            {
                "id":"ans_r_8",
                "type":"reading",
                "moji":"料理を作る人"
            },
        ],
        "audio":""	
    },
    {
        "id":"tp6_r_3",
        "type":"reading",
        "moji":"マリアさんへ\nこんにちは。久しぶりですね。フィリピンは毎日暑いですか。\n日本は今、冬です。とても寒いです。よく雪が降ります。このまえ、初めて雪で遊びました。これから春になります。暖かくなります。花がたくさん咲きますから、公園がきれいになります。とても楽しみです。マリアさんもぜひ日本へ遊びに来てください。\n\nしずか",
        "questionOption":{
            "moji":"Q：今の日本はどれですか。",
            "kanji":"Q：今の日本はどれですか。"
        },
        "answerOption":[
            {
                "id":"ans_r_5",
                "type":"reading",
                "moji":"暑いです"
            },
            {
                "id":"ans_r_3",
                "type":"reading",
                "moji":"よく雪が降ります"
            },
            {
                "id":"ans_r_7",
                "type":"reading",
                "moji":"暖かいです"
            },
            {
                "id":"ans_r_8",
                "type":"reading",
                "moji":"公園がきれいです"
            },
        ],
        "audio":""	
    },
]