export const vocabulary = [
    {
        "id":"tp7_v_1",
        "type":"vocabulary",
        "romaji":"abimasu",
        "moji":"あびます",	
        "english":"to bathe, to shower",
        "audio":"t7_abimasu.mp3"
    },
    {
        "id":"tp7_v_2",
        "type":"vocabulary",
        "romaji":"arukimasu",
        "moji":"あるきます",	
        "english":"to walk",
        "audio":"t7_arukimasu.mp3"
    },
    {
        "id":"tp7_v_3",
        "type":"vocabulary",
        "romaji":"īmasu",
        "moji":"いいます",	
        "english":"to say",
        "audio":"t7_iimasu.mp3"
    },
    {
        "id":"tp7_v_4",
        "type":"vocabulary",
        "romaji":"isogashī",
        "moji":"いそがしい",	
        "english":"busy, irritated",
        "audio":"t7_isogashii.mp3"
    },
    {
        "id":"tp7_v_5",
        "type":"vocabulary",
        "romaji":"uta",
        "moji":"うた",	
        "english":"song",
        "audio":"t7_uta.mp3"
    },
    {
        "id":"tp7_v_6",
        "type":"vocabulary",
        "romaji":"utaimasu",
        "moji":"うたいます",	
        "english":"to sing",
        "audio":"t7_utaimasu.mp3"
    },
    {
        "id":"tp7_v_7",
        "type":"vocabulary",
        "romaji":"umaremasu",
        "moji":"うまれます",	
        "english":"to be born",
        "audio":"t7_umaremasu.mp3"
    },
    {
        "id":"tp7_v_8",
        "type":"vocabulary",
        "romaji":"onaji",
        "moji":"おなじ",	
        "english":"same",
        "audio":"t7_onaji.mp3"
    },
    {
        "id":"tp7_v_9",
        "type":"vocabulary",
        "romaji":"o furo",
        "moji":"おふろ",	
        "english":"Bath",
        "audio":"t7_ofuro.mp3"
    },
    {
        "id":"tp7_v_10",
        "type":"vocabulary",
        "romaji":"o bentō",
        "moji":"おべんとう",	
        "english":"boxed lunch",
        "audio":"t7_obentou.mp3"
    },
    {
        "id":"tp7_v_11",
        "type":"vocabulary",
        "romaji":"ka shimasu",
        "moji":"かします",	
        "english":"to lend/to loan​",
        "audio":"t7_kashimasu.mp3"
    },
    {
        "id":"tp7_v_12",
        "type":"vocabulary",
        "romaji":"kaze",
        "moji":"かぜ",	
        "english":"Wind",
        "audio":"t7_kaze.mp3"
    },
    {
        "id":"tp7_v_13",
        "type":"vocabulary",
        "romaji":"kaze",
        "moji":"かぜ",	
        "english":"a cold",
        "audio":"t7_kaze.mp3"
    },
    {
        "id":"tp7_v_14",
        "type":"vocabulary",
        "romaji":"kado",
        "moji":"かど",	
        "english":"a corner",
        "audio":"t7_kado.mp3"
    },
    {
        "id":"tp7_v_15",
        "type":"vocabulary",
        "romaji":"kawa",
        "moji":"かわ",	
        "english":"River",
        "audio":"t7_kawa.mp3"
    },
    {
        "id":"tp7_v_16",
        "type":"vocabulary",
        "romaji":"gitā",
        "moji":"ギター",	
        "english":"Guitar",
        "audio":"t7_gita.mp3"
    },
    {
        "id":"tp7_v_17",
        "type":"vocabulary",
        "romaji":"kusuri",
        "moji":"くすり",	
        "english":"medicine",
        "audio":"t7_kusuri.mp3"
    },
    {
        "id":"tp7_v_18",
        "type":"vocabulary",
        "romaji":"kō sate n",
        "moji":"こうさてん",	
        "english":"intersection",
        "audio":"t7_kousaten.mp3"
    },
    {
        "id":"tp7_v_19",
        "type":"vocabulary",
        "romaji":"saifu",
        "moji":"さいふ",	
        "english":"Wallet",
        "audio":"t7_saifu.mp3"
    },
    {
        "id":"tp7_v_20",
        "type":"vocabulary",
        "romaji":"jikan",
        "moji":"じかん",	
        "english":"Time",
        "audio":"t7_jikan.mp3"
    },
    {
        "id":"tp7_v_21",
        "type":"vocabulary",
        "romaji":"shawā",
        "moji":"シャワー",	
        "english":"Shower",
        "audio":"t7_shawa.mp3"
    },
    {
        "id":"tp7_v_22",
        "type":"vocabulary",
        "romaji":"sentaku shimasu",
        "moji":"せんたくします",	
        "english":"to launder/to do washing",
        "audio":"t7_sentakushimasu.mp3"
    },
    {
        "id":"tp7_v_23",
        "type":"vocabulary",
        "romaji":"sōji shimasu",
        "moji":"そうじします",	
        "english":"to clean, to sweep",
        "audio":"t7_soujishimasu.mp3"
    },
    {
        "id":"tp7_v_24",
        "type":"vocabulary",
        "romaji":"daijōbu",
        "moji":"だいじょうぶ",	
        "english":"all right",
        "audio":"t7_daijoubu.mp3"
    },
    {
        "id":"tp7_v_25",
        "type":"vocabulary",
        "romaji":"takushī",
        "moji":"タクシー",	
        "english":"taxi",
        "audio":"t7_takushi.mp3"
    },
    {
        "id":"tp7_v_26",
        "type":"vocabulary",
        "romaji":"dandan",
        "moji":"だんだん",	
        "english":"gradually",
        "audio":"t7_dandan.mp3"
    },
    {
        "id":"tp7_v_27",
        "type":"vocabulary",
        "romaji":"chika tetsu",
        "moji":"ちかてつ",	
        "english":"subway",
        "audio":"t7_chikatetsu.mp3"
    },
    {
        "id":"tp7_v_28",
        "type":"vocabulary",
        "romaji":"tsugi",
        "moji":"つぎ",	
        "english":"next",
        "audio":"t7_tsugi.mp3"
    },
    {
        "id":"tp7_v_29",
        "type":"vocabulary",
        "romaji":"dekakemasu",
        "moji":"でかけます",	
        "english":"to go out",
        "audio":"t7_dekakemasu.mp3"
    },
    {
        "id":"tp7_v_30",
        "type":"vocabulary",
        "romaji":"de masu",
        "moji":"でます",	
        "english":"to appear,to leave",
        "audio":"t7_demasu.mp3"
    },
    {
        "id":"tp7_v_31",
        "type":"vocabulary",
        "romaji":"naraimasu",
        "moji":"ならいます",	
        "english":"to learn",
        "audio":"t7_naraimasu.mp3"
    },
    {
        "id":"tp7_v_32",
        "type":"vocabulary",
        "romaji":"noborimasu",
        "moji":"のぼります",	
        "english":"to climb",
        "audio":"t7_noborimasu.mp3"
    },
    {
        "id":"tp7_v_33",
        "type":"vocabulary",
        "romaji":"hairimasu",
        "moji":"はいります",	
        "english":"to enter, to contain",
        "audio":"t7_hairimasu.mp3"
    },
    {
        "id":"tp7_v_34",
        "type":"vocabulary",
        "romaji":"hako",
        "moji":"はこ",	
        "english":"box",
        "audio":"t7_hako.mp3"
    },
    {
        "id":"tp7_v_35",
        "type":"vocabulary",
        "romaji":"ha",
        "moji":"は",	
        "english":"tooth",
        "audio":"t7_ha.mp3"
    },
    {
        "id":"tp7_v_36",
        "type":"vocabulary",
        "romaji":"hashi",
        "moji":"はし",	
        "english":"bridge",
        "audio":"t7_hashi.mp3"
    },
    {
        "id":"tp7_v_37",
        "type":"vocabulary",
        "romaji":"hajimete",
        "moji":"はじめて",	
        "english":"for the first time",
        "audio":"t7_hajimete.mp3"
    },
    {
        "id":"tp7_v_38",
        "type":"vocabulary",
        "romaji":"hashirimasu",
        "moji":"はしります",	
        "english":"to run",
        "audio":"t7_hashirimasu.mp3"
    },
    {
        "id":"tp7_v_39",
        "type":"vocabulary",
        "romaji":"byōin",
        "moji":"びょういん",	
        "english":"hospital",
        "audio":"t7_byouin.mp3"
    },
    {
        "id":"tp7_v_40",
        "type":"vocabulary",
        "romaji":"byōki",
        "moji":"びょうき",	
        "english":"illness",
        "audio":"t7_byouki.mp3"
    },
    {
        "id":"tp7_v_41",
        "type":"vocabulary",
        "romaji":"mada",
        "moji":"まだ",	
        "english":"yet, still",
        "audio":"t7_mada.mp3"
    },
    {
        "id":"tp7_v_42",
        "type":"vocabulary",
        "romaji":"migakimasu",
        "moji":"みがきます",	
        "english":"to brush teeth, to polish",
        "audio":"t7_migakimasu.mp3"
    },
    {
        "id":"tp7_v_43",
        "type":"vocabulary",
        "romaji":"michi",
        "moji":"みち",	
        "english":"street",
        "audio":"t7_michi.mp3"
    },
    {
        "id":"tp7_v_44",
        "type":"vocabulary",
        "romaji":"mō",
        "moji":"もう",	
        "english":"already",
        "audio":"t7_mou.mp3"
    },
    {
        "id":"tp7_v_45",
        "type":"vocabulary",
        "romaji":"yama",
        "moji":"やま",	
        "english":"",
        "audio":"t7_yama.mp3"
    },
    {
        "id":"tp7_v_46",
        "type":"vocabulary",
        "romaji":"renshū shimasu",
        "moji":"れんしゅうします",	
        "english":"to practice",
        "audio":"t7_renshuushimasu.mp3"
    },
    {
        "id":"tp7_v_47",
        "type":"vocabulary",
        "romaji":"watarimasu",
        "moji":"わたります",	
        "english":"to go across",
        "audio":"t7_watarimasu.mp3"
    },
]

export const kanji = [
    {
        "id":"tp7_k_1",
        "type":"kanji",
        "romaji":"karada",
        "moji":"からだ",
        "kanji":"体",
        "english":"body",
        "audio":"body.mp3"
    },
    {
        "id":"tp7_k_2",
        "type":"kanji",
        "romaji":"me",
        "moji":"め",
        "kanji":"目",
        "english":"eye",
        "audio":"eye.mp3"
    },
    {
        "id":"tp7_k_3",
        "type":"kanji",
        "romaji":"kuchi",
        "moji":"くち",
        "kanji":"口",
        "english":"mouth",
        "audio":"mouth.mp3"
    },
    {
        "id":"tp7_k_4",
        "type":"kanji",
        "romaji":"mimi",
        "moji":"みみ",
        "kanji":"耳",
        "english":"ear",
        "audio":"ear.mp3"
    },
    {
        "id":"tp7_k_5",
        "type":"kanji",
        "romaji":"te",
        "moji":"て",
        "kanji":"手",
        "english":"hand",
        "audio":"hand.mp3"
    },
    {
        "id":"tp7_k_6",
        "type":"kanji",
        "romaji":"ashi",
        "moji":"あし",
        "kanji":"足",
        "english":"foot",
        "audio":"foot.mp3"
    },
    {
        "id":"tp7_k_7",
        "type":"kanji",
        "romaji":"chikara",
        "moji":"ちから",
        "kanji":"力",
        "english":"power",
        "audio":"power.mp3"
    },
    {
        "id":"tp7_k_8",
        "type":"kanji",
        "romaji":"ushi",
        "moji":"うし",
        "kanji":"牛",
        "english":"cow",
        "audio":"cow.mp3"
    },
    {
        "id":"tp7_k_9",
        "type":"kanji",
        "romaji":"uma",
        "moji":"うま",
        "kanji":"馬",
        "english":"horse",
        "audio":"horse.mp3"
    },
    {
        "id":"tp7_k_10",
        "type":"kanji",
        "romaji":"sakana",
        "moji":"さかな",
        "kanji":"魚",
        "english":"fish",
        "audio":"fish.mp3"
    },
    {
        "id":"tp7_k_11",
        "type":"kanji",
        "romaji":"kai",
        "moji":"かい",
        "kanji":"貝",
        "english":"shell",
        "audio":"shell.mp3"
    },
    {
        "id":"tp7_k_12",
        "type":"kanji",
        "romaji":"niku",
        "moji":"にく",
        "kanji":"肉",
        "english":"meat",
        "audio":"meat.mp3"
    },
    {
        "id":"tp7_k_13",
        "type":"kanji",
        "romaji":"Shiro",
        "moji":"しろ",
        "kanji":"白",
        "english":"white",
        "audio":"white.mp3"
    },
    {
        "id":"tp7_k_14",
        "type":"kanji",
        "romaji":"kuro",
        "moji":"くろ",
        "kanji":"黒",
        "english":"black",
        "audio":"black.mp3"
    },
    /////// 7
    {
        "id":"tp7_k_15",
        "type":"kanji",
        "romaji":"koku/ kuni",
        "moji":"こく/くに",
        "kanji":"国",
        "english":"country",
        "audio":"country.mp3"
    },
]

export const grammar = [
]

export const listening = [
]

export const reading = [
]