export const vocabulary = [
    {
        "id":"tp5_v_1",
        "type":"vocabulary",
        "moji":"あめ",
        "romaji":"ame",
        "english":"rain",
        "audio":"t5_ame.mp3"
    },
    {
        "id":"tp5_v_2",
        "type":"vocabulary",
        "moji":"あらいます",
        "romaji":"araimasu",
        "english":"to wash",
        "audio":"t5_araimasu.mp3"
    },
    {
        "id":"tp5_v_3",
        "type":"vocabulary",
        "moji":"いす",
        "romaji":"isu",
        "english":"chair",
        "audio":"t5_isu.mp3"
    },
    {
        "id":"tp5_v_4",
        "type":"vocabulary",
        "moji":"いま",
        "romaji":"ima",
        "english":"now",
        "audio":"t5_ima.mp3"
    },
    {
        "id":"tp5_v_5",
        "type":"vocabulary",
        "moji":"いれます",
        "romaji":"iremasu",
        "english":"to put in",
        "audio":"t5_iremasu.mp3"
    },
    {
        "id":"tp5_v_6",
        "type":"vocabulary",
        "moji":"いろいろ",
        "romaji":"iroiro",
        "english":"various",
        "audio":"t5_iroiro.mp3"
    },
    {
        "id":"tp5_v_7",
        "type":"vocabulary",
        "moji":"おきます",
        "romaji":"okimasu",
        "english":"to put",
        "audio":"t5_okimasu.mp3"
    },
    {
        "id":"tp5_v_8",
        "type":"vocabulary",
        "moji":"おさら",
        "romaji":"o sara",
        "english":"plate, dish",
        "audio":"t5_osara.mp3"
    },
    {
        "id":"tp5_v_9",
        "type":"vocabulary",
        "moji":"おしえます",
        "romaji":"oshiemasu",
        "english":"to teach, to tell",
        "audio":"t5_oshiemasu.mp3"
    },
    {
        "id":"tp5_v_10",
        "type":"vocabulary",
        "moji":"おります",
        "romaji":"orimasu",
        "english":"to get off, to descend",
        "audio":"t5_orimasu.mp3"
    },
    {
        "id":"tp5_v_11",
        "type":"vocabulary",
        "moji":"かさ",
        "romaji":"kasa",
        "english":"Umbrella",
        "audio":"t5_kasa.mp3"
    },
    {
        "id":"tp5_v_12",
        "type":"vocabulary",
        "moji":"カップ",
        "romaji":"kappu",
        "english":"Cup",
        "audio":"t5_kappu.mp3"
    },
    {
        "id":"tp5_v_13",
        "type":"vocabulary",
        "moji":"かみ",
        "romaji":"Kami",
        "english":"paper",
        "audio":"t5_kami.mp3"
    },
    {
        "id":"tp5_v_14",
        "type":"vocabulary",
        "moji":"カレンダー",
        "romaji":"karendā",
        "english":"calendar",
        "audio":"t5_karenda.mp3"
    },
    {
        "id":"tp5_v_15",
        "type":"vocabulary",
        "moji":"ぎゅうにく",
        "romaji":"gyūniku",
        "english":"Beef",
        "audio":"t5_gyuuniku.mp3"
    },
    {
        "id":"tp5_v_16",
        "type":"vocabulary",
        "moji":"きらい",
        "romaji":"kirai",
        "english":"Hate",
        "audio":"t5_kirai.mp3"
    },
    {
        "id":"tp5_v_17",
        "type":"vocabulary",
        "moji":"きります",
        "romaji":"kirimasu",
        "english":"to cut",
        "audio":"t5_kirimasu.mp3"
    },
    {
        "id":"tp5_v_18",
        "type":"vocabulary",
        "moji":"くだもの",
        "romaji":"kudamono",
        "english":"Fruit",
        "audio":"t5_kudamono.mp3"
    },
    {
        "id":"tp5_v_19",
        "type":"vocabulary",
        "moji":"くつ",
        "romaji":"kutsu",
        "english":"Shoes",
        "audio":"t5_kutsu.mp3"
    },
    {
        "id":"tp5_v_20",
        "type":"vocabulary",
        "moji":"くつした",
        "romaji":"kutsu shita",
        "english":"Socks",
        "audio":"t5_kutsu shita.mp3"
    },
    {
        "id":"tp5_v_21",
        "type":"vocabulary",
        "moji":"けさ",
        "romaji":"kesa",
        "english":"this morning",
        "audio":"t5_kesa.mp3"
    },
    {
        "id":"tp5_v_22",
        "type":"vocabulary",
        "moji":"コート",
        "romaji":"kōto",
        "english":"coat, tennis court",
        "audio":"t5_kouto.mp3"
    },
    {
        "id":"tp5_v_23",
        "type":"vocabulary",
        "moji":"コップ",
        "romaji":"koppu",
        "english":"a glass",
        "audio":"t5_koppu.mp3"
    },
    {
        "id":"tp5_v_24",
        "type":"vocabulary",
        "moji":"コピーします",
        "romaji":"kopī shimasu",
        "english":"to copy",
        "audio":"t5_kopishimasu.mp3"
    },
    {
        "id":"tp5_v_25",
        "type":"vocabulary",
        "moji":"さかな",
        "romaji":"sakana",
        "english":"Fish",
        "audio":"t5_sakana.mp3"
    },
    {
        "id":"tp5_v_26",
        "type":"vocabulary",
        "moji":"さします",
        "romaji":"sashimasu",
        "english":"to stretch out hands, to raise an umbrella",
        "audio":"t5_sashimasu.mp3"
    },
    {
        "id":"tp5_v_27",
        "type":"vocabulary",
        "moji":"さとう",
        "romaji":"satō",
        "english":"Sugar",
        "audio":"t5_satou.mp3"
    },
    {
        "id":"tp5_v_28",
        "type":"vocabulary",
        "moji":"しお",
        "romaji":"shio",
        "english":"Salt",
        "audio":"t5_shio.mp3"
    },
    {
        "id":"tp5_v_29",
        "type":"vocabulary",
        "moji":"しめます",
        "romaji":"shimemasu",
        "english":"to close something",
        "audio":"t5_shimemasu.mp3"
    },
    {
        "id":"tp5_v_30",
        "type":"vocabulary",
        "moji":"シャツ",
        "romaji":"shatsu",
        "english":"Shirt",
        "audio":"t5_shatsu.mp3"
    },
    {
        "id":"tp5_v_31",
        "type":"vocabulary",
        "moji":"しょうゆ",
        "romaji":"shōyu",
        "english":"soy sauce",
        "audio":"t5_shouyu.mp3"
    },
    {
        "id":"tp5_v_32",
        "type":"vocabulary",
        "moji":"スカート",
        "romaji":"sukāto",
        "english":"Skirt",
        "audio":"t5_sukato.mp3"
    },
    {
        "id":"tp5_v_33",
        "type":"vocabulary",
        "moji":"すき",
        "romaji":"suki",
        "english":"Likeable",
        "audio":"t5_suki.mp3"
    },
    {
        "id":"tp5_v_34",
        "type":"vocabulary",
        "moji":"ズボン",
        "romaji":"zubon",
        "english":"Trousers",
        "audio":"t5_zubon.mp3"
    },
    {
        "id":"tp5_v_35",
        "type":"vocabulary",
        "moji":"すわります",
        "romaji":"suwarimasu",
        "english":"to sit",
        "audio":"t5_suwarimasu.mp3"
    },
    {
        "id":"tp5_v_36",
        "type":"vocabulary",
        "moji":"セーター",
        "romaji":"seitā",
        "english":"sweater, jumper",
        "audio":"t5_seita.mp3"
    },
    {
        "id":"tp5_v_37",
        "type":"vocabulary",
        "moji":"ぜんぶ",
        "romaji":"zenbu",
        "english":"All",
        "audio":"t5_zenbu.mp3"
    },
    {
        "id":"tp5_v_38",
        "type":"vocabulary",
        "moji":"たちます",
        "romaji":"tachimasu",
        "english":"to stand",
        "audio":"t5_tachimasu.mp3"
    },
    {
        "id":"tp5_v_39",
        "type":"vocabulary",
        "moji":"ちょっと",
        "romaji":"chotto",
        "english":"somewhat",
        "audio":"t5_chotto.mp3"
    },
    {
        "id":"tp5_v_40",
        "type":"vocabulary",
        "moji":"つけます",
        "romaji":"tsukemasu",
        "english":"to turn on",
        "audio":"t5_tsukemasu.mp3"
    },
    {
        "id":"tp5_v_41",
        "type":"vocabulary",
        "moji":"でんき",
        "romaji":"denki",
        "english":"electricity, electric light",
        "audio":"t5_denki.mp3"
    },
    {
        "id":"tp5_v_42",
        "type":"vocabulary",
        "moji":"でんわ",
        "romaji":"denwa",
        "english":"telephone",
        "audio":"t5_denwa.mp3"
    },
    {
        "id":"tp5_v_43",
        "type":"vocabulary",
        "moji":"とまります",
        "romaji":"tomarimasu",
        "english":"to come to a halt",
        "audio":"t5_tomarimasu.mp3"
    },
    {
        "id":"tp5_v_44",
        "type":"vocabulary",
        "moji":"とり",
        "romaji":"tori",
        "english":"bird",
        "audio":"t5_tori.mp3"
    },
    {
        "id":"tp5_v_45",
        "type":"vocabulary",
        "moji":"とりにく",
        "romaji":"tori niku",
        "english":"chicken meat",
        "audio":"t5_tori niku.mp3"
    },
    {
        "id":"tp5_v_46",
        "type":"vocabulary",
        "moji":"とります",
        "romaji":"torimasu",
        "english":"to take something",
        "audio":"t5_torimasu.mp3"
    },
    {
        "id":"tp5_v_47",
        "type":"vocabulary",
        "moji":"にく",
        "romaji":"niku",
        "english":"meat",
        "audio":"t5_niku.mp3"
    },
    {
        "id":"tp5_v_48",
        "type":"vocabulary",
        "moji":"ネクタイ",
        "romaji":"nekutai",
        "english":"tie, necktie",
        "audio":"t5_nekutai.mp3"
    },
    {
        "id":"tp5_v_49",
        "type":"vocabulary",
        "moji":"ノート",
        "romaji":"nōto",
        "english":"notebook, exercise book",
        "audio":"t5_nouto.mp3"
    },
    {
        "id":"tp5_v_50",
        "type":"vocabulary",
        "moji":"のります",
        "romaji":"norimasu",
        "english":"to get on, to ride",
        "audio":"t5_norimasu.mp3"
    },
    {
        "id":"tp5_v_51",
        "type":"vocabulary",
        "moji":"はな",
        "romaji":"hana",
        "english":"flower",
        "audio":"t5_hana.mp3"
    },
    {
        "id":"tp5_v_52",
        "type":"vocabulary",
        "moji":"ひきます",
        "romaji":"hikimasu",
        "english":"to play an instrument with strings",
        "audio":"t5_hikimasu.mp3"
    },
    {
        "id":"tp5_v_53",
        "type":"vocabulary",
        "moji":"ふく",
        "romaji":"fuku",
        "english":"clothes",
        "audio":"t5_fuku.mp3"
    },
    {
        "id":"tp5_v_54",
        "type":"vocabulary",
        "moji":"ぶたにく",
        "romaji":"butaniku",
        "english":"pork",
        "audio":"t5_butaniku.mp3"
    },
    {
        "id":"tp5_v_55",
        "type":"vocabulary",
        "moji":"ふります",
        "romaji":"furimasu",
        "english":"to fall, e.g. rain or snow",
        "audio":"t5_furimasu.mp3"
    },
    {
        "id":"tp5_v_56",
        "type":"vocabulary",
        "moji":"ペット",
        "romaji":"petto",
        "english":"pet",
        "audio":"t5_petto.mp3"
    },
    {
        "id":"tp5_v_57",
        "type":"vocabulary",
        "moji":"ぼうし",
        "romaji":"bōshi",
        "english":"hat",
        "audio":"t5_boushi.mp3"
    },
    {
        "id":"tp5_v_58",
        "type":"vocabulary",
        "moji":"ほしい",
        "romaji":"hoshī",
        "english":"want",
        "audio":"t5_hoshi.mp3"
    },
    {
        "id":"tp5_v_59",
        "type":"vocabulary",
        "moji":"まがります",
        "romaji":"magarimasu",
        "english":"to turn, to bend",
        "audio":"t5_magarimasu.mp3"
    },
    {
        "id":"tp5_v_60",
        "type":"vocabulary",
        "moji":"また",
        "romaji":"mata",
        "english":"again, and",
        "audio":"t5_mata.mp3"
    },
    {
        "id":"tp5_v_61",
        "type":"vocabulary",
        "moji":"まちます",
        "romaji":"machimas",
        "english":"to wait",
        "audio":"t5_machimas.mp3"
    },
    {
        "id":"tp5_v_62",
        "type":"vocabulary",
        "moji":"まっすぐ",
        "romaji":"massugu",
        "english":"straight ahead, direct",
        "audio":"t5_massugu.mp3"
    },
    {
        "id":"tp5_v_63",
        "type":"vocabulary",
        "moji":"みせます",
        "romaji":"misemasu",
        "english":"to show",
        "audio":"t5_misemasu.mp3"
    },
    {
        "id":"tp5_v_64",
        "type":"vocabulary",
        "moji":"めがね",
        "romaji":"megane",
        "english":"glasses",
        "audio":"t5_megane.mp3"
    },
    {
        "id":"tp5_v_65",
        "type":"vocabulary",
        "moji":"もっと",
        "romaji":"motto",
        "english":"more",
        "audio":"t5_motto.mp3"
    },
    {
        "id":"tp5_v_66",
        "type":"vocabulary",
        "moji":"やすみます",
        "romaji":"yasumimasu",
        "english":"to rest",
        "audio":"t5_yasumimasu.mp3"
    },
    {
        "id":"tp5_v_67",
        "type":"vocabulary",
        "moji":"やります",
        "romaji":"yarimasu",
        "english":"to do",
        "audio":"t5_yarimasu.mp3"
    },
    {
        "id":"tp5_v_68",
        "type":"vocabulary",
        "moji":"ゆっくり",
        "romaji":"yukkuri",
        "english":"slowly",
        "audio":"t5_yukkuri.mp3"
    },
    {
        "id":"tp5_v_69",
        "type":"vocabulary",
        "moji":"よびます",
        "romaji":"yobimasu",
        "english":"to call out, to invite",
        "audio":"t5_yobimasu.mp3"
    },
]

export const kanji = [
    {
        "id":"tp5_k_1",
        "type":"kanji",
        "romaji":"eki",
        "moji":"えき",
        "kanji":"駅",
        "english":"station",
        "audio":"station.mp3"
    },
    {
        "id":"tp5_k_2",
        "type":"kanji",
        "romaji":"mise",
        "moji":"みせ",
        "kanji":"店",
        "english":"shop",
        "audio":"shop.mp3"
    },
    {
        "id":"tp5_k_3",
        "type":"kanji",
        "romaji":"ue",
        "moji":"うえ",
        "kanji":"上",
        "english":"above",
        "audio":"above.mp3"
    },
    {
        "id":"tp5_k_4",
        "type":"kanji",
        "romaji":"shita",
        "moji":"した",
        "kanji":"下",
        "english":"under",
        "audio":"under.mp3"
    },
    {
        "id":"tp5_k_5",
        "type":"kanji",
        "romaji":"migi",
        "moji":"みぎ",
        "kanji":"右",
        "english":"right",
        "audio":"right.mp3"
    },
    {
        "id":"tp5_k_6",
        "type":"kanji",
        "romaji":"hidari",
        "moji":"ひだり",
        "kanji":"左",
        "english":"left",
        "audio":"left.mp3"
    },
    {
        "id":"tp5_k_7",
        "type":"kanji",
        "romaji":"zen/ mae",
        "moji":"ぜん/まえ",
        "kanji":"前",
        "english":"front",
        "audio":"front.mp3"
    },
    {
        "id":"tp5_k_8",
        "type":"kanji",
        "romaji":"go/ ushiro, ato",
        "moji":"ご/うしろ、あと",
        "kanji":"後",
        "english":"back",
        "audio":"back.mp3"
    },
    {
        "id":"tp5_k_9",
        "type":"kanji",
        "romaji":"chū/ Naka",
        "moji":"ちゅう/なか",
        "kanji":"中",
        "english":"inside",
        "audio":"inside.mp3"
    },
    {
        "id":"tp5_k_10",
        "type":"kanji",
        "romaji":"gai/ soto",
        "moji":"がい/そと",
        "kanji":"外",
        "english":"outside",
        "audio":"outside.mp3"
    },
    {
        "id":"tp5_k_11",
        "type":"kanji",
        "romaji":"kita",
        "moji":"きた",
        "kanji":"北",
        "english":"north",
        "audio":"north.mp3"
    },
    {
        "id":"tp5_k_12",
        "type":"kanji",
        "romaji":"minami",
        "moji":"みなみ",
        "kanji":"南",
        "english":"south",
        "audio":"south.mp3"
    },
    {
        "id":"tp5_k_13",
        "type":"kanji",
        "romaji":"higashi",
        "moji":"ひがし",
        "kanji":"東",
        "english":"east",
        "audio":"east.mp3"
    },
    {
        "id":"tp5_k_14",
        "type":"kanji",
        "romaji":"ni shi",
        "moji":"にし",
        "kanji":"西",
        "english":"west",
        "audio":"west.mp3"
    },
    /////// 5
    {
        "id":"tp5_k_15",
        "type":"kanji",
        "romaji":"hon",
        "moji":"ほん",
        "kanji":"本",
        "english":"book",
        "audio":"book.mp3"
    },
]

export const grammar = [
]

export const listening = [
]

export const reading = [
]