export const vocabulary = [
    {
        "id":"tp8_v_1",
        "type":"vocabulary",
        "romaji":"aki",
        "moji":"あき",	
        "english":"fall",
        "audio":"t8_aki.mp3"
    },
    {
        "id":"tp8_v_2",
        "type":"vocabulary",
        "romaji":"imi",
        "moji":"いみ",	
        "english":"meaning",
        "audio":"t8_imi.mp3"
    },
    {
        "id":"tp8_v_3",
        "type":"vocabulary",
        "romaji":"iriguchi",
        "moji":"いりぐち",	
        "english":"entrance",
        "audio":"t8_iriguchi.mp3"
    },
    {
        "id":"tp8_v_4",
        "type":"vocabulary",
        "romaji":"urimasu",
        "moji":"うります",	
        "english":"to sell",
        "audio":"t8_urimasu.mp3"
    },
    {
        "id":"tp8_v_5",
        "type":"vocabulary",
        "romaji":"oshimasu",
        "moji":"おします",	
        "english":"to push, to stamp something",
        "audio":"t8_oshimasu.mp3"
    },
    {
        "id":"tp8_v_6",
        "type":"vocabulary",
        "romaji":"oboemasu",
        "moji":"おぼえます",	
        "english":"to remember",
        "audio":"t8_oboemasu.mp3"
    },
    {
        "id":"tp8_v_7",
        "type":"vocabulary",
        "romaji":"oyogimasu",
        "moji":"およぎます",	
        "english":"to swim",
        "audio":"t8_oyogimasu.mp3"
    },
    {
        "id":"tp8_v_8",
        "type":"vocabulary",
        "romaji":"kagi",
        "moji":"かぎ",	
        "english":"Key",
        "audio":"t8_kagi.mp3"
    },
    {
        "id":"tp8_v_9",
        "type":"vocabulary",
        "romaji":"kita",
        "moji":"きた",	
        "english":"north",
        "audio":"t8_kita.mp3"
    },
    {
        "id":"tp8_v_10",
        "type":"vocabulary",
        "romaji":"genkan",
        "moji":"げんかん",	
        "english":"entry hall",
        "audio":"t8_genkan.mp3"
    },
    {
        "id":"tp8_v_11",
        "type":"vocabulary",
        "romaji":"kōban",
        "moji":"こうばん",	
        "english":"police box",
        "audio":"t8_kouban.mp3"
    },
    {
        "id":"tp8_v_12",
        "type":"vocabulary",
        "romaji":"koe",
        "moji":"こえ",	
        "english":"Voice",
        "audio":"t8_koe.mp3"
    },
    {
        "id":"tp8_v_13",
        "type":"vocabulary",
        "romaji":"jibun",
        "moji":"じぶん",	
        "english":"Oneself",
        "audio":"t8_jibun.mp3"
    },
    {
        "id":"tp8_v_14",
        "type":"vocabulary",
        "romaji":"suguni",
        "moji":"すぐに",	
        "english":"Instantly",
        "audio":"t8_suguni.mp3"
    },
    {
        "id":"tp8_v_15",
        "type":"vocabulary",
        "romaji":"dake",
        "moji":"だけ",	
        "english":"only",
        "audio":"t8_dake.mp3"
    },
    {
        "id":"tp8_v_16",
        "type":"vocabulary",
        "romaji":"dashimasu",
        "moji":"だします",	
        "english":"to put out",
        "audio":"t8_dashimasu.mp3"
    },
    {
        "id":"tp8_v_17",
        "type":"vocabulary",
        "romaji":"tabun",
        "moji":"たぶん",	
        "english":"probably",
        "audio":"t8_tabun.mp3"
    },
    {
        "id":"tp8_v_18",
        "type":"vocabulary",
        "romaji":"chōdo",
        "moji":"ちょうど",	
        "english":"exactly",
        "audio":"t8_choudo.mp3"
    },
    {
        "id":"tp8_v_19",
        "type":"vocabulary",
        "romaji":"tsukaremasu",
        "moji":"つかれます",	
        "english":"to get tired",
        "audio":"t8_tsukaremasu.mp3"
    },
    {
        "id":"tp8_v_20",
        "type":"vocabulary",
        "romaji":"deguchi",
        "moji":"でぐち",	
        "english":"exit",
        "audio":"t8_deguchi.mp3"
    },
    {
        "id":"tp8_v_21",
        "type":"vocabulary",
        "romaji":"demo",
        "moji":"でも",	
        "english":"but",
        "audio":"t8_demo.mp3"
    },
    {
        "id":"tp8_v_22",
        "type":"vocabulary",
        "romaji":"dōbutsu",
        "moji":"どうぶつ",	
        "english":"animal",
        "audio":"t8_doubutsu.mp3"
    },
    {
        "id":"tp8_v_23",
        "type":"vocabulary",
        "romaji":"Natsu",
        "moji":"なつ",	
        "english":"summer",
        "audio":"t8_Natsu.mp3"
    },
    {
        "id":"tp8_v_24",
        "type":"vocabulary",
        "romaji":"nishi",
        "moji":"にし",	
        "english":"west",
        "audio":"t8_nishi.mp3"
    },
    {
        "id":"tp8_v_25",
        "type":"vocabulary",
        "romaji":"nimotsu",
        "moji":"にもつ",	
        "english":"luggage",
        "audio":"t8_nimotsu.mp3"
    },
    {
        "id":"tp8_v_26",
        "type":"vocabulary",
        "romaji":"nugimasu",
        "moji":"ぬぎます",	
        "english":"to take off clothes",
        "audio":"t8_nugimasu.mp3"
    },
    {
        "id":"tp8_v_27",
        "type":"vocabulary",
        "romaji":"hakimasu",
        "moji":"はきます",	
        "english":"to wear, to put on trousers",
        "audio":"t8_hakimasu.mp3"
    },
    {
        "id":"tp8_v_28",
        "type":"vocabulary",
        "romaji":"hajime",
        "moji":"はじめ",	
        "english":"beginning",
        "audio":"t8_hajime.mp3"
    },
    {
        "id":"tp8_v_29",
        "type":"vocabulary",
        "romaji":"hanashi",
        "moji":"はなし",	
        "english":"talk, story",
        "audio":"t8_hanashi.mp3"
    },
    {
        "id":"tp8_v_30",
        "type":"vocabulary",
        "romaji":"haru",
        "moji":"はる",	
        "english":"spring",
        "audio":"t8_haru.mp3"
    },
    {
        "id":"tp8_v_31",
        "type":"vocabulary",
        "romaji":"hanbun",
        "moji":"はんぶん",	
        "english":"half minute",
        "audio":"t8_hanbun.mp3"
    },
    {
        "id":"tp8_v_32",
        "type":"vocabulary",
        "romaji":"higashi",
        "moji":"ひがし",	
        "english":"east",
        "audio":"t8_higashi.mp3"
    },
    {
        "id":"tp8_v_33",
        "type":"vocabulary",
        "romaji":"hoka",
        "moji":"ほか",	
        "english":"other, the rest",
        "audio":"t8_hoka.mp3"
    },
    {
        "id":"tp8_v_34",
        "type":"vocabulary",
        "romaji":"poketto",
        "moji":"ポケット",	
        "english":"pocket",
        "audio":"t8_poketto.mp3"
    },
    {
        "id":"tp8_v_35",
        "type":"vocabulary",
        "romaji":"botan",
        "moji":"ボタン",	
        "english":"button",
        "audio":"t8_botan.mp3"
    },
    {
        "id":"tp8_v_36",
        "type":"vocabulary",
        "romaji":"hontō",
        "moji":"ほんとう",	
        "english":"truth",
        "audio":"t8_hontou.mp3"
    },
    {
        "id":"tp8_v_37",
        "type":"vocabulary",
        "romaji":"minami",
        "moji":"みなみ",	
        "english":"south",
        "audio":"t8_minami.mp3"
    },
    {
        "id":"tp8_v_38",
        "type":"vocabulary",
        "romaji":"mono",
        "moji":"もの",	
        "english":"thing",
        "audio":"t8_mono.mp3"
    },
    {
        "id":"tp8_v_39",
        "type":"vocabulary",
        "romaji":"wasuremasu",
        "moji":"わすれます",	
        "english":"to forget",
        "audio":"t8_wasuremasu.mp3"
    },
]

export const kanji = [
    {
        "id":"tp8_k_1",
        "type":"kanji",
        "romaji":"ei",
        "moji":"えい",
        "kanji":"英",
        "english":"English",
        "audio":"English.mp3"
    },
    {
        "id":"tp8_k_2",
        "type":"kanji",
        "romaji":"go",
        "moji":"ご",
        "kanji":"語",
        "english":"word, language",
        "audio":"word, language.mp3"
    },
    {
        "id":"tp8_k_3",
        "type":"kanji",
        "romaji":"ten",
        "moji":"てん",
        "kanji":"天",
        "english":"heaven",
        "audio":"heaven.mp3"
    },
    {
        "id":"tp8_k_4",
        "type":"kanji",
        "romaji":"ki",
        "moji":"き",
        "kanji":"気",
        "english":"spirit",
        "audio":"spirit.mp3"
    },
    {
        "id":"tp8_k_5",
        "type":"kanji",
        "romaji":"ame",
        "moji":"あめ",
        "kanji":"雨",
        "english":"rain",
        "audio":"rain.mp3"
    },
    {
        "id":"tp8_k_6",
        "type":"kanji",
        "romaji":"o na",
        "moji":"おな",
        "kanji":"同",
        "english":"same",
        "audio":"same.mp3"
    },
    {
        "id":"tp8_k_7",
        "type":"kanji",
        "romaji":"tsuku",
        "moji":"つく",
        "kanji":"作",
        "english":"to make",
        "audio":"to make.mp3"
    },
    {
        "id":"tp8_k_8",
        "type":"kanji",
        "romaji":"mo",
        "moji":"も",
        "kanji":"持",
        "english":"to hold",
        "audio":"to hold.mp3"
    },
    {
        "id":"tp8_k_9",
        "type":"kanji",
        "romaji":"ma",
        "moji":"ま",
        "kanji":"待",
        "english":"to wait",
        "audio":"to wait.mp3"
    },
    {
        "id":"tp8_k_10",
        "type":"kanji",
        "romaji":"no",
        "moji":"の",
        "kanji":"乗",
        "english":"to get on",
        "audio":"to get on.mp3"
    },
    {
        "id":"tp8_k_11",
        "type":"kanji",
        "romaji":"michi",
        "moji":"みち",
        "kanji":"道",
        "english":"road",
        "audio":"road.mp3"
    },
    {
        "id":"tp8_k_12",
        "type":"kanji",
        "romaji":"mono",
        "moji":"もの",
        "kanji":"物",
        "english":"thing",
        "audio":"thing.mp3"
    },
    {
        "id":"tp8_k_13",
        "type":"kanji",
        "romaji":"de n",
        "moji":"でん",
        "kanji":"電",
        "english":"electricity",
        "audio":"electricity.mp3"
    },
    {
        "id":"tp8_k_14",
        "type":"kanji",
        "romaji":"kan/ aida",
        "moji":"かん/あいだ",
        "kanji":"間",
        "english":"between",
        "audio":"between.mp3"
    },
    /////// 8
    {
        "id":"tp8_k_15",
        "type":"kanji",
        "romaji":"go",
        "moji":"ご",
        "kanji":"午",
        "english":"noon",
        "audio":"noon.mp3"
    }
]

export const grammar = [
]

export const listening = [
]

export const reading = [
]