export const vocabulary = [
    {
        "id":"tp8_v_1",
        "type":"vocabulary",
        "romaji":"aki",
        "moji":"あき",	
        "english":"fall",
        "audio":"t8_aki.mp3"
    },
    {
        "id":"tp8_v_2",
        "type":"vocabulary",
        "romaji":"imi",
        "moji":"いみ",	
        "english":"meaning",
        "audio":"t8_imi.mp3"
    },
    {
        "id":"tp8_v_3",
        "type":"vocabulary",
        "romaji":"iriguchi",
        "moji":"いりぐち",	
        "english":"entrance",
        "audio":"t8_iriguchi.mp3"
    },
    {
        "id":"tp8_v_4",
        "type":"vocabulary",
        "romaji":"urimasu",
        "moji":"うります",	
        "english":"to sell",
        "audio":"t8_urimasu.mp3"
    },
    {
        "id":"tp8_v_5",
        "type":"vocabulary",
        "romaji":"oshimasu",
        "moji":"おします",	
        "english":"to push, to stamp something",
        "audio":"t8_oshimasu.mp3"
    },
    {
        "id":"tp8_v_6",
        "type":"vocabulary",
        "romaji":"oboemasu",
        "moji":"おぼえます",	
        "english":"to remember",
        "audio":"t8_oboemasu.mp3"
    },
    {
        "id":"tp8_v_7",
        "type":"vocabulary",
        "romaji":"oyogimasu",
        "moji":"およぎます",	
        "english":"to swim",
        "audio":"t8_oyogimasu.mp3"
    },
    {
        "id":"tp8_v_8",
        "type":"vocabulary",
        "romaji":"kagi",
        "moji":"かぎ",	
        "english":"Key",
        "audio":"t8_kagi.mp3"
    },
    {
        "id":"tp8_v_9",
        "type":"vocabulary",
        "romaji":"kita",
        "moji":"きた",	
        "english":"north",
        "audio":"t8_kita.mp3"
    },
    {
        "id":"tp8_v_10",
        "type":"vocabulary",
        "romaji":"genkan",
        "moji":"げんかん",	
        "english":"entry hall",
        "audio":"t8_genkan.mp3"
    },
    {
        "id":"tp8_v_11",
        "type":"vocabulary",
        "romaji":"kōban",
        "moji":"こうばん",	
        "english":"police box",
        "audio":"t8_kouban.mp3"
    },
    {
        "id":"tp8_v_12",
        "type":"vocabulary",
        "romaji":"koe",
        "moji":"こえ",	
        "english":"Voice",
        "audio":"t8_koe.mp3"
    },
    {
        "id":"tp8_v_13",
        "type":"vocabulary",
        "romaji":"jibun",
        "moji":"じぶん",	
        "english":"Oneself",
        "audio":"t8_jibun.mp3"
    },
    {
        "id":"tp8_v_14",
        "type":"vocabulary",
        "romaji":"suguni",
        "moji":"すぐに",	
        "english":"Instantly",
        "audio":"t8_suguni.mp3"
    },
    {
        "id":"tp8_v_15",
        "type":"vocabulary",
        "romaji":"dake",
        "moji":"だけ",	
        "english":"only",
        "audio":"t8_dake.mp3"
    },
    {
        "id":"tp8_v_16",
        "type":"vocabulary",
        "romaji":"dashimasu",
        "moji":"だします",	
        "english":"to put out",
        "audio":"t8_dashimasu.mp3"
    },
    {
        "id":"tp8_v_17",
        "type":"vocabulary",
        "romaji":"tabun",
        "moji":"たぶん",	
        "english":"probably",
        "audio":"t8_tabun.mp3"
    },
    {
        "id":"tp8_v_18",
        "type":"vocabulary",
        "romaji":"chōdo",
        "moji":"ちょうど",	
        "english":"exactly",
        "audio":"t8_choudo.mp3"
    },
    {
        "id":"tp8_v_19",
        "type":"vocabulary",
        "romaji":"tsukaremasu",
        "moji":"つかれます",	
        "english":"to get tired",
        "audio":"t8_tsukaremasu.mp3"
    },
    {
        "id":"tp8_v_20",
        "type":"vocabulary",
        "romaji":"deguchi",
        "moji":"でぐち",	
        "english":"exit",
        "audio":"t8_deguchi.mp3"
    },
    {
        "id":"tp8_v_21",
        "type":"vocabulary",
        "romaji":"demo",
        "moji":"でも",	
        "english":"but",
        "audio":"t8_demo.mp3"
    },
    {
        "id":"tp8_v_22",
        "type":"vocabulary",
        "romaji":"dōbutsu",
        "moji":"どうぶつ",	
        "english":"animal",
        "audio":"t8_doubutsu.mp3"
    },
    {
        "id":"tp8_v_23",
        "type":"vocabulary",
        "romaji":"Natsu",
        "moji":"なつ",	
        "english":"summer",
        "audio":"t8_Natsu.mp3"
    },
    {
        "id":"tp8_v_24",
        "type":"vocabulary",
        "romaji":"nishi",
        "moji":"にし",	
        "english":"west",
        "audio":"t8_nishi.mp3"
    },
    {
        "id":"tp8_v_25",
        "type":"vocabulary",
        "romaji":"nimotsu",
        "moji":"にもつ",	
        "english":"luggage",
        "audio":"t8_nimotsu.mp3"
    },
    {
        "id":"tp8_v_26",
        "type":"vocabulary",
        "romaji":"nugimasu",
        "moji":"ぬぎます",	
        "english":"to take off clothes",
        "audio":"t8_nugimasu.mp3"
    },
    {
        "id":"tp8_v_27",
        "type":"vocabulary",
        "romaji":"hakimasu",
        "moji":"はきます",	
        "english":"to wear, to put on trousers",
        "audio":"t8_hakimasu.mp3"
    },
    {
        "id":"tp8_v_28",
        "type":"vocabulary",
        "romaji":"hajime",
        "moji":"はじめ",	
        "english":"beginning",
        "audio":"t8_hajime.mp3"
    },
    {
        "id":"tp8_v_29",
        "type":"vocabulary",
        "romaji":"hanashi",
        "moji":"はなし",	
        "english":"talk, story",
        "audio":"t8_hanashi.mp3"
    },
    {
        "id":"tp8_v_30",
        "type":"vocabulary",
        "romaji":"haru",
        "moji":"はる",	
        "english":"spring",
        "audio":"t8_haru.mp3"
    },
    {
        "id":"tp8_v_31",
        "type":"vocabulary",
        "romaji":"hanbun",
        "moji":"はんぶん",	
        "english":"half minute",
        "audio":"t8_hanbun.mp3"
    },
    {
        "id":"tp8_v_32",
        "type":"vocabulary",
        "romaji":"higashi",
        "moji":"ひがし",	
        "english":"east",
        "audio":"t8_higashi.mp3"
    },
    {
        "id":"tp8_v_33",
        "type":"vocabulary",
        "romaji":"hoka",
        "moji":"ほか",	
        "english":"other, the rest",
        "audio":"t8_hoka.mp3"
    },
    {
        "id":"tp8_v_34",
        "type":"vocabulary",
        "romaji":"poketto",
        "moji":"ポケット",	
        "english":"pocket",
        "audio":"t8_poketto.mp3"
    },
    {
        "id":"tp8_v_35",
        "type":"vocabulary",
        "romaji":"botan",
        "moji":"ボタン",	
        "english":"button",
        "audio":"t8_botan.mp3"
    },
    {
        "id":"tp8_v_36",
        "type":"vocabulary",
        "romaji":"hontō",
        "moji":"ほんとう",	
        "english":"truth",
        "audio":"t8_hontou.mp3"
    },
    {
        "id":"tp8_v_37",
        "type":"vocabulary",
        "romaji":"minami",
        "moji":"みなみ",	
        "english":"south",
        "audio":"t8_minami.mp3"
    },
    {
        "id":"tp8_v_38",
        "type":"vocabulary",
        "romaji":"mono",
        "moji":"もの",	
        "english":"thing",
        "audio":"t8_mono.mp3"
    },
    {
        "id":"tp8_v_39",
        "type":"vocabulary",
        "romaji":"wasuremasu",
        "moji":"わすれます",	
        "english":"to forget",
        "audio":"t8_wasuremasu.mp3"
    },
]

export const kanji = [
    {
        "id":"tp8_k_1",
        "type":"kanji",
        "romaji":"ei",
        "moji":"えい",
        "kanji":"英",
        "english":"English",
        "audio":"t8_ei.mp3"
    },
    {
        "id":"tp8_k_2",
        "type":"kanji",
        "romaji":"go",
        "moji":"ご",
        "kanji":"語",
        "english":"word, language",
        "audio":"t8_go.mp3"
    },
    {
        "id":"tp8_k_3",
        "type":"kanji",
        "romaji":"ten",
        "moji":"てん",
        "kanji":"天",
        "english":"heaven",
        "audio":"t8_ten.mp3"
    },
    {
        "id":"tp8_k_4",
        "type":"kanji",
        "romaji":"ki",
        "moji":"き",
        "kanji":"気",
        "english":"spirit",
        "audio":"t8_ki.mp3"
    },
    {
        "id":"tp8_k_5",
        "type":"kanji",
        "romaji":"ame",
        "moji":"あめ",
        "kanji":"雨",
        "english":"rain",
        "audio":"t8_ame.mp3"
    },
    {
        "id":"tp8_k_6",
        "type":"kanji",
        "romaji":"o na",
        "moji":"おな",
        "kanji":"同",
        "english":"same",
        "audio":"t8_ona.mp3"
    },
    {
        "id":"tp8_k_7",
        "type":"kanji",
        "romaji":"tsuku",
        "moji":"つく",
        "kanji":"作",
        "english":"to make",
        "audio":"t8_tsuku.mp3"
    },
    {
        "id":"tp8_k_8",
        "type":"kanji",
        "romaji":"mo",
        "moji":"も",
        "kanji":"持",
        "english":"to hold",
        "audio":"t8_mo.mp3"
    },
    {
        "id":"tp8_k_9",
        "type":"kanji",
        "romaji":"ma",
        "moji":"ま",
        "kanji":"待",
        "english":"to wait",
        "audio":"t8_ma.mp3"
    },
    {
        "id":"tp8_k_10",
        "type":"kanji",
        "romaji":"no",
        "moji":"の",
        "kanji":"乗",
        "english":"to get on",
        "audio":""
    },
    {
        "id":"tp8_k_11",
        "type":"kanji",
        "romaji":"michi",
        "moji":"みち",
        "kanji":"道",
        "english":"road",
        "audio":"t8_michi.mp3"
    },
    {
        "id":"tp8_k_12",
        "type":"kanji",
        "romaji":"mono",
        "moji":"もの",
        "kanji":"物",
        "english":"thing",
        "audio":"t8_mono_k.mp3"
    },
    {
        "id":"tp8_k_13",
        "type":"kanji",
        "romaji":"den",
        "moji":"でん",
        "kanji":"電",
        "english":"electricity",
        "audio":"t8_den.mp3"
    },
    {
        "id":"tp8_k_14",
        "type":"kanji",
        "romaji":"kan/ aida",
        "moji":"かん/あいだ",
        "kanji":"間",
        "english":"between",
        "audio":"t8_kan_aida.mp3"
    },
    {
        "id":"tp8_k_15",
        "type":"kanji",
        "romaji":"go",
        "moji":"ご",
        "kanji":"午",
        "english":"noon",
        "audio":"t8_go_noon.mp3"
    }
]

export const grammar = [
]

export const listening = [
    {
        "id":"tp8_l_1",
        "type":"listening",
        "romaji":"晩ご飯のあと",
        "moji":"晩ご飯のあと",
        "kanji":"晩ご飯のあと",
        "english":"晩ご飯のあと",
        "answerOption":[
            {
                "id":"tp8_l_2",
                "type":"listening",
                "moji":"朝ご飯の前"
            },
            {
                "id":"tp8_l_1",
                "type":"listening",
                "moji":"晩ご飯のあと"
            },
            {
                "id":"tp8_l_3",
                "type":"listening",
                "moji":"昼ごはんのあと"
            },
            {
                "id":"tp8_l_4",
                "type":"listening",
                "moji":"寝る前"
            }
        ],
        "audio":"t8_listening_1.mp3"
    },
    {
        "id":"tp8_l_2",
        "type":"listening",
        "romaji":"お酒を飲みます",
        "moji":"お酒を飲みます",
        "kanji":"お酒を飲みます",
        "english":"お酒を飲みます",
        "answerOption":[
            {
                "id":"tp8_l_1",
                "type":"listening",
                "moji":"テストをします"
            },
            {
                "id":"tp8_l_3",
                "type":"listening",
                "moji":"勉強します"
            },
            {
                "id":"tp8_l_2",
                "type":"listening",
                "moji":"お酒を飲みます"
            },
            {
                "id":"tp8_l_4",
                "type":"listening",
                "moji":"お店に電話します"
            }
        ],
        "audio":"t8_listening_2.mp3"
    },
    {
        "id":"tp8_l_3",
        "type":"listening",
        "romaji":"イギリス",
        "moji":"イギリス",
        "kanji":"イギリス",
        "english":"イギリス",
        "answerOption":[
            {
                "id":"tp8_l_1",
                "type":"listening",
                "moji":"日本"
            },
            {
                "id":"tp8_l_3",
                "type":"listening",
                "moji":"イギリス"
            },
            {
                "id":"tp8_l_2",
                "type":"listening",
                "moji":"アメリカ"
            },
            {
                "id":"tp8_l_4",
                "type":"listening",
                "moji":"中国"
            }
        ],
        "audio":"t8_listening_3.mp3"
    }
]

export const reading = [
    {
        "id":"tp8_r_1",
        "type":"reading",
        "moji":"私は5年前に日本へ来ました。今は日本のことがわかりますが、初めはわかりませんでした。私の国では、ごはんをもって食べてはいけません。スプーンを使って、スープを飲まなければなりません。食べる前に「いただきます」など、何も言わなくてもいいです。でも、日本はそうじゃありません。初め、私はそれがわかりませんでしたから、「どうやってみそしるを飲みますか」と日本人の友だちに聞きました。",
        "questionOption":{
            "moji":"Q：どうして「どうやってみそしるを飲みますか」と日本人の友だちに聞きましたか。",
            "kanji":"Q：どうして「どうやってみそしるを飲みますか」と日本人の友だちに聞きましたか。"
        },
        "answerOption":[
            {
                "id":"ans_r_5",
                "type":"reading",
                "moji":"日本のことを知りたかったからです"
            },
            {
                "id":"ans_r_6",
                "type":"reading",
                "moji":"わたしの国ではごはんをもって食べなければならないからです"
            },
            {
                "id":"ans_r_1",
                "type":"reading",
                "moji":"スプーンがなかったからです "
            },
            {
                "id":"ans_r_8",
                "type":"reading",
                "moji":"日本人の友だちと話したかったからです"
            },
        ],
        "audio":""	
    },
    {
        "id":"tp8_r_2",
        "type":"reading",
        "moji":"わたしは疲れた時、よく友だちとビールを飲みます。ビールをたくさん飲んではいけません。ビールを飲んだ後、車の運転をしてはいけません。危ないです。でも、ビールは「いいこと」もあります。仕事で大変なことがあったとき、それを忘れます。ビールを飲みながら、友だちといろいろな話ができます。寝る前に飲んだ時、朝までよく寝ることができます。体にもいいです。体があたたかくなります。日本では、20歳になった後で、ビールを飲んでもいいです。私は、10年後、自分の子どもとビールを飲みたいです。",
        "questionOption":{
            "moji":"Q：ビールの「いいこと」は何ですか。",
            "kanji":"Q：ビールの「いいこと」は何ですか。"
        },
        "answerOption":[
            {
                "id":"ans_r_5",
                "type":"reading",
                "moji":""
            },
            {
                "id":"ans_r_2",
                "type":"reading",
                "moji":"車の運転が上手になること　2．仕事で大変だったことを忘れること　"
            },
            {
                "id":"ans_r_7",
                "type":"reading",
                "moji":"寝る前に友だちといろいろな話ができること "
            },
            {
                "id":"ans_r_8",
                "type":"reading",
                "moji":"子どももいっしょに飲むこと "
            },
        ],
        "audio":""	
    },
    {
        "id":"tp8_r_3",
        "type":"reading",
        "moji":"これは去年海へ行った時に撮った写真です。私の左にいて、赤いぼうしをかぶっている人は私の姉です。姉のとなりに立っている人は、父です。その前に犬と座っている男の子は、私の子どもです。姉の前に座っている人は、私の夫の弟です。私の右でかばんを持っている人は、私の母です。母の後ろにいる人は、私の夫です。これが私の家族です。",
        "questionOption":{
            "moji":"Q：私はどこにいますか。",
            "kanji":"Q：私はどこにいますか。"
        },
        "answerOption":[
            {
                "id":"ans_r_5",
                "type":"reading",
                "moji":""
            },
            {
                "id":"ans_r_6",
                "type":"reading",
                "moji":"姉の左　2．父と夫の前　"
            },
            {
                "id":"ans_r_7",
                "type":"reading",
                "moji":"子どもと姉の後ろ "
            },
            {
                "id":"ans_r_3",
                "type":"reading",
                "moji":"姉と母の間"
            },
        ],
        "audio":""	
    },
]