export const vocabulary = [
    {
        "id":"tp2_v_1",
        "type":"vocabulary",
        "romaji":"asa",
        "moji":"あさ",
        "english":"morning",
        "audio":"t2_asa.mp3"
    },
    {
        "id":"tp2_v_2",
        "type":"vocabulary",
        "romaji":"asagohan",
        "moji":"あさごはん",
        "english":"breakfast",
        "audio":"t2_asagohan.mp3"
    },
    {
        "id":"tp2_v_3",
        "type":"vocabulary",
        "romaji":"ashita",
        "moji":"あした",
        "english":"tomorrow",
        "audio":"t2_ashita.mp3"
    },
    {
        "id":"tp2_v_4",
        "type":"vocabulary",
        "romaji":"ikimasu",
        "moji":"いきます",
        "english":"to go",
        "audio":"t2_ikimasu.mp3"
    },
    {
        "id":"tp2_v_5",
        "type":"vocabulary",
        "romaji":"itsu",
        "moji":"いつ",
        "english":"when",
        "audio":"t2_itsu.mp3"
    },
    {
        "id":"tp2_v_6",
        "type":"vocabulary",
        "romaji":"uchi",
        "moji":"うち",
        "english":"house",
        "audio":"t2_uchi.mp3"
    },
    {
        "id":"tp2_v_7",
        "type":"vocabulary",
        "romaji":"e",
        "moji":"え",
        "english":"picture",
        "audio":"t2_e.mp3"
    },
    {
        "id":"tp2_v_8",
        "type":"vocabulary",
        "romaji":"eiga",
        "moji":"えいが",
        "english":"movie",
        "audio":"t2_eiga.mp3"
    },
    {
        "id":"tp2_v_9",
        "type":"vocabulary",
        "romaji":"okimasu",
        "moji":"おきます",
        "english":"to get up",
        "audio":"t2_okimasu.mp3"
    },
    {
        "id":"tp2_v_10",
        "type":"vocabulary",
        "romaji":"o sake",
        "moji":"おさけ",
        "english":"alcohol, rice wine",
        "audio":""
    },
    {
        "id":"tp2_v_11",
        "type":"vocabulary",
        "romaji":"ongaku",
        "moji":"おんがく",
        "english":"Music",
        "audio":"t2_ongaku.mp3"
    },
    {
        "id":"tp2_v_12",
        "type":"vocabulary",
        "romaji":"kaimasu",
        "moji":"かいます",
        "english":"to buy",
        "audio":"t2_kaimasu.mp3"
    },
    {
        "id":"tp2_v_13",
        "type":"vocabulary",
        "romaji":"kaerimasu",
        "moji":"かえります",
        "english":"to go back",
        "audio":"t2_kaerimasu.mp3"
    },
    {
        "id":"tp2_v_14",
        "type":"vocabulary",
        "romaji":"kakimasu",
        "moji":"かきます",
        "english":"to write",
        "audio":"t2_kakimasu.mp3"
    },
    {
        "id":"tp2_v_15",
        "type":"vocabulary",
        "romaji":"kamera",
        "moji":"カメラ",
        "english":"camera",
        "audio":"t2_kamera.mp3"
    },
    {
        "id":"tp2_v_16",
        "type":"vocabulary",
        "romaji":"kikimasu",
        "moji":"ききます",
        "english":"to hear, to listen to, to ask",
        "audio":"t2_kikimasu.mp3"
    },
    {
        "id":"tp2_v_17",
        "type":"vocabulary",
        "romaji":"kyō",
        "moji":"きょう",
        "english":"Today",
        "audio":"t2_kyou.mp3"
    },
    {
        "id":"tp2_v_18",
        "type":"vocabulary",
        "romaji":"ginkō",
        "moji":"ぎんこう",
        "english":"Bank",
        "audio":"t2_ginkou.mp3"
    },
    {
        "id":"tp2_v_19",
        "type":"vocabulary",
        "romaji":"kimasu",
        "moji":"きます",
        "english":"to come",
        "audio":"t2_kimasu.mp3"
    },
    {
        "id":"tp2_v_20",
        "type":"vocabulary",
        "romaji":"kōen",
        "moji":"こうえん",
        "english":"Park",
        "audio":"t2_kouen.mp3"
    },
    {
        "id":"tp2_v_21",
        "type":"vocabulary",
        "romaji":"kō cha",
        "moji":"こうちゃ",
        "english":"black tea",
        "audio":"t2_koucha.mp3"
    },
    {
        "id":"tp2_v_22",
        "type":"vocabulary",
        "romaji":"kōhī",
        "moji":"コーヒー",
        "english":"Coffee",
        "audio":""
    },
    {
        "id":"tp2_v_23",
        "type":"vocabulary",
        "romaji":"gogo",
        "moji":"ごご",
        "english":"afternoon",
        "audio":"t2_gogo.mp3"
    },
    {
        "id":"tp2_v_24",
        "type":"vocabulary",
        "romaji":"gozen",
        "moji":"ごぜん",
        "english":"morning",
        "audio":"t2_gozen.mp3"
    },
    {
        "id":"tp2_v_25",
        "type":"vocabulary",
        "romaji":"gohan",
        "moji":"ごはん",
        "english":"cooked rice, meal",
        "audio":"t2_gohan.mp3"
    },
    {
        "id":"tp2_v_26",
        "type":"vocabulary",
        "romaji":"sakkā",
        "moji":"サッカー",
        "english":"soccer",
        "audio":"t2_sakka-.mp3"
    },
    {
        "id":"tp2_v_27",
        "type":"vocabulary",
        "romaji":"jiten-sha",
        "moji":"じてんしゃ",
        "english":"Bicycle",
        "audio":"t2_jiten-sha.mp3"
    },
    {
        "id":"tp2_v_28",
        "type":"vocabulary",
        "romaji":"shimasu",
        "moji":"します",
        "english":"do",
        "audio":"t2_shimasu.mp3"
    },
    {
        "id":"tp2_v_29",
        "type":"vocabulary",
        "romaji":"shashin",
        "moji":"しゃしん",
        "english":"photograph",
        "audio":""
    },
    {
        "id":"tp2_v_30",
        "type":"vocabulary",
        "romaji":"jūsu",
        "moji":"ジュース",
        "english":"juice",
        "audio":""
    },
    {
        "id":"tp2_v_31",
        "type":"vocabulary",
        "romaji":"shinbun",
        "moji":"しんぶん",
        "english":"newspaper",
        "audio":""
    },
    {
        "id":"tp2_v_32",
        "type":"vocabulary",
        "romaji":"suimasu",
        "moji":"すいます",
        "english":"to smoke, to suck",
        "audio":""
    },
    {
        "id":"tp2_v_33",
        "type":"vocabulary",
        "romaji":"sūpā",
        "moji":"スーパー",
        "english":"supermarket",
        "audio":""
    },
    {
        "id":"tp2_v_34",
        "type":"vocabulary",
        "romaji":"shimasu",
        "moji":"します",
        "english":"to do",
        "audio":"t2_shimasu.mp3"
    },
    {
        "id":"tp2_v_35",
        "type":"vocabulary",
        "romaji":"tabako",
        "moji":"たばこ",
        "english":"tobacco, cigarettes",
        "audio":"t2_tabako.mp3"
    },
    {
        "id":"tp2_v_36",
        "type":"vocabulary",
        "romaji":"tabemasu",
        "moji":"たべます",
        "english":"to eat",
        "audio":"t2_tabemasu.mp3"
    },
    {
        "id":"tp2_v_37",
        "type":"vocabulary",
        "romaji":"chichi",
        "moji":"ちち",
        "english":"my father",
        "audio":"t2_chichi.mp3"
    },
    {
        "id":"tp2_v_38",
        "type":"vocabulary",
        "romaji":"tsukurimasu",
        "moji":"つくります",
        "english":"to make",
        "audio":"t2_tsukurimasu.mp3"
    },
    {
        "id":"tp2_v_39",
        "type":"vocabulary",
        "romaji":"tegami",
        "moji":"てがみ",
        "english":"letter",
        "audio":"t2_tegami.mp3"
    },
    {
        "id":"tp2_v_40",
        "type":"vocabulary",
        "romaji":"depāto",
        "moji":"デパート",
        "english":"department store",
        "audio":"t2_depato.mp3"
    },
    {
        "id":"tp2_v_41",
        "type":"vocabulary",
        "romaji":"terebi",
        "moji":"テレビ",
        "english":"television",
        "audio":"t2_terebi.mp3"
    },
    {
        "id":"tp2_v_42",
        "type":"vocabulary",
        "romaji":"densha",
        "moji":"でんしゃ",
        "english":"electric train",
        "audio":"t2_densha.mp3"
    },
    {
        "id":"tp2_v_43",
        "type":"vocabulary",
        "romaji":"tomodachi",
        "moji":"ともだち",
        "english":"friend",
        "audio":"t2_tomodachi.mp3"
    },
    {
        "id":"tp2_v_44",
        "type":"vocabulary",
        "romaji":"torimasu",
        "moji":"とります",
        "english":"to take a photo or record a film",
        "audio":"t2_torimasu.mp3"
    },
    {
        "id":"tp2_v_45",
        "type":"vocabulary",
        "romaji":"ne masu",
        "moji":"ねます",
        "english":"to go to bed, to sleep",
        "audio":"t2_nemasu.mp3"
    },
    {
        "id":"tp2_v_46",
        "type":"vocabulary",
        "romaji":"nomi masu",
        "moji":"のみます",
        "english":"to drink",
        "audio":"t2_nomimasu.mp3"
    },
    {
        "id":"tp2_v_47",
        "type":"vocabulary",
        "romaji":"hashi",
        "moji":"はし",
        "english":"chopsticks",
        "audio":"t2_hashi.mp3"
    },
    {
        "id":"tp2_v_48",
        "type":"vocabulary",
        "romaji":"basu",
        "moji":"バス",
        "english":"bus",
        "audio":"t2_basu.mp3"
    },
    {
        "id":"tp2_v_49",
        "type":"vocabulary",
        "romaji":"haha",
        "moji":"はは",
        "english":"my mother",
        "audio":""
    },
    {
        "id":"tp2_v_50",
        "type":"vocabulary",
        "romaji":"ban",
        "moji":"ばん",
        "english":"evening",
        "audio":""
    },
    {
        "id":"tp2_v_51",
        "type":"vocabulary",
        "romaji":"pan",
        "moji":"パン",
        "english":"bread",
        "audio":""
    },
    {
        "id":"tp2_v_52",
        "type":"vocabulary",
        "romaji":"ban gohan",
        "moji":"ばんごはん",
        "english":"evening meal",
        "audio":"t2_bangohan.mp3"
    },
    {
        "id":"tp2_v_53",
        "type":"vocabulary",
        "romaji":"hiru",
        "moji":"ひる",
        "english":"noon, daytime",
        "audio":"t2_hiru.mp3"
    },
    {
        "id":"tp2_v_54",
        "type":"vocabulary",
        "romaji":"hiru gohan",
        "moji":"ひるごはん",
        "english":"midday meal",
        "audio":"t2_hirugohan.mp3"
    },
    {
        "id":"tp2_v_55",
        "type":"vocabulary",
        "romaji":"pen",
        "moji":"ペン",
        "english":"pen",
        "audio":""
    },
    {
        "id":"tp2_v_56",
        "type":"vocabulary",
        "romaji":"benkyō shimasu",
        "moji":"べんきょうします",
        "english":"to study",
        "audio":"t2_benkyoushimasu.mp3"
    },
    {
        "id":"tp2_v_57",
        "type":"vocabulary",
        "romaji":"mainichi",
        "moji":"まいにち",
        "english":"every day",
        "audio":"t2_mainichi.mp3"
    },
    {
        "id":"tp2_v_58",
        "type":"vocabulary",
        "romaji":"mizu",
        "moji":"みず",
        "english":"water",
        "audio":"t2_mizu.mp3"
    },
    {
        "id":"tp2_v_59",
        "type":"vocabulary",
        "romaji":"mimasu",
        "moji":"みます",
        "english":"to see, to watch",
        "audio":"t2_mimasu.mp3"
    },
    {
        "id":"tp2_v_60",
        "type":"vocabulary",
        "romaji":"yasumi",
        "moji":"やすみ",
        "english":"rest, holiday",
        "audio":"t2_yasumi.mp3"
    },
    {
        "id":"tp2_v_61",
        "type":"vocabulary",
        "romaji":"yomimasu",
        "moji":"よみます",
        "english":"to read",
        "audio":"t2_yomimasu.mp3"
    },
    {
        "id":"tp2_v_62",
        "type":"vocabulary",
        "romaji":"resutoran",
        "moji":"レストラン",
        "english":"restaurant",
        "audio":"t2_resutoran.mp3"
    },
]

export const kanji = [
    {
        "id":"tp2_k_1",
        "type":"kanji",
        "romaji":"sha/kuruma",
        "moji":"しゃ/くるま",
        "kanji":"車",
        "english":"car",
        "audio":"t2_kuruma.mp3"
    },
    {
        "id":"tp2_k_2",
        "type":"kanji",
        "romaji":"i",
        "moji":"い",
        "kanji":"行",
        "english":"to go",
        "audio":"t2_iku.mp3"
    },
    {
        "id":"tp2_k_3",
        "type":"kanji",
        "romaji":"rai/ ki, ku",
        "moji":"らい/き、く",
        "kanji":"来",
        "english":"to come",
        "audio":"t2_kuru.mp3"
    },
    {
        "id":"tp2_k_4",
        "type":"kanji",
        "romaji":"ki/ kae",
        "moji":"き/かえ",
        "kanji":"帰",
        "english":"to return",
        "audio":"t2_kaeru.mp3"
    },
    {
        "id":"tp2_k_5",
        "type":"kanji",
        "romaji":"hi, bi, ka/ nichi",
        "moji":"ひ、び、か/にち",
        "kanji":"日",
        "english":"day, sun",
        "audio":"t2_nichi.mp3"
    },
    {
        "id":"tp2_k_6",
        "type":"kanji",
        "romaji":"gatsu, getsu/ tsuki",
        "moji":"がつ、げつ/つき",
        "kanji":"月",
        "english":"month, moon",
        "audio":"t2_gatsu.mp3"
    },
    {
        "id":"tp2_k_7",
        "type":"kanji",
        "romaji":"ka",
        "moji":"か",
        "kanji":"火",
        "english":"fire",
        "audio":"t2_ka.mp3"
    },
    {
        "id":"tp2_k_8",
        "type":"kanji",
        "romaji":"sui/ mizu",
        "moji":"すい/みず",
        "kanji":"水",
        "english":"water",
        "audio":"t2_sui.mp3"
    },
    {
        "id":"tp2_k_9",
        "type":"kanji",
        "romaji":"moku/ ki",
        "moji":"もく/き",
        "kanji":"木",
        "english":"tree",
        "audio":"t2_moku.mp3"
    },
    {
        "id":"tp2_k_10",
        "type":"kanji",
        "romaji":"kin/ kane",
        "moji":"きん/かね",
        "kanji":"金",
        "english":"gold",
        "audio":"t2_kin.mp3"
    },
    {
        "id":"tp2_k_11",
        "type":"kanji",
        "romaji":"do",
        "moji":"ど",
        "kanji":"土",
        "english":"soil",
        "audio":"t2_do.mp3"
    },
    {
        "id":"tp2_k_12",
        "type":"kanji",
        "romaji":"ji",
        "moji":"じ",
        "kanji":"時",
        "english":"time",
        "audio":"t2_ji.mp3"
    },
    {
        "id":"tp2_k_13",
        "type":"kanji",
        "romaji":"fun, pun, bun",
        "moji":"ふん、ぷん、ぶん",
        "kanji":"分",
        "english":"minute",
        "audio":"t2_fun.mp3"
    },
    {
        "id":"tp2_k_14",
        "type":"kanji",
        "romaji":"han",
        "moji":"はん",
        "kanji":"半",
        "english":"half",
        "audio":"t2_han.mp3"
    },    
    {
        "id":"tp2_k_15",
        "type":"kanji",
        "romaji":"kon/ ima",
        "moji":"こん/いま",
        "kanji":"今",
        "english":"now",
        "audio":"t2_ima.mp3"
    }
]